### ISSUE TITLE
NA Feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#104]
1- On Add/Edit Student if user select/change any program from drop down
following control sh'd be clear.
Section  
Fee Package  
Discount 
Discount Amount

2-  Fee packages are not dispalying as fractions
![image](https://user-images.githubusercontent.com/19146254/61572378-f48a0800-aab5-11e9-9039-5f52bcd218fc.png)

![image](https://user-images.githubusercontent.com/19146254/61572386-010e6080-aab6-11e9-92c8-b80a2c2e40de.png)

what is exact word? 
![image](https://user-images.githubusercontent.com/19146254/61572396-256a3d00-aab6-11e9-9af4-a723b2ddac22.png)

3 - i registered student in 2  Programs

![image](https://user-images.githubusercontent.com/19146254/61572411-7bd77b80-aab6-11e9-9c1b-7a2a326e32f5.png)

Total amount of each course is same????
i have added diffrent fee packages.

**Comment by serviceproviderpk** [comment]
6) remove label
![image](https://user-images.githubusercontent.com/19146254/61339974-b7293e80-a859-11e9-8a5e-29f471f2a414.png)

**Comment by serviceproviderpk** [comment]
4- Add Inquiry not working , its not adding inquiry

no validation working on Enquiry and not saving in database.
https://www.loom.com/share/d64c342d811f455eafca962d1610423f?focus_title=1&muted=1


5) Show latest transcript on top in grid

**Comment by serviceproviderpk** [comment]
8) add new column "Download" when user click on , attachement will be downloaded.
reduce width of action column
![image](https://user-images.githubusercontent.com/19146254/61340194-b6dd7300-a85a-11e9-8909-d0971f6a67e6.png)

9) on edit enquiry duration is not displaying correct value
![image](https://user-images.githubusercontent.com/19146254/61340223-d83e5f00-a85a-11e9-917c-8a410d52b711.png)

**Comment by serviceproviderpk** [comment]
10) on edit Enquiry i see bread crumb title is "Add"
![image](https://user-images.githubusercontent.com/19146254/61340296-22bfdb80-a85b-11e9-8dce-95e52fd92245.png)

**Comment by serviceproviderpk** [comment]
11) on trasciprt student id and student name is missing

![image](https://user-images.githubusercontent.com/19146254/61340554-459ebf80-a85c-11e9-963f-48f45c14e566.png)

**Comment by serviceproviderpk** [comment]
12) show student id and student name and email as well.

**Comment by serviceproviderpk** [comment]
13) on Transcirpt add 
![image](https://user-images.githubusercontent.com/19146254/61340767-2a807f80-a85d-11e9-96b6-6a3b1001c886.png)


a) heading is missing
b) show search able dropdown 
must search on "Student id,name and email as well" on search result dipslay data as
"studentid + full name  + email"  show  top 50 instead of n records.

this dropdown pattern will be use in all over the projects. if client will request we will change in one place. it will be changed on all places.

**Comment by serviceproviderpk** [comment]
14) on transcript list "Double click " on grid is not displaying edit mode
![image](https://user-images.githubusercontent.com/19146254/61340820-661b4980-a85d-11e9-917d-81fbe9bab934.png)

**Comment by serviceproviderpk** [comment]
15) Adil please make sure both icons are in center of the row verticlly
![image](https://user-images.githubusercontent.com/19146254/61340859-9531bb00-a85d-11e9-9c9b-65a18e0ced94.png)

**Comment by serviceproviderpk** [comment]
16) i am unaable to test  "Add Student" because there is no fee package define.

Please make sure, we have must have proper data in prograam+fee packages and session to test app properly.

**Comment by TahirHussai** [comment]
1- Rename page title in all places from "School Management Software" to "Calgary Academy"
2- on enquiyr page and student page, first character of lablel will be capital others will be small.
4- i can see only two options in programs and both are same. make sure, Program Name must be unique in specific session
5- in Program list where we have mension Duration also mention Hours Please
6.remove label
8.add new column "Download" when user click on , attachement will be downloaded.
reduce width of action column
10.on edit Enquiry i see bread crumb title is "Add"
11.on trasciprt student id and student name is missing
12.show student id and student name and email as well.
13.on Transcirpt add (a)complete and (b) is in progress
14.on transcript list "Double click " on grid is not displaying edit mode

          ############All the Above Mentioned Issues are fixed##########

                                                       #####RFR#######

**Comment by TahirHussai** [comment]
15) 
![image](https://user-images.githubusercontent.com/46710856/61438560-36516c00-a959-11e9-995a-30d82269e4b7.png)

add also cancel button

on cancel clear feed pacakges etc

**Comment by TahirHussai** [comment]
16) add "Hours" where we are displaying "Duraiton"

**Comment by TahirHussai** [comment]
17) http://localhost:22048/Student/index/#

in grid display created date, studentid, name,email

**Comment by TahirHussai** [comment]
18) use currency in all places where we are displaying "Amount or FEE

**Comment by TahirHussai** [comment]
19) on calss edit/create show proper bredcurmb.

**Comment by TahirHussai** [comment]
20- on section screen add icon of "Program" instead of text

**Comment by TahirHussai** [comment]
13.on Transcirpt add (a) and (b) 
16.add "Hours" where we are displaying "Duraiton"
17.http://localhost:22048/Student/index/#  in grid display created date, studentid, name,email
18. use currency in all places where we are displaying "Amount or FEE
19.on calss edit/create show proper bredcurmb.
20.on section screen add icon of "Program" instead of text

**Comment by serviceproviderpk** [comment]
Feedback July 17 2019

**Comment by serviceproviderpk** [comment]
admin detail will be

email : admin@niwe.ca
passowrd: admin321

Branch default login will be as below

Branch Login : ca@niwe.ca
Passowrd:	admin321

1) Set defautt date of Programm end  3 month later.
2)  use validatin on document title.
![image](https://user-images.githubusercontent.com/19146254/61502411-474bbd00-a9ed-11e9-8d72-d25cb8aaf14f.png)

OR

if user dont specify set file name as title

**Comment by serviceproviderpk** [comment]
3) always use not null check PLEASE while you do some action.

. if there is no question data must be save .
![image](https://user-images.githubusercontent.com/19146254/61502501-a6a9cd00-a9ed-11e9-8fc5-8ece86768381.png)

**Comment by serviceproviderpk** [comment]
4- in all js function. if there is error un-block UI and show message in alert.

Sytem error + show error message

**Comment by serviceproviderpk** [comment]
5- in enquiry Grid show follwing fields as well with sequesne

Inquiry ID,Date,Status, Name,Email,Phone,Mobile,Postal code, city

**Comment by serviceproviderpk** [comment]
6) use standard spaces from top and bottom of all pages. it must be consistent plese

![image](https://user-images.githubusercontent.com/19146254/61502798-c5f52a00-a9ee-11e9-8df8-30515d1101b3.png)

**Comment by serviceproviderpk** [comment]
7) on add student, I selecteced one program and saved, again i choose an other program.
feed package not displayed, and also dont see the   "Add" button.

**Comment by serviceproviderpk** [comment]
8) on edit student  screen, i tried to register new Program.
fee section not displayed.

![image](https://user-images.githubusercontent.com/19146254/61503005-8f6bdf00-a9ef-11e9-9b2b-799bf08fab10.png)

Please test it properly with diffrent flows.

**Comment by serviceproviderpk** [comment]
9) from stuent grid, i click on edit button. "Only changed" Date of Birth. and click on next and save button.
getting error on fee.
![image](https://user-images.githubusercontent.com/19146254/61503166-289af580-a9f0-11e9-984c-8b27f2f3f9e2.png)

**Comment by serviceproviderpk** [comment]
6) on Student Leave Form i logged in as admin

Bind student drop down as i said more than 5 times

Student id+" - "+  Full name +"-  " + Email

IN ALL PLACES WHERE WE ARE BINDING STUDENT DROP DOWN!!!!!!!!!!!!

**Comment by adilshehbaz** [comment]
**Feedback July 17 2019
Fixed points are

1,2,3,5,6,7,8,9,10**

**Comment by serviceproviderpk** [comment]
11- @TahirHussai 
 remove back ground color
![image](https://user-images.githubusercontent.com/19146254/61571823-fd77db00-aaaf-11e9-8a2c-c80ee1ad6f96.png)
in database only show two employee type, remove other dummy
a) Senior Employee
b) Junior Employee
c) refresh button in all screen must be in center.
e) email already exist lable errorr shd be hiddedn by default. (discuss with me, i will guide you.)

![image](https://user-images.githubusercontent.com/19146254/61571862-60697200-aab0-11e9-8c71-37b9f9565f70.png)

**Comment by serviceproviderpk** [comment]
12) there are bundle of chart of account can we display only few account maximum 5
![image](https://user-images.githubusercontent.com/19146254/61571891-93ac0100-aab0-11e9-9be3-c9f310867d02.png)

13) when an employee is created we will send him email


Dear  Ali,

Your account is created  on Calgary Academy. below are your login details.

Email: email@mail.com
Password: yourpassword

Regards,
Calgary Academy Team

**Comment by serviceproviderpk** [comment]
13) remove phone number pattern 
![image](https://user-images.githubusercontent.com/19146254/61571990-70ce1c80-aab1-11e9-82c0-ff23e4751ff0.png)
14) default date of birth must be  01/01/2000

**Comment by serviceproviderpk** [comment]
15) on edit employee if there is no photo show defult photo
![image](https://user-images.githubusercontent.com/19146254/61572057-049fe880-aab2-11e9-95b7-5eb5421edc99.png)

**Comment by serviceproviderpk** [comment]
16) change color accoreding to theme
![image](https://user-images.githubusercontent.com/19146254/61572143-d373e800-aab2-11e9-97c4-0d6a6c23caa6.png)

also remove scrolling

**Comment by serviceproviderpk** [comment]
17)  Transcirpt must be displayed from user rights.
![image](https://user-images.githubusercontent.com/19146254/61572188-2cdc1700-aab3-11e9-9db4-a2d4b1ec616e.png)

**Comment by serviceproviderpk** [comment]
18) i created a group give him 2 permission

- manage students
- manage inquiry

as i logged manage students menu was not visible for him.

and trascripts menu was visible although i never give permissin to this.

**Comment by serviceproviderpk** [comment]
19) on add inquiry no validation working.
![image](https://user-images.githubusercontent.com/19146254/61572233-cb687800-aab3-11e9-933a-bbca5eecddee.png)

try email sending in try catch plz

**Comment by serviceproviderpk** [comment]
21-  on add student/Inquiry 
send email to the Student

[Dear Ali,

Your account is created with following details

Email: email@email.com
Password : yorpassowrd

Regards,
Calgary Academy](url)


---------------------

Dear Ali,

Thanks for visit us.

Regards,
Calgary Academy

**Comment by serviceproviderpk** [comment]
22- check drop  of student on "Manage Enrolment Contract"

Student id+" - "+ Full name +"- " + Email

**Comment by serviceproviderpk** [comment]
23- "ALBERTA ENROLLMENT CONTRACT"
show all field  on add/edit screen and print view must 100% same.

we will have  separate contract for each program.

we can  save Program Id in contract.
 or we can diffrrent text boxes to add data in progam sections.

as below document

[2019 ALBERTA ENROLLMENT CONTRACT.pdf](https://github.com/serviceproviderpk/sp.pk/files/3413154/2019.ALBERTA.ENROLLMENT.CONTRACT.pdf)

**Comment by serviceproviderpk** [comment]
[NIWE REGISTRATION_LOAN CHECKLIST MAR_19.docx](https://github.com/serviceproviderpk/sp.pk/files/3413157/NIWE.REGISTRATION_LOAN.CHECKLIST.MAR_19.docx)
24- Loan registration form is missing

**Comment by serviceproviderpk** [comment]
25) Remove Web Portal menu for layout page.
