### ISSUE TITLE
NA Feedback 4 Tahir

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#105]
0)
in sudent application

display  "StudentID " - " + Name + " - " - Email
1) in menu add menu 
"Manage Documents" that will display following document

a) Student Handbook
b) NIWE REGISTRATION_LOAN CHECKLIST MAR_19

on add/edit maintain history of the document. (in new table that is "DocumentHisotry"
c) add  "Download" button in grid of document and document history

**Comment by serviceproviderpk** [comment]
2) 
 Student can apply for leave (enter reason), hide status 
 Staff can view/approve leave (can change status) and can enter remakrs.

Student can view leave status. get email as leave is approved/rejected.
--------------
Dear Admin,

Ali has applied for  Leave status.

Reason:

Thanks,
Student Name,

----------

Dear student name,
Your leave is leave status.
Remarks:

Regards,
Calgary  Academy,

**Comment by serviceproviderpk** [comment]
Incident(Id,,CreatedByUserId,StudentId,CreatedDateTime,IncidentDAte,,incidentTime,address,phone,DepartmentLocation,WhatHappend,
Injurydetails,WitenessName,WitenessEmail,WitenessPhone,First Aid Given,Ambulance, Call91 called? 
OtherwintensName,OtherWitneesEmail,OtherWitnessPhone)
IncidentDocument(IncidentDocumentId,IncientId,,Title,FileURL,createdDate,CreatedByUserid,)
Incident report
1.	will send an incident report form
2.	This will be a simple form that can be filled by anyone in staff for a student
3.	Form should have the capability of adding attachments
4.	This will exist independently and admin can search it by Student name

My apologies for the delay please see below,

Injured Student/Client Name Date of IncidentTime

Injured Student/Client Address and Phone Number

Department Location where accident occurred

Describe what happened:

Describe Injury:

School Employees or students who witnessed incident: 
NameAddressPhone No.

Medical Response
Was medical attention needed or provided?
First Aid Given: Yes No  Ambulance Yes  No 911 called? Yes  No 

Other Witness Contact Information
NameAddressPhone No.

Follow-up (if applicable):

Instructor/Site Administrator Signature Date

**Comment by serviceproviderpk** [comment]
dobule check my all feedabck.

**Comment by TahirHussai** [comment]
0.in sudent application

display "StudentID " - " + Name + " - " - Email
1.in menu add menu
"Manage Documents" that will display following document
2.Student can apply for leave (enter reason), hide status
Staff can view/approve leave (can change status) and can enter remakrs.
Student can view leave status. get email as leave is approved/rejected.


################################RFR#################
