### ISSUE TITLE
Feedback July23

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#106]
Can you please remove  remote attributed related code or lines from all over the project.
email address is behaving strangely.
i enter email it is auto set empty.

0) I  created/edited an inquiry i see status is empty

![image](https://user-images.githubusercontent.com/19146254/61675889-6ca13980-ad13-11e9-92a9-62a442e15a48.png)

1) Program 
a) write "Hours" in front of Duration
![image](https://user-images.githubusercontent.com/19146254/61674334-d66a1500-ad0c-11e9-8e5d-edfc56f4b012.png)

in all places where we are displaing dropdown of Prograam
bind it as

"Program Name + "-Startdate-enddate-duration hours"
e.g  "Nail - 01/07/2019 - 30/072019 - 500 Hour

b) Use currency  symbol in all places where we are displaying Fee/Amount

these point was also written in my prvious feedback

**Comment by serviceproviderpk** [comment]
2) On add student . we can not force any student to join atleast 1 program.
![image](https://user-images.githubusercontent.com/19146254/61675496-01a33300-ad12-11e9-9782-26d293433c80.png)

Please correct spelling of programs.

**Comment by serviceproviderpk** [comment]
3) i have added program
 after discount total some is 500.99 
as below
![image](https://user-images.githubusercontent.com/19146254/61675676-b4739100-ad12-11e9-9413-e69f2be0215b.png)

![image](https://user-images.githubusercontent.com/19146254/61675694-cb19e800-ad12-11e9-946e-0e480204a67f.png)

if i re-edit it is displaying 501

![image](https://user-images.githubusercontent.com/19146254/61675734-f8ff2c80-ad12-11e9-92b3-e28bf4d9d678.png)

we can not ignore  "cennts / fraction values"
Still currency symbol is missing 

make sure in all placed show fee/amount as 2 decimal places.

**Comment by serviceproviderpk** [comment]
4) Inquiry email tempalte is not same as i written in github. before few weeks

![image](https://user-images.githubusercontent.com/19146254/61675950-a83c0380-ad13-11e9-8143-06c32e073d07.png)
5) remove student card option from all places and from reports as well.
6) default image still missing 
![image](https://user-images.githubusercontent.com/19146254/61676502-ae32e400-ad15-11e9-8b35-9afe836c5cfc.png)
it was on previous feedback as well.

5) 
![image](https://user-images.githubusercontent.com/19146254/61677056-90ff1500-ad17-11e9-9bc3-d8a027ee194a.png)
the have written optional
we have used validation for that field.

i will re-test as you will say all feedback is done from my side.

please dont depends on Tahir, Please take responsibility!!!!!

**Comment by serviceproviderpk** [comment]
https://github.com/serviceproviderpk/smspk/issues/139
https://github.com/serviceproviderpk/sp.pk/issues/104
https://github.com/serviceproviderpk/sp.pk/issues/106

re-verify my feedback  AND SPRINT 1
re-verify my feedback  AND SPRINT 1
re-verify my feedback  AND SPRINT 1

**Comment by serviceproviderpk** [comment]
if my all feedback done  start work on fee collection.

 Payment Method: E-Transfer, Niwe Referral, Cheque, and Debit
 Payment Type:  Full cash payment, Loan Installments

1. Full cash payment - Some students pay upfront for the entire course 
2. Loan Installments - Alberta Student Aid will provide loan to student and payment  would be issued in installments as well

In rare cases installment is given when the student has not completed 50% or less of the entire program.  

Suggestion!

when we will register a student, in confirmation box we will display 2 option.

"Account is successfully, created"
with following 2 buttons.

"Download" and "Collect Payment"


)  Tutition fee
) Books and supplies fee
) Registration fee 

 ) page from where fee can be collected for any student
)  from this page remaining balance of student can be verified
) Fee receipt can  be issue for printing
) Payment method: Cash / Bank Trasnfer/ Credit Card
) Full cash payment - Some students pay upfront for the entire course 
2. Loan Installments - Alberta Student Aid will provide loan to student and payment  would be issued in installments as well

In rare cases installment is given when the student has not completed 50% or less of the entire program.  
Only single payment gateway option will be given including what we have right now.

**Comment by serviceproviderpk** [comment]
Please test each and every section by adding proper data.
when you check in code and db, Make sure, in each section atleast 1 record is added with proper data and proper alignment.

**Comment by adilshehbaz** [comment]
Download PDF Option in student registration , enrolment, firstcontact form,

**Comment by serviceproviderpk** [comment]
@@adilshehbaz  re-test above all task and message me. on whatsapp.
