### ISSUE TITLE
Feedback Urgnet

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#110]
in trello client as provided new logo please use that logo on log page and forget password page as welll
![NIWE_Academy_Cosmetology_ _Massage](https://user-images.githubusercontent.com/19146254/61849797-e419c900-aecb-11e9-8040-71ec23abe122.png)

**Comment by serviceproviderpk** [comment]
2) in Add Programm
i added fee as  .50 , .40

![image](https://user-images.githubusercontent.com/19146254/61850476-dcf3ba80-aecd-11e9-9c8a-6e293fa13f53.png)

on edit it was displayed as .5 and .4

**Comment by serviceproviderpk** [comment]
3- from Program grid and Feepacakged grid remove delete button Please!!!!

**Comment by serviceproviderpk** [comment]
4) Email subject  of Student registartion must be

"NIWE - Student Registration"

and on Inquiry email subject


"NIWE - Student Inquiry"

**Comment by serviceproviderpk** [comment]
5) if create an Inquiry "Status " is emppty
in grid

if re-edit this status is ok

![image](https://user-images.githubusercontent.com/19146254/61852085-06aee080-aed2-11e9-929c-ce6d6353119b.png)

**Comment by serviceproviderpk** [comment]
6) on Inqiury Grid, if i click on download button
i see  QA/index page

**Comment by serviceproviderpk** [comment]
7- Display proper data 
![image](https://user-images.githubusercontent.com/19146254/61853756-18928280-aed6-11e9-82d4-484ecadd9b28.png)

![image](https://user-images.githubusercontent.com/19146254/61853831-4081e600-aed6-11e9-9afa-967d3faea065.png)

**Comment by serviceproviderpk** [comment]
8- 
![image](https://user-images.githubusercontent.com/19146254/61854284-301e3b00-aed7-11e9-869b-425f238cafea.png)

**Comment by serviceproviderpk** [comment]
9) in all project replace "RS" with "$"

**Comment by adilshehbaz** [comment]
Validation not shoing message on global documents

**Comment by adilshehbaz** [comment]
No validation on Transcript

**Comment by adilshehbaz** [comment]
Enrollment contract form pdf remains
