### ISSUE TITLE
FYP  hsmp

### ISSUE THREAD

**Issue by MughalBilal** [serviceproviderpk/sp.pk#12]

**Comment by MughalBilal** [comment]
**Bilal Task**

1:-system look up module add sub module name Patient Status and performing crud Add, update, and view list on index page ## **(fix)/Muhammad Bilal**

2:-system look up module add sub module name Appointment Status and performing crud Add, update, and view list on index page **(fix)/Muhammad Bilal**

3:-Add field patient table are Bed no and ward no **(fix)/Muhamad Bilal**

4:-Add module left side menu Manage Appointments performing crud crete update and and show list on index page  and bind drop down on crete screen are Appoint status, Doctors,Patient 
**(fix)/Muhamad Bilal**

5:-Layout remove settings option and remove search **(fix)/Muhamad Bilal**

6:-All button formatting change**(fix)/Muhamad Bilal**

7:-Admin side layout formatting change **(fix)/Muhamad Bilal**
8:-Edit profile (Fix by Tayyab)
9:-Forget password(Fix by Tayyab)

10:-Title Login page  According to the documentation**(fix)/Muhamad Bilal**

11:-Login Box show Center page **(fix)/Muhamad Bilal**

12:-Error message show in login div**(fix)/Muhamad Bilal**

13:-Side menu background white **(fix)/Muhamad Bilal**

14:-navbar background white**(fix)/Muhamad Bilal**

15:-Hospital background red and font color white**(fix)/Muhamad Bilal**

16:-profile box formatting (Fix by Tayyab)

17:-System users add module system type like doctor, admin,labmanager,recetionist (Fix by Tayyab)

19:-Remember me **(fix)/Muhamad Bilal**

**Comment by MughalBilal** [comment]
**Tayyab**

doctor menu should be same as in document and all page should working as in documents (fix by Tayyab)

**Comment by serviceproviderpk** [comment]
**Below are Pending issues**

**Comment by serviceproviderpk** [comment]
21- When Lab Manger : login show him same page as in Documentation (fix by Tayyab)
22- When Receiptionist : login show him same page as in Documentation(fix by Tayyab)
18:- Add search on lists of admin, lab manager, doctor, receptionist **(fix)/Muhamad Bilal**

**Comment by serviceproviderpk** [comment]
23- Patient Hisotry: test ,medicine,operation etc
24-Patient Account for view his record.
25-Patient  Appointment Request option
26-Move patient from indoor to outdoor**(fix)/Muhamad Bilal**
27-Billing report for patient
28-MedicalTestReport Create and detail  **(fix)/Muhamad Bilal**
29-Profile Photo**(fix)/Muhamad Bilal**
30-Login Allignment **(fix)/Muhamad Bilal**
31-Add Proper Data for testing (Enter 3 entires)
32-Show drop down on login page to select Account type then login.**(fix)/Muhamad Bilal**
