### ISSUE TITLE
Feedback July29

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#121]
1) ON manage students "Student search" not working properly i see null value in textbox right side of student name.
remove auto complete, we will implement wild search on text box.
2) use block UI on this screen
http://niwe.schoolmanagementsoftware.pk/SystemSettings/BrowseUserGroup/BrowseUserGroupIndex

3) in below page use Delete option so that we can delete any rights when we neeed it.

http://niwe.schoolmanagementsoftware.pk/SystemSettings/ManageSystemRight/Index

1.Student search is working  but issue in auto complete    2.Fix , 3.Fix,

**Comment by serviceproviderpk** [comment]
2) remove green color
![image](https://user-images.githubusercontent.com/19146254/62074388-188add80-b25c-11e9-9db8-1bd347e1464d.png)

i clicked on download file getting error

**Comment by serviceproviderpk** [comment]
3) spacing on  pdf document not same as in provided pdf

**Comment by serviceproviderpk** [comment]
4) Enrolment Contract shd be dipslayed of ONLY selected brnach. it is showing data of other brnach


![image](https://user-images.githubusercontent.com/19146254/62075732-4f162780-b25f-11e9-855b-7d33dca0b18b.png)

**Comment by serviceproviderpk** [comment]
5) For branch loging show "Manage Group rights" screen so that branch can  add/edit rights to any staff or can create new group.

**Comment by serviceproviderpk** [comment]
6) If  we  upload document for employe contract , show link to download that document.
![image](https://user-images.githubusercontent.com/19146254/62076298-c26c6900-b260-11e9-97c9-cc43e686b686.png)

**Comment by serviceproviderpk** [comment]
7) Document types, and documents must be displayed of selected branch
![image](https://user-images.githubusercontent.com/19146254/62076399-fe073300-b260-11e9-9be9-ff121d052de3.png)

**Comment by serviceproviderpk** [comment]
8) Transcript must be displayed of selected branch

**Comment by serviceproviderpk** [comment]
6) use white broder for image control so that all types of images must be visible
![image](https://user-images.githubusercontent.com/19146254/62095316-7b4e9a00-b299-11e9-8be8-f36dae5a5ded.png)

7) rename print to "Download" as i requested already in my previous feedabck
6.Fix,7.Fix
*************************Button is remaned from print to Download**************************

**Comment by serviceproviderpk** [comment]
excel file to import data, but its not importing data, Please modify it according to our new database table of student.
[Students.xlsx](https://github.com/serviceproviderpk/sp.pk/files/3444671/Students.xlsx)

**Comment by serviceproviderpk** [comment]
3) spacing on  pdf document not same as in provided pdf

**Comment by SajjadAhmad111** [comment]
> 1. use white broder for image control so that all types of images must be visible
>    ![image](https://user-images.githubusercontent.com/19146254/62095316-7b4e9a00-b299-11e9-8be8-f36dae5a5ded.png)
> 2. rename print to "Download" as i requested already in my previous feedabck
>    6.Fix,7.Fix
>    _************************Button is remaned from print to Download************************_*

Still Remaining

**Comment by SajjadAhmad111** [comment]
> 1. use white broder for image control so that all types of images must be visible
>    ![image](https://user-images.githubusercontent.com/19146254/62095316-7b4e9a00-b299-11e9-8be8-f36dae5a5ded.png)
> 2. rename print to "Download" as i requested already in my previous feedabck
>    6.Fix,7.Fix
>    _************************Button is remaned from print to Download************************_*

Still Remaining
