### ISSUE TITLE
Faheem Ijaz

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#13]

**Comment by serviceproviderpk** [comment]
1.remove above section in side manue  (fixed)
3.Create and manage posts  combine   (fixed)
4.Add the images in postCategory   (fixed)
5. make controler of  and make Technolgies page like http://www.c-sharpcorner.com/technologies
List>   (Fixed)
6. List of Post by Category  like http://www.c-sharpcorner.com/technologies/dot_net_2015  (Fixed)
7.  show post detail by PostID  (fixed)
8. On post detail page.  comments section.(Inprocess)
Name, Email
Comment Box


9. run this script, to create new table in DB  (Fixed)

```

GO

/****** Object:  Table [dbo].[IE_StaticPages]    Script Date: 11/28/2017 7:20:11 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IE_StaticPages](
	[IE_StaticPageID] [bigint] IDENTITY(1,1) NOT NULL,
	[StaticPageCode] [int] NULL,
	[Title] [nvarchar](500) NULL,
	[Description] [nvarchar](max) NULL,
	[PageTitle] [nvarchar](max) NULL,
	[PageDescription] [nvarchar](max) NULL,
	[PageKeywords] [nvarchar](max) NULL,
	[SNO] [int] NULL,
 CONSTRAINT [PK_IE_StaticPages] PRIMARY KEY CLUSTERED 
(
	[IE_StaticPageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

```



Static Pages, Please add following static pages link in footer.  (Fixed)


- Home
- Events
- Consultants
- Jobs
- Career Advice
- Stories
- Partners

Learn Asp.net mvc
Learn C#
Learn Jquery
Learn SQL Server
Learn Azure
Learn Web Deployment
Learn SEO



and 

- About Us
-  Contact Us
-  Privacy
-  Policy
-  Terms
-  Sitemap
-  Report a Bug 
- FAQ

Footer should be look like this
![image](https://user-images.githubusercontent.com/19146254/33298970-3bf54700-d40b-11e7-9507-f869701731da.png)

**Comment by serviceproviderpk** [comment]
1. Fixed
2. Fixed

**Comment by mfaheemijaz** [comment]
1-Fixed
3-Fixed
4-Fixed
5-Fixed
9-fixed
