### ISSUE TITLE
QA Feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#131]
1)  Login history must be displayed of logged in branch ONLY
latest data on top. make sure it will be visible only for admin NOT for  employee
http://niwe.schoolmanagementsoftware.pk/LoginHistory/Index/

branch name is empty remove this column or display branch name
![image](https://user-images.githubusercontent.com/19146254/62422620-e69bd000-b6ce-11e9-896c-d16a4cdf2fc8.png)

**Comment by serviceproviderpk** [comment]
2)  in all places where we are showing programss in dropddown make sure
we must display active Programs ONLY
![image](https://user-images.githubusercontent.com/19146254/62422637-472b0d00-b6cf-11e9-8f6f-7dd61728472c.png)

**Comment by serviceproviderpk** [comment]
3) I imported student from excel file, it was imported successfully,  then i click on "Manage students"
and tried to edit that student which was imported.

Screen was hanged/block. maybe some data was not imported. (in short on imported student)
Edit button not working.
![image](https://user-images.githubusercontent.com/19146254/62424063-ff15e580-b6e2-11e9-86e6-a27e3a976938.png)

**Comment by serviceproviderpk** [comment]
4) i created new branch and logged in as student
i see below error
![image](https://user-images.githubusercontent.com/19146254/62424174-9596d680-b6e4-11e9-9e7e-a5aaf577df92.png)

**Comment by serviceproviderpk** [comment]
5) on manage document section, i tried to upload exe it was uploaded 
![image](https://user-images.githubusercontent.com/19146254/62424197-1229b500-b6e5-11e9-9b01-7d9139b5c83a.png)

i requeested you, YOU yourself work on this task...........

as i said many time.

we will add max length check on all fileupload control
only will allow discussed extensions ONLY

![image](https://user-images.githubusercontent.com/19146254/62424216-4a30f800-b6e5-11e9-813b-b05d3f2bbae4.png)

**Comment by serviceproviderpk** [comment]
6)  Enrollment contract 
Unit is empty
![image](https://user-images.githubusercontent.com/19146254/62424274-14404380-b6e6-11e9-8a48-7ce9675fbe65.png)

**Comment by serviceproviderpk** [comment]
7) remove from menu activiity log as  its not displaying activity
![image](https://user-images.githubusercontent.com/19146254/62424299-739e5380-b6e6-11e9-8f4f-8850e46ac6d0.png)

8) check spelling plz
![image](https://user-images.githubusercontent.com/19146254/62424489-68e4be00-b6e8-11e9-879a-78a53691f08e.png)

**Comment by serviceproviderpk** [comment]
9)  Student/Inquiry/Employee you have added in Front end for duplicate email.
also check from backend check.

we will not allow duplicate emails in the system, as this issue is raisded by Umer.

**Comment by serviceproviderpk** [comment]
10) 
![image](https://user-images.githubusercontent.com/19146254/62427055-7e68e080-b706-11e9-9148-bbe101620180.png)
a) Flat discount amount must not be greater than actual amount 
b) Discount % must  not be greater than 100%

**Comment by serviceproviderpk** [comment]
11) on edit leave, if we click on right side. drop down must be expanded.
![image](https://user-images.githubusercontent.com/19146254/62427293-6f842d00-b70a-11e9-8c05-e42740b58d67.png)

a) on edit leave show all students OR hide drop down just display student name+id+email as label

**Comment by serviceproviderpk** [comment]
12) Manage students grid "remove registeration" form
![image](https://user-images.githubusercontent.com/19146254/62427380-b32b6680-b70b-11e9-9142-269b75bc2251.png)

**Comment by serviceproviderpk** [comment]
13) on manage studdents > Terminated students>
a) if we restore a student on prompt screen close button not working.
In Struck off and terminated Close button is not working
![Issue](https://user-images.githubusercontent.com/50301383/62426895-52e4f680-b704-11e9-8729-46d36c0180e4.PNG)

b) also remove  auto complete search form Terminated and struck of tabs

![image](https://user-images.githubusercontent.com/19146254/62427465-dacefe80-b70c-11e9-829d-cd32134e12cc.png)

**Comment by serviceproviderpk** [comment]
14)From manage employe grid remove  add document  (reason time is short )

![image](https://user-images.githubusercontent.com/19146254/62427597-bd029900-b70e-11e9-84fc-6a4fa50d58ab.png)

**Comment by serviceproviderpk** [comment]
remove delete button and  x-employee

**Comment by TahirHussai** [comment]
![FeeAmountIssues](https://user-images.githubusercontent.com/46710856/62462186-439e9100-b776-11e9-84d4-52fbdf44a26d.PNG)
When create Class user add fee packages of that class fee package limit is 2 lakh but i am entering value 200001 no validation is occur

**Comment by SajjadAhmad111** [comment]
> 1. I imported student from excel file, it was imported successfully,  then i click on "Manage students"
>    and tried to edit that student which was imported.
> 
> Screen was hanged/block. maybe some data was not imported. (in short on imported student)
> Edit button not working.
> ![image](https://user-images.githubusercontent.com/19146254/62424063-ff15e580-b6e2-11e9-86e6-a27e3a976938.png)

Issue is still remaining
