### ISSUE TITLE
NiwWe Mid Priorty task

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#132]
-

**Comment by serviceproviderpk** [comment]
a ) set hight of both text boxes same please
![image](https://user-images.githubusercontent.com/19146254/62424082-48fecb80-b6e3-11e9-842f-41e898259481.png)

**Comment by SajjadAhmad111** [comment]
> a ) set hight of both text boxes same please
> ![image](https://user-images.githubusercontent.com/19146254/62424082-48fecb80-b6e3-11e9-842f-41e898259481.png)

Issue is rmaining still

**Comment by SajjadAhmad111** [comment]
> > a ) set hight of both text boxes same please
> > ![image](https://user-images.githubusercontent.com/19146254/62424082-48fecb80-b6e3-11e9-842f-41e898259481.png)
> 
> Issue is remaining still
