### ISSUE TITLE
Student Leave

### ISSUE THREAD

**Issue by SajjadAhmad111** [serviceproviderpk/sp.pk#136]
In student leave when we edit any student from the Grid of leave student.Then in Student Name drop down the complete list of manage student Should be show but in this Case only the present student is being Shown.While the list of Student consist of three student
![LeaveStudenteditdropdown](https://user-images.githubusercontent.com/50301383/62427096-12d34300-b707-11e9-96ad-b96ffb676722.PNG)

**Comment by serviceproviderpk** [comment]
This is default behaviour of the features

**Comment by serviceproviderpk** [comment]
we must hide drop down in edit leave.
