### ISSUE TITLE
Spelling Mistake  of Attendance in Mark Attendance

### ISSUE THREAD

**Issue by SajjadAhmad111** [serviceproviderpk/sp.pk#152]
![SpellingMistake in Attendance Sheet](https://user-images.githubusercontent.com/50301383/63409385-8022eb80-c40a-11e9-9acc-a11076aa0cf0.PNG)

**Comment by TahirHussai** [comment]
Spelling Mistake of Attendance in Mark Attendance
######################################Fixed###################
