### ISSUE TITLE
Successfully spelling mistake in Terminated Student and Struck off Student Pop Up

### ISSUE THREAD

**Issue by SajjadAhmad111** [serviceproviderpk/sp.pk#154]
In terminated student Successfully Spelling is incorrect also when we Restore Terminate student to Manage Student.
![Successfully](https://user-images.githubusercontent.com/50301383/63422327-94271700-c423-11e9-9e4d-20ce60e8bfa1.PNG)

**Comment by TahirHussai** [comment]
In terminated student Successfully Spelling is incorrect also when we Restore Terminate student to Manage Student.
##############################Issue Fixed####################
