### ISSUE TITLE
SPPKWEB

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#16]

**Comment by serviceproviderpk** [comment]
@MughalBilal 
3-For facebook URL use this link plz for all social media accounts 
https://www.facebook.com/serviceprovider.pk/
4- when i fill this form  
http://beta.serviceprovider.pk/ContactUs/CreateEnquiry

I am getting error. we should get email and saved enquiry in DB.
error is 
![image](https://user-images.githubusercontent.com/19146254/34237532-01f00a60-e61f-11e7-9103-b4f8d92f8696.png)

5- when user subscribe show him message

Thanks, for joining us, we will keep you update about our offers.
6- Change office timing  9AM - 6PM
Sunday Close
7-project detail page giving error
http://beta.serviceprovider.pk/BrowseProjects/ProjectDetail?ProjectID=32

8- NOTE!  Set Proper meta data for  all pages
9- Use Proper URL for each page like
  http://beta.serviceprovider.pk/About-us
http://beta.serviceprovider.pk/Clients
http://beta.serviceprovider.pk/Projects
http://beta.serviceprovider.pk/Contact-us
http://beta.serviceprovider.pk/Training
http://beta.serviceprovider.pk/Enquiry
http://beta.serviceprovider.pk/Services

10- If i click on portfolio from footer it 

![image](https://user-images.githubusercontent.com/19146254/34237770-42757196-e620-11e7-9773-3ca47a5aa06b.png)


showing wrong page , rename "PortFolio" to "Portfolio"
11-

**Comment by MughalBilal** [comment]
Ok sir i will check and fix these issues..

**Comment by serviceproviderpk** [comment]
12-Title of page should be  proper  on "Submit Your Problem" page title is  "Conat us" , it should be "Submit your Problem"
13- In footer links  proper url is not enabled. still is i can  old urls
14-Please use consistency for URL  http://beta.serviceprovider.pk/contactus
should be http://beta.serviceprovider.pk/Contactus  (First letter will be capital)
15- in projects please add proper data with images. so that we can make it live asap
16-in client add proper data with images
17-if i set serial number of 1 for project and client it should display on top and 2 on second and 3 on 3rd and so on.
if you will sort by "SerialNo"
18-on CRUD of project clients  use plz textaread for description fields or some other field where multiline text is required.
19- Please all text carefully
![image](https://user-images.githubusercontent.com/19146254/34316876-a660c6ee-e7c2-11e7-8e43-cdb0ec70fc4e.png)

20-when I login as admin. there should be  menu
"Web Portal" it will have submenu
Enquiry,Tasks,Static Pages,Clients,Projects. Enquiry/Quotation submission list.

**Comment by serviceproviderpk** [comment]
21-use tool tip on each icon/menu
22- Use Proper meta tags for each page this task very important as its done we will do release

**Comment by serviceproviderpk** [comment]
23- I logged in as admin, I tried to edit "Project", it is forcing me to  "Choose" Image. i just want to edit "Title" only. on edit project, already added data should be show in textboxes.

**Comment by serviceproviderpk** [comment]
1-Create two more banner just like blow banner (color scheme is looking good).
![image](https://user-images.githubusercontent.com/19146254/34450503-681bf11e-ed2c-11e7-9c4c-08f462baa600.png)
2-Route of this page"http://serviceprovider.pk/BrowseAllTask/SubmitYourProblem"
should be "http://serviceprovider.pk/SubmitYourProblem
3-Email will be use as "UserName" so this page will have only following fields
-Contact Name, Email,Phone,Message,Title will be set from backend
like "Request by "+Contact Name
4- Use re-captcha on  following page
a) Submit your problem, signup and contact us
5-Change Look and feel of "Singh"and"Signup page just like a "/contactus"
and also remove social icon from Sign in page.
Please use "Login"and  "Register" name in all portal instead of "Signin" and Signup. (in all places)
6-in footer relpace "Fax" with Cell and use this number "0307 4585990"
7-on "/contactus" page also show this number "0307 4585990" it should be set from web.config

**Comment by serviceproviderpk** [comment]
8-Contactus page Url should be like "serviceprovider.pk/contact-service-provider
about use page url should be like"serviceprovider.pk/about-service-provider
submityourproblem url should be"serviceprovider.pk/submit-your-problem-to-service-provider
"http://serviceprovider.pk/BrowseServices"should be http://serviceprovider.pk/services
"http://serviceprovider.pk/BrowseOurClients" should be "http://serviceprovider.pk/our-clients
detailed routes "http://serviceprovider.pk/BrowseProjects/ProjectDetail?ProjectID=32" should be like this

http://serviceprovider.pk/projects/project-title-32

**Comment by serviceproviderpk** [comment]
17. this route should be in working for. http://www.serviceprovider.pk/food-and-drink-3-in-pakistan

**Comment by serviceproviderpk** [comment]
@MughalBilal  when you comment please use "Fixed" as Bold like  "FIXED"

**Comment by serviceproviderpk** [comment]
@MughalBilal Please test all issue those are listed if fixed then update me. I'll test it.

**Comment by serviceproviderpk** [comment]
15- I have created new table "Todolist" just refresh "edmx" file and attached latest DB.
perfrom crud of "Todolist"
CreatedDate/AssingedDate/CreatedBy will be set from backend. 

AssignedTo (will choose from dropdown
show list of users whose type is admin and developer".
Details and priority will be set from UI.

jo task create kery ga wohe os ko delete ker sakta hay.

when user logged show him "ToDolist" assingeto him and order by priroity.

for add/edit/list use single screen instead of diffrent pages.

Dont use any StoreProcedure, you can use LINQTOSQL, nawab can help you, he will create a single
that will show list. # **Fixed**


16- when i login as admin "on dashobar" page show four section as we did in ebike

a) "To Do List (show logged in user to do list)", "Submitted Problem", "Inquiry", "Admissions.
  # Fixed

**Comment by serviceproviderpk** [comment]
17- Validate user on the basis of UserName NOT email, dont take this type of decicsion without any discussion. # **Fixed**
17- Add Delete button in following # **Fixed**

-Manage Enquiry
-Reviews
-Submit Your Problem
-To do list
18- "Remember me " option on login page **Fixed**
19- for each list page show proper look and feel as i explained

proper bread crumb, menu should remain expand for selected menu.
e.g # **Fixed**
![image](https://user-images.githubusercontent.com/19146254/34497597-0cd8a8dc-f020-11e7-91b4-7df485eeb208.png)

**Comment by serviceproviderpk** [comment]
20- in "AllTask" and "TaskActivity" i have added two field
"EstiamtedEffort" and "ActualEffort.
When user create a task we will mension. and any activty done, hours will be added in it.

We need this feature in new simple screen,one task will be assinged to one person at a time.

it will help use to for time estimation.

**Comment by serviceproviderpk** [comment]
21-Please dont hard code things, those are written web.config

![image](https://user-images.githubusercontent.com/19146254/34506795-cc2bdbce-f051-11e7-8c3d-ab8347335712.png)

**Comment by serviceproviderpk** [comment]
22- in Mobile UI,Menu position is disturbed
![image](https://user-images.githubusercontent.com/19146254/34506956-3a19ad18-f053-11e7-95c3-24804c88f970.png)
# Fixed

**Comment by serviceproviderpk** [comment]
23- Uncomment old routes, those route shuld show relevent data or default data, but link should be not broken.
  24- hosting list should be sort by "Hosting Expiry date" near by date will be on top.

**Comment by serviceproviderpk** [comment]
25- @adilshehbaz  banner you have used on live, please give to bilal so that he can locally as well as.

**Comment by serviceproviderpk** [comment]
26-Genral Email box, any one can send email to all developers and admin to all developers.
admin can also choose user type and send email to all

**Comment by serviceproviderpk** [comment]
27- on home page 
![image](https://user-images.githubusercontent.com/19146254/34507468-f8616604-f057-11e7-8f68-c94cea2ab58f.png)
these sh;d be in one line also change color of these tick, if not possible you can find from net use gray or our color scheme for it.

   **Fixed**

**Comment by serviceproviderpk** [comment]
28-in All screen change position of button 
![image](https://user-images.githubusercontent.com/19146254/34545478-1344311a-f10f-11e7-9d5f-f1b6a6175888.png)

Heading+"Create button" and breadcrumb will be in one line.

  we can also move breadcrumb on left side and "Add Button"on right, if search button required.
   **Fixed**

**Comment by serviceproviderpk** [comment]
29-Apply session filter on "Dashboard  URLS" @adilshehbaz  can guide you.

**Comment by serviceproviderpk** [comment]
30- http://serviceprovider.pk/SubmitYourProblem
i fill the form, it says "email " already exist. does it make sense??

**Comment by serviceproviderpk** [comment]
33- Left Grid will be "To Do List" Right Grid will be " My Requests".

**Comment by serviceproviderpk** [comment]
34- In web portal " Show CRUD" of "Courses"

**Comment by serviceproviderpk** [comment]
35-show some data in recent post. you can add on live website.

**Comment by serviceproviderpk** [comment]
36- Please re-check all issues those i have request in few week. Thanks.
