### ISSUE TITLE
Feedback Sprint 2&3

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#160]

**Comment by serviceproviderpk** [comment]
1- admin must be enable/disable the  employee and student, as both account will be disabled they will be not able to use system.

as they will be enabled/disabled email will be send to them with status

sprint 1 refrence: 
![image](https://user-images.githubusercontent.com/19146254/63477830-8cf21e80-c4a0-11e9-8c69-edc7f7f993de.png)

**Comment by serviceproviderpk** [comment]
2) when admin/student/employee change his password send him email

Dear first name,

Your password is updated.

Your new Password: XnXcF

Regards,
Calgary Academy

**Comment by serviceproviderpk** [comment]
3) when Birthday notifcation is sent screen is hanged.
![image](https://user-images.githubusercontent.com/19146254/63477952-14d82880-c4a1-11e9-868a-96e7415d604f.png)

**Comment by serviceproviderpk** [comment]
4) in  System Default settings add notification setting section

Email,SMS and both, None

None= no email and sms will be send via system.
Both= email and sms will be send to both user and admin

and similarly  for  sms and emails.


according to the above settings system will send sms and emails

**Comment by serviceproviderpk** [comment]
5) use diffrent icon for menu
![image](https://user-images.githubusercontent.com/19146254/63478223-6634e780-c4a2-11e9-8653-ea6d5f3ce440.png)

**Comment by serviceproviderpk** [comment]
6) Incident Form

a) Display time in   AM and PM format please
b) Default date must be Today Date instead  of "01/01/0001"
c) Add download option for template (look and feel please follow below)

on top add Niwe Logo plz

![incident report](https://user-images.githubusercontent.com/19146254/63478501-739ea180-c4a3-11e9-9422-15ec66e609be.jpg)

**Comment by serviceproviderpk** [comment]
7) Attendance

Verify absent & Present must not be until attendance is done. do it please as we discussed!!!!

a) In front of Duration write (Hours)
e.g   Duration (Hours)
Duration box will be only active when status is  "Present"

b) Load, Reset and Cancel button sh'd be  right side of the  "Section"
mean in one Line text boxes and buttons.

c)  if i mark attandance of same day 2 time
second time it must display already marked details.

Verify abesent, verify preseent button not working properly.

Do it the way we discussed.

**Comment by serviceproviderpk** [comment]
8) on Fee

a) Auto search not working  (remove it auto search section)
![image](https://user-images.githubusercontent.com/19146254/63479055-e446bd80-c4a5-11e9-941e-93654bd29001.png)

b) this section shd be hidden until any program is selected.
![image](https://user-images.githubusercontent.com/19146254/63479148-6636e680-c4a6-11e9-88a3-9d2599c4f020.png)

c) add button to add "Deposit Account"
brach must be able to collect fee. 

when count is 0 by default we can add any account , in edit profile we can show section to add accounts as we have given in "edit Employee " screen

**Comment by serviceproviderpk** [comment]
9) Fee receipt use SGS please

![image](https://user-images.githubusercontent.com/19146254/63479408-ab0f4d00-c4a7-11e9-918e-c84610df9e72.png)

**Comment by serviceproviderpk** [comment]
10) in student section there was a menu "Student Profile"

Please re-add it now.

show student fee, Attendance detail, student leaves. on that page.

**Comment by serviceproviderpk** [comment]
11)  in student transscript create screen
show all fields those are in provided template.
will be auto filled on selecting student

**Comment by serviceproviderpk** [comment]
@adilshehbaz  as all issues fixed  ,Please assign to me write YOUR ) commnets as

1) Fixed
2) Fixed 

and so on.....

**Comment by adilshehbaz** [comment]
3. Fixed

**Comment by serviceproviderpk** [comment]
12) Manage students
![image](https://user-images.githubusercontent.com/19146254/63659029-74e40d00-c7c8-11e9-9417-f8277597f860.png)

How student can be move to "Graduated" ,  Leave of Absense and struck of ?

what is diffrence in terminated and struck off?
b) if there is no data in grid

Only add button must be selectable

**Comment by serviceproviderpk** [comment]
12) Attendance

a) I mark attendance but this is not visible in hisotry
again i tried to re-mark attedance data was not selected

but nothing is saved related to attendance.

**Comment by serviceproviderpk** [comment]
13) in all places where we are using "+"  add  link with text as well

like

"Add new student"
Add  inquiry
"Collect fee"
"Add  new program"
"Add new section"

and so on...

**Comment by serviceproviderpk** [comment]
14) Fee receipt screen must be 100% same as used in SGS Please
data must be displayed for each section.
![image](https://user-images.githubusercontent.com/19146254/63659617-c3df7180-c7cb-11e9-9061-0efdb1ec8c34.png)

receipt must display correct value of fee collections.
15) if double click on "Fee collection" list it is displaying empty form

**Comment by serviceproviderpk** [comment]
Student Transfer  be categorized properly

Show data in field set

Transfer From Programs


Transfer To Programs

as transferred  change status of existing assigned programs.


in edit student there must be some status that will display active course
completed, transfered or graudated etc.

![image](https://user-images.githubusercontent.com/19146254/63659884-4a488300-c7cd-11e9-81fd-9ff0d0c6089c.png)



@adilshehbaz 

Please compare productbacklog of spring 1,2,3,4
and today end of the day email me with status "RFR"

so that i can review it tally and email to client

your testing with focus is very important plzzz

**Comment by serviceproviderpk** [comment]
16) in Quick access add  "Reports" menu
and display their requested reports

and also add this link left menu as last menu  with name
"Reports" with no sub menu.

**Comment by serviceproviderpk** [comment]
Reprot is not same as i given.

use logo proper section and border as welll so it give same look


6) Incident Form

a) Display time in   AM and PM format please
b) Default date must be Today Date instead  of "01/01/0001"
c) Add download option for template (look and feel please follow below)

on top add Niwe Logo plz

![incident report](https://user-images.githubusercontent.com/19146254/63478501-739ea180-c4a3-11e9-9422-15ec66e609be.jpg)


Re

**Comment by serviceproviderpk** [comment]
i see report as
![image](https://user-images.githubusercontent.com/19146254/63660335-69481480-c7cf-11e9-8c0d-fa7bcd70ba2b.png)

**Comment by adilshehbaz** [comment]
1. Fixed
2. Fixed
3. Fixed
4. Fixed
5. Fixed
6. Format Changed
7. Fixed (If we mark attendance again, this update existing attendance, bcz user can update any time.)
8. Fixed
9. Fixed
10. Fixed
11. Fixed
12. Fixed moving from operations.. grid procedure remaining 
13. Fixed
14. Fixed
15. Fixed
16. Fixed

**Comment by serviceproviderpk** [comment]
@adilshehbaz  Thanks,


Please update status on google drive on productback log.
