### ISSUE TITLE
QA Feedback Aug 312019

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#178]

**Comment by SajjadAhmad111** [comment]
![image](https://user-images.githubusercontent.com/50301383/64061230-0d2b2900-cbf1-11e9-85bb-cd3467121f25.png)

1) add the question mark for active or not active student

**Comment by SajjadAhmad111** [comment]
Student Section->In student leave
Student Leave view detail section hit the back button re-directly to manage student section.

**Comment by adilshehbaz** [comment]
**1. RFR**

**Comment by SajjadAhmad111** [comment]
3) issue in transfer Program

**Comment by SajjadAhmad111** [comment]
4.Attendance section
mark the attendance of the student 'Present' but Verify in list student is not display
issue same for present and absent.

**Comment by SajjadAhmad111** [comment]
5.unable to view attendance list

**Comment by SajjadAhmad111** [comment]
![image](https://user-images.githubusercontent.com/50301383/64062912-841eec80-cc06-11e9-8211-44a2b944d361.png

collect accounts have show duplicate

**Comment by SajjadAhmad111** [comment]
![image](https://user-images.githubusercontent.com/50301383/64063007-dca2b980-cc07-11e9-8d82-7851a5657169.png)

increase the box size.series number has show in one line.change the table sequence
