### ISSUE TITLE
Management Feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#179]
0) in User manual use flow of "Manage Group Rights"

**Comment by serviceproviderpk** [comment]
2) Edit  Employee / Student  use bellow icon  on tool tip set as

"Only active student  can login"
"Only active employee can login"

![image](https://user-images.githubusercontent.com/19146254/64061209-bd4c6200-cbf0-11e9-9521-5091cb0ad803.png)


i assume it will be avaiable in fa fa icon.

**Comment by serviceproviderpk** [comment]
3)  when i click  on "Graduate" student heanding must be change instead of "Passout"
![image](https://user-images.githubusercontent.com/19146254/64061278-1072e480-cbf2-11e9-8e79-36f9e53b95bc.png)

**Comment by serviceproviderpk** [comment]
4) on Edit section   > IN prograams

display following columsn as

ID(Program Id) , Status, Name and so on....

**Comment by serviceproviderpk** [comment]
5) on student leave show student drop down in one line.
reason right side of drop down not clickable.
![image](https://user-images.githubusercontent.com/19146254/64061903-03f28a00-cbfa-11e9-8c4e-3d9106ca1086.png)

**Comment by adilshehbaz** [comment]
**1,2,3,4 RFR**

**Comment by adilshehbaz** [comment]
**5 RFR**

**Comment by serviceproviderpk** [comment]
6) add space between Label and  icon Please on all pages where you have added this label
![image](https://user-images.githubusercontent.com/19146254/64062363-d9570000-cbfe-11e9-92b5-b5d915caae6f.png)

**Comment by serviceproviderpk** [comment]
6) in edit student set Gender Default value  as "Not specified"

**Comment by adilshehbaz** [comment]
**6 RFR**

**Comment by serviceproviderpk** [comment]
7) in student grid display  "Telephone" instead of  Mobile
as have used validation on  "Telephone" field
![image](https://user-images.githubusercontent.com/19146254/64062881-f6430180-cc05-11e9-9e77-ed8e9e7db42c.png)

**Comment by serviceproviderpk** [comment]
8) Show Attedance menu after "Students" menu

**Comment by serviceproviderpk** [comment]
9) on re-mark attedance , not displaying already marked attednace.

**Comment by serviceproviderpk** [comment]
10)  Attendance History not displaying marked attendance.

use proper heading and breadcrumb label for this page
![image](https://user-images.githubusercontent.com/19146254/64063061-8d10bd80-cc08-11e9-8777-6c778f78154b.png)

**Comment by serviceproviderpk** [comment]
11) Print voucher not looking good, Please improve it.
![image](https://user-images.githubusercontent.com/19146254/64063082-ef69be00-cc08-11e9-98d3-f399cb117450.png)

**Comment by serviceproviderpk** [comment]
12) Communcation

not displaying 
a) send message to All staff
b) Send message to All students 
c) Send message to Programm wise

**Comment by serviceproviderpk** [comment]
13) on Brithday email we are sending email not sms
so use label of email instead of sms

**Comment by serviceproviderpk** [comment]
14) 
![image](https://user-images.githubusercontent.com/19146254/64063152-0bba2a80-cc0a-11e9-88b1-39b67aa8dbc3.png)
use validation for above section.

**Comment by serviceproviderpk** [comment]
15) incident 
show logo on incident report please
![image](https://user-images.githubusercontent.com/19146254/64063240-0f01e600-cc0b-11e9-97c2-16d999fbba2a.png)

**Comment by serviceproviderpk** [comment]
16) use 2 decimal places please
![image](https://user-images.githubusercontent.com/19146254/64068838-46967f80-cc57-11e9-9657-da41886a88cd.png)

**Comment by serviceproviderpk** [comment]
17) please left align data in columns

![image](https://user-images.githubusercontent.com/19146254/64068847-852c3a00-cc57-11e9-8cce-aed26592cd5c.png)

**Comment by serviceproviderpk** [comment]
18) REports

a) rename   "Sr #  " with "SN"
b) remove preview column

**Comment by serviceproviderpk** [comment]
19) Dashboard must display correct Data

![image](https://user-images.githubusercontent.com/19146254/64093816-29ef6a00-cd73-11e9-8a41-fed47172ea03.png)

**Comment by serviceproviderpk** [comment]
20) in all emails  send Only first name  instead of full name like

Dear  Ali,

instead of 

Dear Ali usman ahmed,

**Comment by serviceproviderpk** [comment]
21) in fee collection email i am getting incorrect amount.

**Comment by serviceproviderpk** [comment]
@adilshehbaz  

my above feedback all task NOT done, few task are still missing


re-verify above all

**Comment by serviceproviderpk** [comment]
22)  in  system i have 3 students as attendance marked 3 time grid showing 9 students.

![image](https://user-images.githubusercontent.com/19146254/64316147-6dddab80-cfcd-11e9-90cc-a4b58839b295.png)

sajjad also getting this issue.

**Comment by serviceproviderpk** [comment]
23) add max length in  fields in all system.

**Comment by serviceproviderpk** [comment]
24) on employee email use "," after name

![image](https://user-images.githubusercontent.com/19146254/64367697-1e7d9680-d032-11e9-9a2a-2cf2b1a7640d.png)

**Comment by serviceproviderpk** [comment]
25) in manage student set default discount as "percent"

**Comment by serviceproviderpk** [comment]
26) ON manage documents as document is upload re-set control values.

**Comment by serviceproviderpk** [comment]
27 ) Manage attednace (Program, student and section must be optional)

![image](https://user-images.githubusercontent.com/19146254/64368995-d613a800-d034-11e9-9275-748af7131d03.png)

**Comment by serviceproviderpk** [comment]
28) monthly brday reports (add new reprt)

**Comment by serviceproviderpk** [comment]
29) reduce width of  action column use some good icon with label
![image](https://user-images.githubusercontent.com/19146254/64369174-34d92180-d035-11e9-8321-a538d497e1ee.png)

**Comment by serviceproviderpk** [comment]
30) in User manual use flow of "Manage Group Rights"

**Comment by serviceproviderpk** [comment]
31)  in fee recceipt email, i am getting  "10.5" instead of "10.50"
![image](https://user-images.githubusercontent.com/19146254/64370142-44596a00-d037-11e9-9304-5e8974c01f10.png)

**Comment by serviceproviderpk** [comment]
31) show all details of Program
![image](https://user-images.githubusercontent.com/19146254/64394208-75a15c80-d06e-11e9-9feb-347dd5f5bafb.png)

Name , start date, end date, duration, same way we are showing in student register screen

**Comment by serviceproviderpk** [comment]
5) on student leave show student drop down in one line.
reason right side of drop down not clickable.
![image](https://user-images.githubusercontent.com/19146254/64061903-03f28a00-cbfa-11e9-8c4e-3d9106ca1086.png)

**Comment by serviceproviderpk** [comment]
6) Move down "Staff" menu below the "Fee" menu

**Comment by serviceproviderpk** [comment]
7) Add  "+" and Mark Attendance button in list page
![image](https://user-images.githubusercontent.com/19146254/64394634-8226b480-d070-11e9-8a7c-9f484d34286f.png)

**Comment by serviceproviderpk** [comment]
8) I tried to send message to a class
![image](https://user-images.githubusercontent.com/19146254/64394800-49d3a600-d071-11e9-9345-3fdf937cbbce.png)

that have already few students. but when i click on "submit" i see no record msg

![image](https://user-images.githubusercontent.com/19146254/64394824-640d8400-d071-11e9-9643-e81b919b3e37.png)

Please try send email with all options and confirm it.

**Comment by serviceproviderpk** [comment]
9) rename word "Class" with Program
![image](https://user-images.githubusercontent.com/19146254/64394899-be0e4980-d071-11e9-9d4d-b892c303f593.png)

**Comment by serviceproviderpk** [comment]
10) SHOW ALL details OF STUDENT  like name, id, email (as we have stanard functions)
![image](https://user-images.githubusercontent.com/19146254/64395032-3b39be80-d072-11e9-8e63-07be23501505.png)

**Comment by serviceproviderpk** [comment]
11) on edit incident report "Time" is always null on edit screen
![image](https://user-images.githubusercontent.com/19146254/64395302-31fd2180-d073-11e9-9990-cb548681df1c.png)

**Comment by serviceproviderpk** [comment]
12) in fee collection  2.99 
![image](https://user-images.githubusercontent.com/19146254/64395420-a89a1f00-d073-11e9-8d9f-87a3c506e974.png)
instead of 2.99 showing "3"
![image](https://user-images.githubusercontent.com/19146254/64395462-cff0ec00-d073-11e9-9001-197b77e53860.png)

**Comment by serviceproviderpk** [comment]
13)   Amount column and row text must be right alighn, and Particular header and row text must be left align.
![image](https://user-images.githubusercontent.com/19146254/64395605-44c42600-d074-11e9-8bf5-2b7049acc501.png)

**Comment by serviceproviderpk** [comment]
14) show fee in 2 decimal places
![image](https://user-images.githubusercontent.com/19146254/64395747-bb612380-d074-11e9-9f0d-7009d98bbc85.png)

**Comment by serviceproviderpk** [comment]
15) fee must be in 2 decimal places in email
![image](https://user-images.githubusercontent.com/19146254/64395938-68d43700-d075-11e9-81b5-32eddb72b492.png)

**Comment by serviceproviderpk** [comment]
16) rename  to "Import Students"
![image](https://user-images.githubusercontent.com/19146254/64396150-2e1ece80-d076-11e9-95d3-0a24f3421717.png)

**Comment by serviceproviderpk** [comment]
17) Forgot Password Email not Received.

change email sending function and test, it must send email.

**Comment by serviceproviderpk** [comment]
18) Create a gmail id, niweca@gmail.com
use this email id for sending email.

i can share its code with you. if required.

**Comment by serviceproviderpk** [comment]
19) in all reports left alighn row and heading text
![image](https://user-images.githubusercontent.com/19146254/64396993-1137ca80-d079-11e9-9e26-1b17a39a0698.png)

**Comment by serviceproviderpk** [comment]
-

**Comment by serviceproviderpk** [comment]
21) what is name of menu that we are using for " Loan registration form"

**Comment by serviceproviderpk** [comment]
22) Loan Installments - Alberta Student Aid will provide loan to student and payment  would be issued in installments as well.

which menu is used to manage loan that will be given to student?

**Comment by serviceproviderpk** [comment]
23) 
![image](https://user-images.githubusercontent.com/19146254/64398040-d5066900-d07c-11e9-9d13-b33f1c2a01b4.png)

increase width of the program dropdown

**Comment by serviceproviderpk** [comment]
24)   caculate percetange  on the basis of  

"Total hours of program and attedenace hours " and set value in textbox
![image](https://user-images.githubusercontent.com/19146254/64398107-11d26000-d07d-11e9-899f-b73aa597455d.png)

**Comment by serviceproviderpk** [comment]
25) 

REGISTRATION   & LOAN CHECKLIST
--
STUDENT AID PAPER APPLICATION


which menu will be use for above 2 section
write your comments plz

**Comment by serviceproviderpk** [comment]
26) Trasscript Report is missing in report section

**Comment by serviceproviderpk** [comment]
27) Create an API that will save  Inquiry, data will be as
below

![image](https://user-images.githubusercontent.com/19146254/64398396-1cd9c000-d07e-11e9-9d2d-bcb9a5fec1d6.png)

**Comment by serviceproviderpk** [comment]
28) in User manuall document please use some headin glike

1) Manage Students
  1.1 Inquiry
1.2  Import Student
etc and so on...

**Comment by adilshehbaz** [comment]
21. Loan Registration Form
22. Need to create

**Comment by adilshehbaz** [comment]
26. Transcript Report Mean??

**Comment by adilshehbaz** [comment]
27. Where to create API in web project or in webAPI project

**Comment by adilshehbaz** [comment]
All other issues are fixed.

**Comment by serviceproviderpk** [comment]
1) Open PDF document in new tab instead of show downloading.

**Comment by serviceproviderpk** [comment]
-

**Comment by serviceproviderpk** [comment]
3) Change color of this button, Please use some css, it must effect on all places.
i re-produced this issue  in Incoginato windows
![image](https://user-images.githubusercontent.com/19146254/64468038-ead96400-d138-11e9-9813-44a4bc4e2b0c.png)

**Comment by serviceproviderpk** [comment]
4) Default value must be "Select"

**Comment by serviceproviderpk** [comment]
5) show hours column
![image](https://user-images.githubusercontent.com/19146254/64468101-e06b9a00-d139-11e9-88d2-503a16795bbe.png)

**Comment by serviceproviderpk** [comment]
6) in student drop down show standard data like (first middle name last name, id, and email etc)

**Comment by serviceproviderpk** [comment]
7) on fee collection i given Receipt Discount as  "14.75" but it was displayed  as 
"$ 15" in PDF report

and in email display value of  "Receipt Discount "

![image](https://user-images.githubusercontent.com/19146254/64468233-7fdd5c80-d13b-11e9-9bc4-4588603cc4cb.png)

**Comment by serviceproviderpk** [comment]
8) on student leave show student drop down in one line.
reason right side of drop down not clickable.
![image](https://user-images.githubusercontent.com/19146254/64061903-03f28a00-cbfa-11e9-8c4e-3d9106ca1086.png)

**Comment by serviceproviderpk** [comment]
9) 
![image](https://user-images.githubusercontent.com/19146254/64468288-583ac400-d13c-11e9-80df-27f85a54e9f1.png)

a) change message "Your request is send to sms gateway."
to "Your request is successfully processed."

b) show email log please

**Comment by serviceproviderpk** [comment]
10) change color according to theme
![image](https://user-images.githubusercontent.com/19146254/64468329-f7f85200-d13c-11e9-87be-9979bb7e6c2b.png)

**Comment by serviceproviderpk** [comment]
11) on edit incident report "Time" is always null on edit screen
![image](https://user-images.githubusercontent.com/19146254/64395302-31fd2180-d073-11e9-9990-cb548681df1c.png)

**Comment by serviceproviderpk** [comment]
12) in fee collection  2.99 
![image](https://user-images.githubusercontent.com/19146254/64395420-a89a1f00-d073-11e9-8d9f-87a3c506e974.png)
instead of 2.99 showing "3"
![image](https://user-images.githubusercontent.com/19146254/64395462-cff0ec00-d073-11e9-9001-197b77e53860.png)

**Comment by serviceproviderpk** [comment]
13)  must display 2 decimal places
![image](https://user-images.githubusercontent.com/19146254/64468383-b025fa80-d13d-11e9-8c1a-86ee82c00a8f.png)

**Comment by serviceproviderpk** [comment]
14) Forget Password not sending email

**Comment by serviceproviderpk** [comment]
15) Create a gmail id, niweca@gmail.com
use this email id for sending email.

i can share its code with you. if required.

**Comment by serviceproviderpk** [comment]
16) When student and employee account is created create random password as number.
instead of random string.
in BusinessManager we have 2 different function for it.

**Comment by serviceproviderpk** [comment]
17) 
a) ![image](https://user-images.githubusercontent.com/19146254/64472745-85a76200-d17c-11e9-91cc-cfced46670c7.png)
show 2 decimal places
b) 
![image](https://user-images.githubusercontent.com/19146254/64472759-b4bdd380-d17c-11e9-9563-4283703817cd.png)

**Comment by serviceproviderpk** [comment]
17)
