### ISSUE TITLE
Sajjad Feedback

### ISSUE THREAD

**Issue by SajjadAhmad111** [serviceproviderpk/sp.pk#187]
Successfully spelling is incorrect in notification when we restore student from graduated to active student

![image](https://user-images.githubusercontent.com/50301383/64234633-31984580-cf10-11e9-8d46-a16a247e1297.png)

**Comment by SajjadAhmad111** [comment]
I have total Student four.When i marked their attendance first  time they are showing four and when i marked attendance next time  these four student become 8.Mean they become double every time  

![image](https://user-images.githubusercontent.com/50301383/64236676-568eb780-cf14-11e9-9069-1343696202b2.png)

**Comment by SajjadAhmad111** [comment]
Validation message should be show below the text field of date of birth

![image](https://user-images.githubusercontent.com/50301383/64237078-14b24100-cf15-11e9-89e6-b4204d85ec8c.png)

**Comment by SajjadAhmad111** [comment]
When i Create a staff i have to face this error many time.
![image](https://user-images.githubusercontent.com/50301383/64237486-e1bc7d00-cf15-11e9-8452-286ff3fb0051.png)

**Comment by SajjadAhmad111** [comment]
when i collect fee of any student i have to face this error.

![image](https://user-images.githubusercontent.com/50301383/64244187-074f8380-cf22-11e9-9bb7-2d67d98f1e93.png)

**Comment by SajjadAhmad111** [comment]
In fee collect searching is not working

![image](https://user-images.githubusercontent.com/50301383/64245687-d1f86500-cf24-11e9-802a-00e456afc609.png)

**Comment by SajjadAhmad111** [comment]
In student First aid save button is not working

![image](https://user-images.githubusercontent.com/50301383/64250021-7fbc4180-cf2e-11e9-87d3-e542d9d4e830.png)

**Comment by adilshehbaz** [comment]
**All Issues Fixed**

**Comment by SajjadAhmad111** [comment]
I have Create an inquiry when i download it then i have face this error instead of download this file 
![image](https://user-images.githubusercontent.com/50301383/64315913-cfe9e100-cfcc-11e9-9c99-a326828e41d1.png)

**Comment by SajjadAhmad111** [comment]
![image](https://user-images.githubusercontent.com/50301383/64317336-d2e6d080-cfd0-11e9-9fb4-f9779fbd53e0.png)

**Comment by SajjadAhmad111** [comment]
in Manage import student there should be maximum limit on province 
![image](https://user-images.githubusercontent.com/50301383/64317489-4852a100-cfd1-11e9-8013-09e1a39770c4.png)

**Comment by SajjadAhmad111** [comment]
Studdent incident report is no looking well
![image](https://user-images.githubusercontent.com/50301383/64318768-4b02c580-cfd4-11e9-9aff-c8284ddeeec6.png)
