### ISSUE TITLE
5 september

### ISSUE THREAD

**Issue by SajjadAhmad111** [serviceproviderpk/sp.pk#189]

**Comment by SajjadAhmad111** [comment]
Show the breadcrumb on Section Screen

**Comment by SajjadAhmad111** [comment]
On Dashboard and Communication system icon has been disappear when when we expand any module

**Comment by SajjadAhmad111** [comment]
In Secession Screen give space between icon and add secession
 
![image](https://user-images.githubusercontent.com/50301383/64336644-ec9b0e80-cff6-11e9-9e25-3c7478b7e5ea.png)

**Comment by SajjadAhmad111** [comment]
In Manage Question Screen also give space between icon and add question

![image](https://user-images.githubusercontent.com/50301383/64336780-3d126c00-cff7-11e9-832d-b01ed2e44733.png)

**Comment by SajjadAhmad111** [comment]
Add space between icon and add Reminder on Reminder Screen

![image](https://user-images.githubusercontent.com/50301383/64338429-28d06e00-cffb-11e9-94e2-e4f17f113fd1.png)

**Comment by SajjadAhmad111** [comment]
In Send Birth Day Message  Screen there Should be notification instead of message 

![image](https://user-images.githubusercontent.com/50301383/64338653-bf9d2a80-cffb-11e9-8f55-0f063bdc5164.png)

**Comment by adilshehbaz** [comment]
**RFR**

**Comment by SajjadAhmad111** [comment]
Has been fixed
