### ISSUE TITLE
omer feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#195]
-

**Comment by serviceproviderpk** [comment]
1) Edit student on download button  as "Mouse hover" show hand icon(cursor)
![image](https://user-images.githubusercontent.com/19146254/64747248-e392cb80-d527-11e9-8e7b-935e51f383da.png)

**Comment by serviceproviderpk** [comment]
2) in create inquuiry download button not working also use handicon on mouse hover

**Comment by serviceproviderpk** [comment]
3)  in Edit Inquiry download document button not working aslo handicon on mouse hover please

**Comment by serviceproviderpk** [comment]
4) i want to create a "Program" from November  2019 to December  2019
Start date can no be choosed as november.

if you are getting issue in client side, you can use backend this check.

this is very confusion, user must increase end date to increase the start date.

by default you can set start date and end date null if it is usefull for you.

**Comment by serviceproviderpk** [comment]
5) when we create / edit student we have diffrent fileds for first name, middle name and last name.

![image](https://user-images.githubusercontent.com/19146254/64758514-32535c00-d54e-11e9-87d1-5e77a0bc8411.png)


but when student login we are showing only one field

show diffrent fields for it.

![image](https://user-images.githubusercontent.com/19146254/64758551-4dbe6700-d54e-11e9-91f2-19d3921a22e9.png)

for student you can create diffrent "Action"
like EditStudentProfile

**Comment by serviceproviderpk** [comment]
6 ) when  admin edit student profile

send email to student same as we we on new student creation

like

Dear Ali,

Your account details is

Email: your@afsds.com
Password: sadfasdf

Thanks,

7) when admin edit staff also send email to staff

**Comment by serviceproviderpk** [comment]
8) Student leave
![image](https://user-images.githubusercontent.com/19146254/64759490-aee73a00-d550-11e9-8c41-0446ccdf3191.png)

a) When admin/staff "Add Student leave"
firt we will choose student
then  we will select Program of student
Then FromDate will be today date and  To date will be end date of the Program.

b) When student will apply for  leave he will chooose his  program and so on....

**Comment by serviceproviderpk** [comment]
9) "Send Genral Email" Spellings are wrong.
- Generatel notifications -> not all programs and sections being loading.

try to send email using all options.

**Comment by serviceproviderpk** [comment]
10) Delete student then test below

IF fee of a program has been paid and other formalities, i deleted program from students by editing it, it did deleted that program.

now again i try to update that program or change program in student edit
it does not allow me to do that and all sections,program are empty see screenshot.

all the documents i uploaded are also gone. (is this right?)
let me give you example: i uploaded everything and i came to know program i selected was wrong, i delete it and update it again, then i will have to upload it again big effort (in that case either you should give error or warning if you do this will happen something like that to notify user in a proper way)

**Comment by serviceproviderpk** [comment]
11) Edit Student > Program

![image](https://user-images.githubusercontent.com/19146254/64760975-66ca1680-d554-11e9-9f3c-e91637be0c19.png)

**Comment by serviceproviderpk** [comment]
after fixing above issues, Please test all system features.  by entering data.


we wish to deliver Quality of work!!!!!

**Comment by serviceproviderpk** [comment]
14) branch that we have shared with Umer

change session to  "Winter 2019" and "Summer 2019"

**Comment by serviceproviderpk** [comment]
15)  on Daily Attendance >  attedance add min date check 

mininum date must me today.

**Comment by serviceproviderpk** [comment]
16) in student profile > Attendace secion show Hours column
and  in footer show number of hours he completed 
![image](https://user-images.githubusercontent.com/19146254/64845619-1621ee80-d624-11e9-858f-8ea4349b365d.png)

**Comment by serviceproviderpk** [comment]
17) back button sh;d not reload page
![image](https://user-images.githubusercontent.com/19146254/64846014-f8a15480-d624-11e9-8002-425df1ed2e53.png)

**Comment by serviceproviderpk** [comment]
18) on fee collection, if i choose "Select"  instead of program it is giving exception.
![image](https://user-images.githubusercontent.com/19146254/64846265-ae6ca300-d625-11e9-9492-6aabb3b78098.png)

**Comment by serviceproviderpk** [comment]
19) if there is no delete buton show Transfer button
with some good icon

![image](https://user-images.githubusercontent.com/19146254/64846993-62baf900-d627-11e9-8293-6225e4076b4a.png)

**Comment by serviceproviderpk** [comment]
20) @TahirHussai  explain below issue to adil

Test at Niwe on live
I have open Inquiry grid i have no record
 i have select download and edit cursor move i think we need to display message
I have Regiger one student and collect fee after fee collection i have in active that class in which class student is registered
then i have collect fee In Active class is available in fee collection, same Enrolment
Student Transfer Issue is still remaining

**Comment by serviceproviderpk** [comment]
@adilshehbaz  verify on live, and write fix infront of each task

**Comment by serviceproviderpk** [comment]
[nathan03666228.docx](https://github.com/serviceproviderpk/sp.pk/files/3612265/nathan03666228.docx)

client feedback with comments

**Comment by serviceproviderpk** [comment]
1) Forget Password showing old logo
http://niwe.schoolmanagementsoftware.pk/Account/ForgetPassword

![image](https://user-images.githubusercontent.com/19146254/64918500-692caa80-d7b8-11e9-8db1-235b837f14ca.png)

**Comment by serviceproviderpk** [comment]
2) i changed the sesssion students always remaing same in student list

**Comment by serviceproviderpk** [comment]
3) Staff profile also display password in email
![image](https://user-images.githubusercontent.com/19146254/64919341-1c020600-d7c3-11e9-8a7b-cf21be16a04f.png)

**Comment by serviceproviderpk** [comment]
4- Communiction > on all staff emails
![image](https://user-images.githubusercontent.com/19146254/64919452-47392500-d7c4-11e9-9c59-b2cdf279c602.png)

**Comment by serviceproviderpk** [comment]
5) mark attendace , delete button must be disable.

**Comment by serviceproviderpk** [comment]
1)  Attednace can be mark with in duration of the Program
we need change sequence of  controls
Program,section,Datepicker ( date can be only selected with duration of the program)

**Comment by serviceproviderpk** [comment]
2) Save button font color must be white in students inquiry section right now its black, before it was white, which is more visible. its everywhere "add","save" buttons font color must be white not black. (NOT FIXED)

**Comment by serviceproviderpk** [comment]
3) programs: I can select start date and end data in past months which is
wrong, it must be selected from today or future dates. (NOT FIXED:please restrict
to date to be selected before from date)

**Comment by serviceproviderpk** [comment]
4) same dates issue with sections. (NOT FIXED:please restrict
to date to be selected before from date)

**Comment by serviceproviderpk** [comment]
5) Program, how to edit a fee now i dont see any option?
we need to implement it. as it was shown to umer, now it doesnot make sense, we are hidding.
and will say umer, fee is not editable of a program.

**Comment by serviceproviderpk** [comment]
6) Leave > Email format content is ok now but still mistake:

dear admin, (i am not admin) (if email goes to admin, then this title should be same otherwise

Dear [name]

You have applied for leave.

Status: Pending

also move status:pending to next line.

**Comment by serviceproviderpk** [comment]
7) Edit student
Scenario: I changed student profile from admin account + logging into student portal (both times emails on edit profile not generated)

**Comment by serviceproviderpk** [comment]
8) in add/edit student add this field

"ID Number" and in inquiry  it will be optional

**Comment by serviceproviderpk** [comment]
9)  auto complete for Country, city and provnice, table i provided.

**Comment by serviceproviderpk** [comment]
10- please double check Omer feedback in trello

**Comment by adilshehbaz** [comment]
6) Please Provide Format of Leave for Email

**Comment by serviceproviderpk** [comment]
7) Clear attendance date by default.

**Comment by serviceproviderpk** [comment]
8) as leave is approved, remove  "Hide" or disabled "Save" button

**Comment by serviceproviderpk** [comment]
9) ID Number Field in Student Inquiry Form

**Comment by serviceproviderpk** [comment]
10) cache for country,provnice,city, it will save time to db again and again.
