### ISSUE TITLE
Client Feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#196]

**Comment by serviceproviderpk** [comment]
1) Student: Inquire student should be like a crm where we can track leads, also formally like hubspot or link to all our email inbox to gather new leads, this will allow us to track all our leads in one place instead of taking the time to add a inquiry one at a time

Solution:
a) API will save data in inquiry.  (API that will display active programs,  api that will save inquiry
b) also add one entry in mail-chimp account.
as

**Comment by serviceproviderpk** [comment]
2) Reminder of how many hours till graduation plus reminders at 80% students are always concerned by their hours.
- no reply email congralutions you are almost completed your graduations and send how many hours they are left with.

**Comment by serviceproviderpk** [comment]
Notification of changes from the calendar to all staff
Solution:
Show system activities. (draw and show)

**Comment by serviceproviderpk** [comment]
3) Sample Email

Once student hits 60% of their tuition:

Hi %Name%
This is a friendly reminder that you should have paid 100 % of your tuition by now.

If you have any questions or concerns please contact accounting@niwe.ca.

**Comment by serviceproviderpk** [comment]
@adilshehbaz  below is feedback. feel free to discuss.
[Feedback_confirmations.docx](https://github.com/serviceproviderpk/sp.pk/files/3617982/Feedback_confirmations.docx)

**Comment by serviceproviderpk** [comment]
Confirmation about Feedback

1) Attendance: Drop down menu of sick, excused, and unexcused absence?
- List of student names, put reason with dropdown.
Under attendance there will be a drop down menu with the following (Sick, Excused, absent, and unexcused absence with the option to attach a doctor’s note to their file)
Comments: 
We are using below screen to mark attendance (at a same time we can mark attendance for all students) 


a)	If student is present, we are showing text box to enter hours.
Yes
b)	You mean to say when student is absent, we need to display a drop down with following option (Sick, Excused, absent, Un-excused) ?
Yes that is correct 
c)	We must remove leave option form this section. 
Yes I just want absent and present with the dropdown menu with (Sick, Excused, absent, Un-excused)?
d)	Duration of each program is fixed hours daily or it varies from day to day?
Yes, it is fixed 7 hours however students will typically show up a few minutes late. Also the evening class is 5 hours daily but 7 hours on Saturday. 
2)  Reminder of how many hours till graduation plus reminders at 80% students are always concerned by their hours.
Comments:
We will create a page, from that page user will choose a program and click  on “Submit “button.
Reminder will be send to the student who has completed 80% of the program.
Please provide reminder format.
Sample Email
Once student hits 80% of their tuition:
Congratulations %Name%
you have officially reached 80% of your program, have you Considered RSVP for your your Grad Yet? 
If not, please click here (Is it possible to add a link at a later date?)
If you wish to purchase a ticket for a guest please click here.
If you have any questions or concerns please contact admin@niwe.ca.

**Comment by serviceproviderpk** [comment]
2) Calendar – Please add to CRM
- One for the staff and (program start dates, module start dates)
- for students (test days, exam days)

Comments:
We will create a page with following fields (title, description, start date and end date, start time, end time)
this section will be visible for all students and staff as well just for updates.

**Comment by adilshehbaz** [comment]
All issues fixed..

Image issue on attendance.

Send Reminder Button issue just

**Comment by serviceproviderpk** [comment]
1- 
![image](https://user-images.githubusercontent.com/19146254/65219156-722bbd80-dad1-11e9-99e4-1ad9943c9bc6.png)
show reason and button to download doctor perception.

**Comment by serviceproviderpk** [comment]
2) Set default value for "Reason" drop down our use word "Select"
increase width of file upload control
use some reasonable width for each column of table
![image](https://user-images.githubusercontent.com/19146254/65219339-ccc51980-dad1-11e9-8e03-5b5adf00c0d2.png)

**Comment by serviceproviderpk** [comment]
3 ) Add colmun of  reason and file downloand 

![image](https://user-images.githubusercontent.com/19146254/65219482-14e43c00-dad2-11e9-8477-a390511fa21f.png)

4) in all all project 

Can we also Please make a change from "Calgary Academy to NIWE Academy

**Comment by serviceproviderpk** [comment]
4) Please read all feedback and re-test carefully, not request to some resource, do yourslef please.

**Comment by serviceproviderpk** [comment]
5- Please fix Umer feedback that he shared. that is possible what he said.
we need to fix it. if something is difficult. send message me on group. i will assist you.
