### ISSUE TITLE
Mubashir

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#2]

**Comment by mubashir633** [comment]
Yesterday i did worked on Consultancy request and it is functional. 
Today i start working on consultancy **Assign** did half of its work and after the i shifted on Quotation request create its partial view and worked on it. 
At the end i fixed issues of bread crum according to the page.

**Comment by mubashir633** [comment]
Look and feel of Three Requests (Done)
Edit Profile (Done)
Change password (Done)
Logout (Done)
Is Deleted add in every DTO (Done)
