### ISSUE TITLE
Client Feedback 27 2019

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#200]
ref: https://demos.telerik.com/aspnet-mvc/scheduler

**Comment by adilshehbaz** [comment]
[Fixed_CRM_Updated_Changes_Sept_27th_2019.docx](https://github.com/serviceproviderpk/sp.pk/files/3664200/Fixed_CRM_Updated_Changes_Sept_27th_2019.docx)

**Comment by serviceproviderpk** [comment]
@adilshehbaz  some details from client about pending questions
[Question_about_feedback_Sep__28_2019.docx](https://github.com/serviceproviderpk/sp.pk/files/3664972/Question_about_feedback_Sep__28_2019.docx)

**Comment by serviceproviderpk** [comment]
in Manage document section we will add a dropdown "For Staff,For Students, Both"

so document will be visible accoredingly.

**Comment by serviceproviderpk** [comment]
1) i dont see any grid to edit existing events
2)  when any event is click show detail of events in alert box or in some div etc

**Comment by serviceproviderpk** [comment]
3) please not forget to update date time on login page
© Copyright 2019 NIWE Academy **(Updated on 19/09/2019 06:25 PM).** All Right Reserved.

**Comment by serviceproviderpk** [comment]
4) School Management  Software key words from all over the project and meta tags of login/forget/and dashobard page

**Comment by serviceproviderpk** [comment]
@adilshehbaz  let me know as all feedback verified on server. http://niwebeta.schoolmanagementsoftware.pk/
so that i can test it.

**Comment by serviceproviderpk** [comment]
5) in Student Inquiry

rename  "Maling Address-Api #" Address 1
and  "Street" Address 2

**Comment by serviceproviderpk** [comment]
6) 3.	Student Enrollment 
a.	Unit Number (remove validation from this field, it will be optional)

**Comment by serviceproviderpk** [comment]
7) in Apply  leave  (From date must be less than today)

**Comment by serviceproviderpk** [comment]
8) in Manage documents , display SNO as first column of the grid. we have already this field in this table.

**Comment by serviceproviderpk** [comment]
9.	Communication System 
a.	 be able to send notification to all staff or all students (add this option.) please

**Comment by serviceproviderpk** [comment]
10) Transcript 
a.	Remove Russell Langley off the template and write school official.

![image](https://user-images.githubusercontent.com/19146254/65815688-511f4700-e20c-11e9-891c-3336bc37c490.png)

**Comment by serviceproviderpk** [comment]
11) 	Request Order 

Please  add "Rights" in both domains,  or give me script, i will addd it.

**Comment by serviceproviderpk** [comment]
12) i was logged in as student and click on "Attendance" i see below error
![image](https://user-images.githubusercontent.com/19146254/65815741-e4f11300-e20c-11e9-9336-59825395ec22.png)

**Comment by serviceproviderpk** [comment]
13) Events ,when user click on events, Please show detail of event in alert as below
![image](https://user-images.githubusercontent.com/19146254/65815778-38636100-e20d-11e9-84a1-b82ca2594325.png)

**Comment by serviceproviderpk** [comment]
14) in student dashboard show "Documents" menu.  and display  document which are  created for students.

**Comment by serviceproviderpk** [comment]
15)
-	Notification Bar or icon 

(when fee is collected, or leave is approved, or birthday notifcaiton send, we can dipslay here.)

![image](https://user-images.githubusercontent.com/19146254/65815861-069eca00-e20e-11e9-8758-a164f6807e8b.png)

**Comment by serviceproviderpk** [comment]
Student "Middle" name must be optional. in add/edit student and Inquiry page.

**Comment by adilshehbaz** [comment]
1 Fixed
3 Done
4 Done
5 Done
6 Done
7 Done
8 Done
9 Done
10 Done
11 Done
14 Done

**Comment by adilshehbaz** [comment]
15. This is reminder to creater any reminder for yourself from date to date etc..

**Comment by adilshehbaz** [comment]
[Fixed_CRM_Updated_Changes_Sept_29.docx](https://github.com/serviceproviderpk/sp.pk/files/3667436/Fixed_CRM_Updated_Changes_Sept_29.docx)

**Comment by serviceproviderpk** [comment]
20- from this page  http://niwebeta.schoolmanagementsoftware.pk/ManageUpcomingEvents/EventsCalender

a) rename "Manage Upcoming Events" to " Events"
b)  rename "Add, Update and Search" to "Browse and search events"
c) if click on any event show details of events in alert box as explined
d) in System setttings add new  menu "Manage Events"

**Comment by serviceproviderpk** [comment]
21) on servcie request i am getting error

![image](https://user-images.githubusercontent.com/19146254/65854335-d07c5a00-e375-11e9-9cc9-469cdd7b6b74.png)

**Comment by serviceproviderpk** [comment]
22) send sql script  to add "Available system rights" for events and service requests

**Comment by serviceproviderpk** [comment]
23)  in  submit reqeust  below section is missing. Please make  sure give it same look and use same label names

![image](https://user-images.githubusercontent.com/19146254/65908625-3e5d6b80-e3e0-11e9-8ad8-cfcabb62bb4d.png)

**Comment by serviceproviderpk** [comment]
24) use validation on "create /edit  Events"
todate must be greater than from date.

**Comment by serviceproviderpk** [comment]
25) ASN will be text box  just kind of NIC,,  and add this on right side of "ID"Number
![image](https://user-images.githubusercontent.com/19146254/65909670-8bdad800-e3e2-11e9-9293-a84cb19dc694.png)

**Comment by serviceproviderpk** [comment]
26) in search event screen give this type of look 
in drop down use  (Active Events,Past Events)
Active Events=Future events
Past Events=Events which are password
![image](https://user-images.githubusercontent.com/19146254/65910187-a9f50800-e3e3-11e9-8925-c36508db5038.png)

**Comment by serviceproviderpk** [comment]
27 )  Add /Edit program

a) rename "Duration (Hours) "  to	"# of hours total per course"
b) rename "Hours Per Day (Hours)" to  "#Hours per day"

**Comment by serviceproviderpk** [comment]
28) if student  login

![image](https://user-images.githubusercontent.com/19146254/65911792-95fed580-e3e6-11e9-9e78-31e23c14076c.png)

if user click on "View" open in new tab.

**Comment by serviceproviderpk** [comment]
30) missing
![image](https://user-images.githubusercontent.com/19146254/65912023-f68e1280-e3e6-11e9-928d-dcf98f4bafa7.png)

**Comment by serviceproviderpk** [comment]
31) change "School Management Software" to "Niwe Academy"

![image](https://user-images.githubusercontent.com/19146254/65926752-41705000-e410-11e9-9bc4-80fbc17e4155.png)

**Comment by serviceproviderpk** [comment]
32) "Manage Enrollment Contract" =>  remove * and validation from both

![image](https://user-images.githubusercontent.com/19146254/65926860-b2176c80-e410-11e9-8c41-002a3f16483a.png)

**Comment by serviceproviderpk** [comment]
33) Manage documents  -> Also display version number after "SNO"

**Comment by serviceproviderpk** [comment]
34)  Transcript 
a.	Remove "Russell Langley"  on other section will remain as it is. (you have removed all section)

![image](https://user-images.githubusercontent.com/19146254/65815688-511f4700-e20c-11e9-891c-3336bc37c490.png)

**Comment by serviceproviderpk** [comment]
35)  in Student Dashobard  "use some diffrent "fa fa icon.
![image](https://user-images.githubusercontent.com/19146254/65927210-30284300-e412-11e9-9ae0-d45f2469bc4e.png)

**Comment by serviceproviderpk** [comment]
36) as we have already discussed and approved by client. if course is 60% or 80% completed.
we will send fee deposit reminder to all students.

> "under the fee -> once a student hits 60% of the program they should get a reminder email"

where is the page that will send that notification??

in "Fee" menu we can add new menu "Fee Reminder" or whatever is your suggestion comments here plz

**Comment by adilshehbaz** [comment]
c) also show "Timeline"view and other view option 
**already shoing month week and day timeline**
![image](https://user-images.githubusercontent.com/28675602/65994851-b6459780-e4ad-11e9-96da-02b8a90e80ee.png)

**Comment by adilshehbaz** [comment]
15. Reminder notification

**Need Discussion**

**Comment by adilshehbaz** [comment]
**All other task fixed**

**Comment by serviceproviderpk** [comment]
16) 
![image](https://user-images.githubusercontent.com/19146254/66013154-8f09bd00-e4e3-11e9-82da-9e10fbe84b6f.png)

**Comment by serviceproviderpk** [comment]
17) Please download latest database from this link
and see why newly added user rights not working for existing branches, although i have assigned  them.
https://transfernow.net/57cii947e541

**Comment by serviceproviderpk** [comment]
18)  when student login, in his dashobard  add 	Notification Bar or icon 

(when fee is collected, or leave is approved, or birthday notifcaiton send, we can dipslay here.)

![image](https://user-images.githubusercontent.com/19146254/65815861-069eca00-e20e-11e9-8758-a164f6807e8b.png)

**Comment by serviceproviderpk** [comment]
NOT Fixed

19)  in  submit reqeust  below section is missing. Please make  sure give it same look and use same label names

![image](https://user-images.githubusercontent.com/19146254/65908625-3e5d6b80-e3e0-11e9-8ad8-cfcabb62bb4d.png)

**Comment by serviceproviderpk** [comment]
20) give some good look to notifications.

also add delete option in notificaitns.

admin, staff and student both must able abel to delete their own notifications.

**Comment by serviceproviderpk** [comment]
21) modify it, as i explained.
![image](https://user-images.githubusercontent.com/19146254/66026165-9f389100-e511-11e9-8968-41d6528a3dd3.png)

**Comment by serviceproviderpk** [comment]
1) i created event as below , if click on "Events" 

Please remove word "Select " from drop down.

![image](https://user-images.githubusercontent.com/19146254/66076579-924e8880-e577-11e9-9391-64bb79b10585.png)
if click on  "Events" to see event in calender,  screen was hanged as below

![image](https://user-images.githubusercontent.com/19146254/66076662-bf02a000-e577-11e9-87da-ef41a323ffa0.png)

**Comment by serviceproviderpk** [comment]
2) Student Login > 

a) SNO is same for all
![image](https://user-images.githubusercontent.com/19146254/66077227-fcb3f880-e578-11e9-9ba4-705ab7fe1015.png)
b ) student is registerd in 2 programs, attednace was marked for 2 program.
but data is displayed for only 1 program.

**Comment by serviceproviderpk** [comment]
3) Manage document, if i save version as "1.1" it was not saved. i suggest make it string instead of number.

**Comment by serviceproviderpk** [comment]
4)  Transcript 
a.	Remove "Russell Langley"  on other section will remain as it is. (you have removed all section)

![image](https://user-images.githubusercontent.com/19146254/65815688-511f4700-e20c-11e9-891c-3336bc37c490.png)

**Comment by serviceproviderpk** [comment]
5) Sample Email  ( you are sending  some other email, student completed 62%" but notification was not send to that student)

Once student hits 60% of their tuition:

Hi %Name%,

This is a friendly reminder that you should have paid 100 % of your tuition by now.

If you have any questions or concerns please contact accounting@niwe.ca.

Thanks,
Niwe Academy

**Comment by serviceproviderpk** [comment]
6) need to test api

**Comment by adilshehbaz** [comment]
All issues fixed

**Comment by adilshehbaz** [comment]
I am stuck in this issue, when we click on send email, not found error,,
i tried every thing  but fail, can you please take a look at this?
![image](https://user-images.githubusercontent.com/28675602/66083952-eca31580-e586-11e9-90b2-8f9bb902abea.png)

**Comment by serviceproviderpk** [comment]
1)  Event Calender is still hanged. login email service@serviceprovider.pk
passowrd admin123
click on "Events" screen is hanged.

![image](https://user-images.githubusercontent.com/19146254/66092682-4f57d980-e5a6-11e9-80ee-bec723c5a6cb.png)

**Comment by serviceproviderpk** [comment]
2) Save Fee reminder alert in "Student" notifications
![image](https://user-images.githubusercontent.com/19146254/66093085-30f2dd80-e5a8-11e9-803a-1acc65721f08.png)

**Comment by serviceproviderpk** [comment]
3)  Rename  "Send Reminder" to "Fee Reminder"

![image](https://user-images.githubusercontent.com/19146254/66093139-6d263e00-e5a8-11e9-96ef-5a723e78aef3.png)

**Comment by serviceproviderpk** [comment]
4)  Please show/ hide this menu from user rights. if already what is name and rights id of this?
 i want to hide it admin rights, we will give this menu to super admin.

![image](https://user-images.githubusercontent.com/19146254/66094584-ee340400-e5ad-11e9-9d92-3e27e5040b56.png)

**Comment by adilshehbaz** [comment]
1. Its working fine Event Screen i check many times,
please refresh cache 

![image](https://user-images.githubusercontent.com/28675602/66114994-610ea080-e5e9-11e9-9ab8-43aab0710625.png)

**Comment by adilshehbaz** [comment]
3. We can't change general to fee
because we are sendgin reminders for attendance and fee both , their is reminder type

**Comment by adilshehbaz** [comment]
4. We are showing manage rights to only branch, so that's why no need to add in user rights

**Comment by adilshehbaz** [comment]
Manage Group Rights Menu user rights Detail

ID=92
Name: GROUPRIGHTS
