### ISSUE TITLE
Designer Task

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#201]
1) ![image](https://user-images.githubusercontent.com/19146254/65853675-b6da1300-e373-11e9-93d9-5655d998dbf1.png)

2) 
![SMS1](https://user-images.githubusercontent.com/19146254/65937248-beafbb00-e438-11e9-897b-3034768c91c8.jpg)

3) 
![sw2](https://user-images.githubusercontent.com/19146254/65937279-d8e99900-e438-11e9-9254-6a6e0b5f23b6.jpg)

**Comment by SarmadTehami** [comment]
1)
![software school](https://user-images.githubusercontent.com/55796705/65853997-b2622a00-e374-11e9-9ffc-1c504fa9c34e.jpg)

**Comment by SarmadTehami** [comment]
2)
![NCS2](https://user-images.githubusercontent.com/55796705/65854069-f9501f80-e374-11e9-8b5c-62e6cbb86c70.jpg)

**Comment by SarmadTehami** [comment]
3)
![education 2](https://user-images.githubusercontent.com/55796705/65854088-0c62ef80-e375-11e9-8a36-e6498256375b.jpg)

**Comment by SarmadTehami** [comment]
4)
![education banner 3](https://user-images.githubusercontent.com/55796705/65854123-2270b000-e375-11e9-874f-0bf4cb44adcc.jpg)

**Comment by SarmadTehami** [comment]
5)
![web sale](https://user-images.githubusercontent.com/55796705/65854158-4207d880-e375-11e9-9d13-9e3da484f5d3.jpg)

**Comment by SarmadTehami** [comment]
6)
![web sale jpg](https://user-images.githubusercontent.com/55796705/65854186-5b108980-e375-11e9-8073-f91c8cde32a8.jpg)

**Comment by SarmadTehami** [comment]
7)
![aaa](https://user-images.githubusercontent.com/55796705/65854219-754a6780-e375-11e9-92ce-7240da3896e9.jpg)

**Comment by SarmadTehami** [comment]
8)
![sunday](https://user-images.githubusercontent.com/55796705/65854258-9317cc80-e375-11e9-83fb-88b1832b6fe6.jpg)

**Comment by SarmadTehami** [comment]
9)
![School managment 3](https://user-images.githubusercontent.com/55796705/65854306-bb9fc680-e375-11e9-9439-159eab0c2afe.jpg)
![School managment 1](https://user-images.githubusercontent.com/55796705/65854307-bb9fc680-e375-11e9-8dc0-4e00e51efdf2.jpg)
![School managment 2](https://user-images.githubusercontent.com/55796705/65854308-bc385d00-e375-11e9-9350-f0539ea3f90d.jpg)

**Comment by SarmadTehami** [comment]
10)
![10](https://user-images.githubusercontent.com/55796705/65949753-39d39a00-e456-11e9-8bdd-88d7e8f73c97.jpg)

**Comment by SarmadTehami** [comment]
11)
![11](https://user-images.githubusercontent.com/55796705/65962321-d3f50b80-e471-11e9-98a0-b2846a512b2c.jpg)

**Comment by SarmadTehami** [comment]
12)
![12](https://user-images.githubusercontent.com/55796705/66042160-2a774e00-e535-11e9-8404-d1f793d08716.jpg)
