### ISSUE TITLE
Client Feedback October 4 2019

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#203]
1) Hi Nathan, Please have a look at dashboard features we have available in system,please confirm so that we proceed with its integration. if anything else you need in dashboard please do let me know, we will use similar box type design as you suggest earlier.

1) Dashboard Admin

-Active/Graduated/Terminated Students
-New Admissions
-Fee Collection Summary
-Attendance summary

2) Staff Dashboard

-Upcoming Events
-Program Hours and Remaining Hours
-Attendance Summary
-Latest Inquiry

3) Student Dashboard

Attendance Summary
Upcoming events
Program Hours and Remaining Hours
Total Fee and Remaining Fee

**Client comments:

That is good, Please proceed with integration**

**Comment by serviceproviderpk** [comment]
2) 
![request](https://user-images.githubusercontent.com/19146254/66174720-e50b6b80-e66f-11e9-89cb-0d33491d0d09.png)

As the Screenshot I added can we remove the text at the top and just change it too "this form is for any NON - EMERGENCY Requests, for any emergency requests please call 403-615-1015" you ca get rid of the rest

**Comment by adilshehbaz** [comment]
2. Fixed

**Comment by adilshehbaz** [comment]
1. Fixed
Please review dashboard and check

**Comment by serviceproviderpk** [comment]
2) Get latest code from TFS and add this link in all emails that we are sending to the staff/admin/students


> To access Dashboard visit => http://niwe.schoolmanagementsoftware.pk

**Comment by serviceproviderpk** [comment]
3) Send Email button not working.
![image](https://user-images.githubusercontent.com/19146254/66265897-2437e900-e837-11e9-9525-3a9b76d6a806.png)

**Comment by serviceproviderpk** [comment]
4) 60% Fee Reminder = This is a friendly reminder that you should have paid 100 % of your tuition by now.
If you have any questions or concerns please contact accounting@niwe.ca.

if student attendance is 60% or greater than 60% and he didnot paid his full fee.

then reminder shd send all students.

forexample, one student attdenace is 97% and  second stuent atteance is 69%

and reminder screen showing one student.
![image](https://user-images.githubusercontent.com/19146254/66265998-79282f00-e838-11e9-9f4f-c3339f1f8b2c.png)

in above grid, Please show one column "Completed Hours" show some of attendance hour, it will reduce the confusion as well.


![image](https://user-images.githubusercontent.com/19146254/66697829-922a5780-ecf2-11e9-8539-075f0e4a3ef4.png)


on reminder of 60% and 80% correct record are not displayed.

**Comment by serviceproviderpk** [comment]
5) Graduation reminder not displaying the data , one student has completed 97% of his course.

![image](https://user-images.githubusercontent.com/19146254/66266028-c4424200-e838-11e9-9d60-8bf014fda227.png)


in next screen grid, Please show  a column with "Completion Hours"

**Comment by serviceproviderpk** [comment]
6) Student Dashobard
![image](https://user-images.githubusercontent.com/19146254/66266065-28650600-e839-11e9-8a0b-2284649b8177.png)

Display data in html table as.

Program, Session, Total Duration(hours) , Completion Hours, Total Fee, Paid Fee, Remaining Fee.
HTML,     Morning , 100 Hours ,                 50 Hours,                $1000,    $60,          $40
HTML,     Morning , 100 Hours ,                 50 Hours,                $1000,    $60,          $40
aspnet,    Morning , 100 Hours ,                 40 Hours,                $1000,    $1000,       $0

**Comment by serviceproviderpk** [comment]
Dashboard
a) when admin and super admin will be login dasbhaord name will be

b) For staff dashobard name  "StaffDasbhoard"
c) for Student  "StudentDashobard

Please separate actions

**Comment by adilshehbaz** [comment]
In case of different dashboard,

we need to change on every screen dashboard link that's why i am holding this for now

**Comment by adilshehbaz** [comment]
2. Fixed

**Comment by adilshehbaz** [comment]
5. Fixed

**Comment by adilshehbaz** [comment]
4. I tried a lot but unable to find why send buton not working i change every idd and class

can you please check this??

task # 4 is not related to button submit it is related to display data in grid.

**Comment by serviceproviderpk** [comment]
2) 
![image](https://user-images.githubusercontent.com/19146254/66444882-6000c780-ea5e-11e9-9516-bfa4eb4ca64c.png)

**Comment by adilshehbaz** [comment]
We are sending simple text in email not html.

**Comment by adilshehbaz** [comment]
6. Fixed

**Comment by serviceproviderpk** [comment]
@adilshehbaz  3,4
when you get chance, Please visit office and take help from Nawab.



Thanks,

**Comment by serviceproviderpk** [comment]
In case of different dashboard,

we need to change on every screen dashboard link that's why i am holding this for now

@adilshehbaz 
**use same dashobard and show hide section according to the user profle.**
