### ISSUE TITLE
Khalid Task

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#204]
0) 3 splash pics as WD and then  header  logo+search
1)  logo+search icon in all pages   (remove menu icon from top)
2)  remove extra space form top+right+left side of  menu icon+logo+search icon
3) show header in all pages
6) novel list page ,remove left space from the title , title, and image must be click able. add som space in footer of the row.
7) on novel detail page, show other detail of novel like
	Created Date, category, number of views,maxium information whatever we can display
 
@Muhammadkhalid66

**Comment by serviceproviderpk** [comment]
1) Fixed

**Comment by serviceproviderpk** [comment]
@Muhammadkhalid66  as joined office discuss "0" point plz

**Comment by serviceproviderpk** [comment]
0) MapController
a) Welcome1  show logo in center and in footer copy right text
b) Welcome2 Logo on top and will have fllowing boxex
  1) Novel
2) Interviews
3) Poetry 
4) Books
5) Submit your contents,  Share and Earn Money
c) Welcome3

How you can earn!!!
a) Earnings per share
b) Earnings per post
c) Earning per  views & review

  
on click "Index" of "MapController"

**Comment by serviceproviderpk** [comment]
map index

a) logo in first row on right side search icon
b) inner pages  "Back button" logo"+search

**Comment by Muhammadkhalid66** [comment]
a) logo in first row on right side search icon        fixed
b) inner pages "Back button" logo"+search         fixed
@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
welcome 1 fixed
welcome 2 fixed
welcome 3 fixed

**Comment by Muhammadkhalid66** [comment]
welcome 1 fixed
welcome 2 fixed
welcome 3 fixed
on click "Index" of "MapController"  fixed

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
3 splash pics as WD and then header logo+search  fixed
logo+search icon in all pages (remove menu icon from top) fixed
remove extra space form top+right+left side of menu icon+logo+search icon  fixed
show header in all pages fixed

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
novel list page ,remove left space from the title , title, and image must be click able. add som space in footer of the row.  Fixed
@serviceproviderpk
