### ISSUE TITLE
NiweTask

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#205]
1-

**Comment by serviceproviderpk** [comment]
2) Can we please change the name of "Inquiry Student" to "Inquiries"
a) 
![image](https://user-images.githubusercontent.com/19146254/67547969-ffd67a80-f719-11e9-8400-92935372c2e8.png)
b) 
![image](https://user-images.githubusercontent.com/19146254/67547997-15e43b00-f71a-11e9-9e92-7d2d619f9321.png)
c)
![image](https://user-images.githubusercontent.com/19146254/67548057-44621600-f71a-11e9-8bbc-bba8e93068ee.png)

**Comment by serviceproviderpk** [comment]
3) Create order request form, and its link below the service request
a)
b) when order and request is submitted send email to below email address
Please ensure both these forms go to ramesh@niwe.ca and cc service@servicepro..pk

**Comment by serviceproviderpk** [comment]
4)
![events](https://user-images.githubusercontent.com/19146254/67631028-93db4a00-f8b2-11e9-8f88-11ecbc3d08ed.png)

a)  Please change  text "Events" to Calendar
b) Can we make an "ad event" button to the calendar.
c) Basically what i want to do is have 2 calender's one for the program and course start dates and another for any miscellaneous events. essentially a drop down menu to switch calendar. please let me know if you would like clarification.

**Comment by serviceproviderpk** [comment]
4) Grid right click option=> Please adjust this method of highlighting from only clicking to hovering over, this will allow the user to find the link easier without error for miss clicking.

**Comment by serviceproviderpk** [comment]
6) I request that the font be easier on the eyes and be consistent with the body of the CRM, the left side panel has a different font and is harder on the eyes.

for left menu item and sub item => Please change to Segoe UI Semilight

**Comment by serviceproviderpk** [comment]
7)
When i click the report "Student Status Report" the attached error screen shot came up.
![image](https://user-images.githubusercontent.com/19146254/67911099-0dbb4e00-fba7-11e9-908e-c1d492f9a1cc.png)

when i click i see error
![image](https://user-images.githubusercontent.com/19146254/67911136-3cd1bf80-fba7-11e9-9257-89f344ca9d11.png)

**Comment by serviceproviderpk** [comment]
8)When changing a students status it should be more automatic vs manual. On the Prospect tab, it gives you an option to change the status to Registered but then when you see the next tab on Student it isn’t transferred there, even though it prompts you with a question in line with, “ This student will now be changed to Registered student”. But it actually does not show that. In addition, the drop down tab should list: Prospect, Registered, Enrolled , Never Attended, Withdrawn and Other.

**Comment by serviceproviderpk** [comment]
9) in add/edit student  add student photo option.

**Comment by serviceproviderpk** [comment]
10) In program list add new option in "Context menu"
"Duplicate"
here in this case we can give you an option to replicate program.

Procedure will be:
1) through right click or grid of programs will start showing "Duplicate" button infront of each record and once you press it, you just need to enter second start/end date to save the record and you are done.

**Comment by adilshehbaz** [comment]
10: Fixed

**Comment by adilshehbaz** [comment]
9 Fixed

**Comment by adilshehbaz** [comment]
8 Fixed

**Comment by serviceproviderpk** [comment]
@adilshehbaz  Please re-test above issues
i think you added no commnets about  # 6

**Comment by serviceproviderpk** [comment]
10) Not fixed, as requested. i have explained on voice msg.

**Comment by adilshehbaz** [comment]
2 Fixed

**Comment by serviceproviderpk** [comment]
@TahirHussai 
in order email and serice reqeust email, please use simple template for sending email

that we are using  getting student create email.

1)  in order request email, if  Urgent: True use "Yes"  or not
2) 1)  in server request email, if  Urgent: True use "Yes"  or not

**Comment by serviceproviderpk** [comment]
2) in  add/edit student show picutre preview same as we are doing in school software

**Comment by TahirHussai** [comment]
1.in order email and serice reqeust email, please use simple template for sending email
2.in add/edit student show picture preview same as we are doing in school software.
3.ogram list > Right click on grid > Choose "Duplicate"
######################################RRF######################

**Comment by serviceproviderpk** [comment]
1) i make duplicate copy of a program, i changed program code and title it was not changed.

**Comment by serviceproviderpk** [comment]
2) i removed the picture and save, it was not removed.

**Comment by serviceproviderpk** [comment]
3) not getting email on  email id that was added in system defualt settings

**Comment by serviceproviderpk** [comment]
4) file:///C:/Users/asifj/Downloads/Transcript_Nathan%20%20%20Sharma132181425704240922.pdf

there must be no space between file names

**Comment by serviceproviderpk** [comment]
@TahirHussai why you disabled program title and code?

**Comment by serviceproviderpk** [comment]
1) in Order request and service request 

Please add a "completed" and "Delete" feature
![image](https://user-images.githubusercontent.com/19146254/68958658-59e4d000-07ee-11ea-9545-f50a93fbba84.png)

Suggestion:
add RequestStatus =Active, Deleted,Completed.
in list we will show only "Active" status

**Comment by serviceproviderpk** [comment]
2) in left menu use this font "Segoe® UI Symbol"
https://fonts.google.com/?query=Segoe%C2%AE+UI+Symbol
![image](https://user-images.githubusercontent.com/19146254/68958920-e3949d80-07ee-11ea-8931-d1954817a092.png)

**Comment by serviceproviderpk** [comment]
@adilshehbaz 

2) use # 1 font for left menu and sub menu

http://niwe.schoolmanagementsoftware.pk/font-index.html

**Comment by adilshehbaz** [comment]
2 Fixed

**Comment by serviceproviderpk** [comment]
3) admission tracker
4) merge in one menu "order requests and service requests"
