### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#207]
For NewEraMag

1- logo  180*180 and 160*160 => transpatent
2- Welcome Screen with "red rose" Back ground color
in Center show logo as text "New Era Magzine"
3- Latest splash with new logo
4- logo for mobile app size
2- 9 photo of = 174px*300

1) Mobile App logo 2 size
2) Welcome Screen
3) Splash screen, remove round, use simple or box types
4) Logo+9 images

**Comment by serviceproviderpk** [comment]
For  school management software.pk

for logo color scheem=> http://schoolmanagementsoftware.pk/

1) welcome  Screen logo in center
2) Splash screen with following features


1. Student Profile
2. Attendance History
3. Student Leaves
4. Apply for Leaves
5. Fee History
6. Holidays
7. Notifications
8. Test & Exam

foreexmaple
![image](https://user-images.githubusercontent.com/19146254/68065064-74766e00-fd45-11e9-9e62-25b9f604e5be.png)

3) Logo for mobile app size


for Khalid

![image](https://user-images.githubusercontent.com/19146254/68065072-a12a8580-fd45-11e9-98ca-72797d734ea0.png)

**Comment by serviceproviderpk** [comment]
@Muhammadkhalid66 


Home, Progress,  Attendance, Fee, More

more=>

Dashboard,
Progress,
Attendance,
Fee
Logout

Dashobard

![image](https://user-images.githubusercontent.com/19146254/68697122-0a10c980-05a0-11ea-8195-82ba342a916f.png)

**Comment by Muhammadkhalid66** [comment]
Home, Progress, Attendance, Fee, More

more=>

Dashboard,
Progress,
Attendance,
Fee
Logout

Dashobard

image
![image](https://user-images.githubusercontent.com/41336284/68791272-c2a33f80-066a-11ea-82b7-311cf4f50ec8.png)

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
For school management software.pk
welcome Screen logo in center Fixed
Splash screen with following features Fixed
Student Profile  Fixed
![image](https://user-images.githubusercontent.com/41336284/68791717-b23f9480-066b-11ea-9050-2ff77ebe8934.png)

Attendance History Fixed
Student Leaves Fixed
Apply for Leaves  Fixed
Fee History Fixed
Holidays Fixed
Notifications Fixed
Test & Exam Fixed
![image](https://user-images.githubusercontent.com/41336284/68791788-d3a08080-066b-11ea-8c09-b344532001a0.png)


![image](https://user-images.githubusercontent.com/41336284/68791463-30e80200-066b-11ea-97db-968e891155f7.png)

Fixed

@serviceproviderpk
