### ISSUE TITLE
Khalid task

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#208]
1)

**Comment by serviceproviderpk** [comment]
2) Novel list
a) Font  Normal: 13px;
b) Font  Smaller : 12px
c) page heading font family little readable
e)  margin 2px from left side of image

**Comment by serviceproviderpk** [comment]
3) Novel details 
zoom out of image, see what property is using

**Comment by serviceproviderpk** [comment]
4)  Register page must have

Contact Name, Email, Password and Phone ONLy

**Comment by serviceproviderpk** [comment]
5) Poetry
Create detail page of poetry

**Comment by serviceproviderpk** [comment]
6) if user click on about us, show about us page
7) if user click on  "Contact us" page show contact page.

**Comment by serviceproviderpk** [comment]
8) if user click on writers show writer list
if user click on any write show its novel

**Comment by serviceproviderpk** [comment]
9) please test all links are working fine.

**Comment by serviceproviderpk** [comment]
10) on  all pages, use section of heading in all pages.

**Comment by serviceproviderpk** [comment]
11) if mobile website is open in windows browser. show max widht max width of mobile device

**Comment by serviceproviderpk** [comment]
12- Logo used in mobile app, please request to Sarmad add space ike

New Era Magazine  instead of "neweramagazine"

**Comment by serviceproviderpk** [comment]
13) User must able able to  delete his "boook mark" pages

**Comment by serviceproviderpk** [comment]
14) user SessionExpire filter to all Actions, which are getting use id from "Section"

**Comment by serviceproviderpk** [comment]
15) if user type is "admin" add menu 
"member Feedback"

and show all feedback list. that was added by users

**Comment by serviceproviderpk** [comment]
16) use page heading for following
a)
![image](https://user-images.githubusercontent.com/19146254/68079064-f37eab80-fe04-11e9-88f1-d52763a16e2e.png)

**Comment by serviceproviderpk** [comment]
17)  "Member of the Week " Feature
a) Create new table "MemberOfTheWeek" (Id,CreatedBYuserID,CreatedDateTime,WinnerUserID,Description)
in menu show list of "Member of the Week"
when user click on any user show following details
Contact Name, CreatedDate,Description.

**Comment by serviceproviderpk** [comment]
18) in Edit Profile page

a) use validation for first Name, Last Name, City, About my self.
b) Please space when you add in lable like" FirstName" must be "First Name"
c) Use Profile Photo in edit Profile

**Comment by serviceproviderpk** [comment]
19) Logo is not center of the page
![image](https://user-images.githubusercontent.com/19146254/68172781-a46a7f00-ff9a-11e9-88bc-90cbc2356e48.png)

20) 
![image](https://user-images.githubusercontent.com/19146254/68172820-c237e400-ff9a-11e9-9ca4-789cbce9e4fc.png)

remove following headings
"Total Poetry", Total Novels, Total Members, 
Total Writers

**Comment by serviceproviderpk** [comment]
21) Record not found must be in center of the page, Please make sure use standard font size
![image](https://user-images.githubusercontent.com/19146254/68172945-2c508900-ff9b-11e9-9bd0-b52012cf574d.png)

**Comment by serviceproviderpk** [comment]
22) Text must me in centerd, for download plugin change its color to blue
![image](https://user-images.githubusercontent.com/19146254/68173014-628e0880-ff9b-11e9-8e75-62005553a462.png)

**Comment by serviceproviderpk** [comment]
23) use full back ground for page heading
![image](https://user-images.githubusercontent.com/19146254/68173064-881b1200-ff9b-11e9-967e-01a02cc3ac37.png)

**Comment by serviceproviderpk** [comment]
24) When user click on "BookMark"
![image](https://user-images.githubusercontent.com/19146254/68173158-e1834100-ff9b-11e9-9c81-40ac39059e3c.png)

a) show list of bookmark of the users.
b) Add delete button in Bookmark list page

**Comment by serviceproviderpk** [comment]
25) Add new section or Link
"Member of the  Week" (UserID,Photo, Name, Address, City, Introduction)

> you will storeprocedure that will link User Table to get other details of the users.

a) when user click on it, show list of "Member of the week"
b) admin user can create and delete member of the week.
c) on click on any user show profile of that user.

**Comment by serviceproviderpk** [comment]
26)also add menu "Member of the Week"

**Comment by serviceproviderpk** [comment]
27) Correct spellings are  " New Era Magazine "

**Comment by Muhammadkhalid66** [comment]
1-use this font family to page headings.       Fix

a) Rename "Urdu Novels" to "Novels"     Fix
b) Urdu Poetry to "Poetry"     Fix
c) Rename "Bookmark pages" to "My Bookmarking"     Fix
when user click on "My Bookmarking" show user book marking list page     Fix
d) remove below section     Fix
e) Total Novels (9487)      Fix
Total Writers (948)      Fix

change to "

Total Poetry (2589) Total Novels (9487) Total Members (589) Total Writers (948)      Fix

f) when user click on "Writers" show list of writers      Fix
when user click on "Any writer" show its Novels list.      Fix
for novel list we will use existing list of novel, we will pass Writer ID or User ID as parameters.      Fix
g) when user click on "About us" show "About us" page      Fix
h) When user click on "Contact us" show contact us page      Fix
i) when user is logged in Change "Login/Register" to "My Account" show user account page     Fix



@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
if user type is "admin" add menu    Fix
"member Feedback"
use page heading for following     Fix
a) "Submit your Idea"     Fix
a) show Contact Name, Email, Phone and Description.     Fix
Member of the Week " Feature
a) Create new table "MemberOfTheWeek" (Id,CreatedBYuserID,CreatedDateTime,WinnerUserID,Description)     Fix
in menu show list of "Member of the Week"
when user click on any user show following details     Fix
Contact Name, CreatedDate,Description.     Fix
Logo is not center of the page     Fix
remove following headings     Fix
"Total Poetry", Total Novels, Total Members,     Fix
Total Writers
Text must me in centerd, for download plugin change its color to blue
use full back ground for page heading     Fix


@serviceproviderpk

**Comment by serviceproviderpk** [comment]
1) Add delete option, in "Book marking" list
