### ISSUE TITLE
tahir task

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#209]
0) Create new controller with "DashboardV2" 
a) Create index page with out any model
b) when user click on footer "© Copyright 2019 NIWE Academy. All Right Reserved."
show that page , show text coming soon.

**Comment by serviceproviderpk** [comment]
2) order + service email on email id of our and cient that is

emaill be send on "AdminEmails" 
![image](https://user-images.githubusercontent.com/19146254/68455701-ce7fa380-021d-11ea-81c0-f8343b56f980.png)


a) Email 1

Subject: Service Requests

Dear Niwe Team,

Below is service request
Request Type: asfasfasfas
Subject : asasdf
Urgent: Yes or NO
Description:

Regards,
CRM Team

b) Email 2 (Order)
3)report
[Admissions_Tracker (1).xlsx](https://github.com/serviceproviderpk/sp.pk/files/3814200/Admissions_Tracker.1.xlsx)

**Comment by serviceproviderpk** [comment]
) on error send emial

**Comment by serviceproviderpk** [comment]
3)  in add/edit Student add photo option, make sure image is uploading in "UploadesStuff" folder

**Comment by serviceproviderpk** [comment]
4) Here is the final copy,

The one big change aside from the "NIWE Academy Official" is i noticed that the name was "Nathan . Sharma" can we please remove the period?

Also the transcript is named "Transcript-410c0c01-68c9-4c72-b4ea-a31b8bc96874"

Can we please have it named what the students name is?

For example: (Transcript_Nathan Sharma)

Transcript-410c0c01-68c9-4c72-b4ea-a31b8bc96874.pdf

**Comment by serviceproviderpk** [comment]
5) Change Remarks to Comments, on all pages

6)  Inquiry reports
a) Admission Tracker Summary
a) Program Summary

**Comment by TahirHussai** [comment]
1.Create new controller with "DashboardV2"
2.order + service email on email id of our and cient that is
4.Here is the final copy,
The one big change aside from the "NIWE Academy Official" is i noticed that the name was "Nathan . Sharma" can we please remove the period?
5.Change Remarks to Comments, on all pages
######################################RFR#################################
