### ISSUE TITLE
SP.PK

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#21]
-

**Comment by serviceproviderpk** [comment]
1) tick icon update 
2) services heading clickable and on click show relevant page, just like about us. heading+text will be changeable from admin section.
3) use captacha that was used in innexception tak help from Khalid
4) admin section show list of developers, admin sh'd be able to edit the developers.
5)  from menu "Account" remove sub items. it will be main menu
when user will click on "Account" we will show him login page. if user is already logged then will redirect him on his dashobard
6) when admin logged in show him
a) To do list on top
b) Left side, Enquiry, right side "Problems"
and then  "Admissions"

**Comment by serviceproviderpk** [comment]
12- Crud for UserProfileRating

**Comment by serviceproviderpk** [comment]
1) I have added two tables SeoOrm and  SeoOrmDocument , Please do its CRUD
Only admin and developer can add/edit/delete it.
add new menu in "Projects"
Rename "Project" menu to "Development"
2) in "Web Portal" menu show list of "Submit Your Problem" admin sh'd be able to Delete it
and reply it. (add new button in it, Reply" when user click on it, he can enter some text and presss button email will be send to to the that guy who submit problem.

**Comment by MughalBilal** [comment]
Ok fine sir.

**Comment by serviceproviderpk** [comment]
1) Show Hosting list order by "ExpiryDate" upcoming renew hosting will be on top
2) From website header remove gray back ground , use white background for it.
![image](https://user-images.githubusercontent.com/19146254/35495840-ca0d4682-04e4-11e8-8d6e-4f46d1d88652.png)
link color or icon color can be used gray or green of theme
3) Add dropdown of Quick Links
![image](https://user-images.githubusercontent.com/19146254/35495875-fd0a7352-04e4-11e8-9f8b-edb0f772db41.png)

- To do list
- Admision request
- Problems
- Inquiry
- Timesheet
- Hosting
-

**Comment by serviceproviderpk** [comment]
4) Please set proper meta data of ech page of website
for below page you can see
view-source:http://serviceprovider.pk/Training

![image](https://user-images.githubusercontent.com/19146254/35496027-243864f6-04e6-11e8-8be1-380dc6ffbc6d.png)

**Comment by serviceproviderpk** [comment]
5)on http://serviceprovider.pk/admission right show course list
with title and description  (for descrition use raw html) we will add details of courses.

**Comment by serviceproviderpk** [comment]
6) ON CONTACT US PAGE SHOW OFFICE ADDRESS, ALSO SHOW PTCL NUMBER AS WELL AS.

**Comment by serviceproviderpk** [comment]
7- Banner text is not readable use shadow or some border for font. right now its not readable.

**Comment by serviceproviderpk** [comment]
@adilshehbaz  we need to minimize the exception error by fixing the issues. right now are getting bundle of email on  sgs+scl+sp.pk

**Comment by UsmanJafar321** [comment]
All issues has been fixed except 5 and 6.

**Comment by serviceproviderpk** [comment]
Please also upload code on live.

**Comment by UsmanJafar321** [comment]
Sir upload now or tomorrow??

**Comment by serviceproviderpk** [comment]
its upto you.

**Comment by UsmanJafar321** [comment]
sir i think we should upload tomorrow after finishing invoice module what
is ur opinion ?

**Comment by serviceproviderpk** [comment]
7) http://serviceprovider.pk/Our-Clients  and http://serviceprovider.pk/Portfolio show  website link
8) on home page show on  3 projects in section "OUR LATEST PROJECT"
it will be configureable from admin
9) in footer of layout © 2017 All Rights Reserved
year sh'd be change from C# code like @Date.now.year
10)  in footer of website these are some icons of "Payments" if user click on any icon
redirect to a page "Payment"
it contents will be changeable from admin using  "Staticpage" table
11) From home page remove this image
![image](https://user-images.githubusercontent.com/19146254/38066178-4fa1f036-3320-11e8-86aa-e0bbb04dcf7b.png)

in the place of this image, use some text,that will show some information related to us.

**Comment by serviceproviderpk** [comment]
12) on this page http://serviceprovider.pk/admission
you can see list of Coursed, when user click on any Course show its detail and on left side show partial view or course. also add a button on detail page "Apply Now" when user click on it then redirect to 
http://serviceprovider.pk/admission

I suggest remove heading banner form this page.

**Comment by serviceproviderpk** [comment]
**Pending task**

**Comment by serviceproviderpk** [comment]
1) use label for invoice item i requrested
2) Delete Item from edit invoice screen not working
3) i sh'd be able to delete invoice and it's item if there is no payment against this invoice
4)  Sometime "Invoice list" is not working due append of "#" in URL
5)  When i  click on send email  it sh'd be open in new page.  when email is send "redirect to list of invoice page with thanks, instead of "dummy " page with thanks.
6)If i click on Cancel button in "CRUD invoice" it sh'd redrect me to "Invoice List page"

**Comment by serviceproviderpk** [comment]
8) i see phone direcotry text is white 
![image](https://user-images.githubusercontent.com/19146254/38224979-1743051e-370c-11e8-8f87-b12e2651d3ca.png)
although i fixed it.
when i click on "Direcotry" page it sh'd show the list and details as i explained in your.
show nubmer which are showalltrue if user is logged then show his added number

List of direct and detail page of direct will not use "Admin Layout" it sh'd use customer layout page.

**Comment by serviceproviderpk** [comment]
9) on course detail page "http://localhost:7185/Admission/Coursedetails?id=2" on left side show list of coursed as i explained.
with proper heading.

**Comment by serviceproviderpk** [comment]
10) In "Manage Invoice" add new sub menu
"Contracts" do it crud. i have already Created Table with name "Conracts"
Create html page as invoice use contents of "Contract" i have shrared with adil
11) if user is logged in he sh'd be able to edit his all infomration that is added in table of "UserProfile"
Please double check it.

request to all employee+developer+admin update there profile ASP today.

**Comment by serviceproviderpk** [comment]
12 ) Check task and task activity feature. make sure, its working fine . if any issue fix it you can take help form adil.

**Comment by serviceproviderpk** [comment]
i have created 3 tables in a file that i have sent you on skype

1) Service Package type, ServicePacckage and ServicePackageRequest

Please do it crud,

admin sh'd be able to add/edit ServicePacakge type, Sevices Package

**Comment by serviceproviderpk** [comment]
1) remove this type of banner from all  pages, keep it simple as home page.
![image](https://user-images.githubusercontent.com/19146254/38782471-7e74cfaa-410d-11e8-9c1f-7f8646bcc43e.png)
2) Please make sure every page has proper Route 
e.g. course detail, seo package list and package detail, also check other page.
3) Phone Directory page sh'w show data in a list, fill left side with some partial view.
and also show detail page, it will be also filled with partial views

**Comment by serviceproviderpk** [comment]
1. Page title spacing from top and bttom sh'd be same as at home page

![image](https://user-images.githubusercontent.com/19146254/38829935-1d9ac424-41d4-11e8-947f-49ad072caa6f.png)
![image](https://user-images.githubusercontent.com/19146254/38829986-4839f178-41d4-11e8-8978-d0ecc58ca689.png)

you can see  the diffrence

**Comment by serviceproviderpk** [comment]
1) When user add "Followup" entry, send email to the service@.ser...pk
2) in follow up screen add "Delete" button when user click on delete after confirmation user will add some comments in text box. then we will add some comment(reason of deletion) after this email will be sent to customer.

**Comment by serviceproviderpk** [comment]
**Create a new table**

MyDocuments(ID,Title,Description,FileURL,CreatedDate)

**Comment by serviceproviderpk** [comment]
**For Shahid Riaz**

we need to categorize the "Pojects"
so on portfolio page we need to show category on left side and right side list of projects 
http://www.serviceprovider.pk/Portfolio
for category we will use table "ServiceCategory"

using sql script we will add new forign ki in "Project" Table
i will explain it.


4) If user type is admin and he logged in show edit button in front of each page
http://www.serviceprovider.pk/site-map
5) Create a new controller with name "PaymentMethods"

show compnay bank account detail on it with some good look and feel.
ref: https://websouls.com/payment.html

) Jazz Cash account   - for sim of Jaz 0300 4761693  please open jaz cash account
) Telenor Easy paisa = get mobile number from nawab and get  easy paisa account plz


6) in footer of the website add some text as added in below
![image](https://user-images.githubusercontent.com/19146254/43987404-95b335b6-9d39-11e8-92ed-7a0c7cbf41f6.png)

text will be

"ServiceProvider.Pk is software Development Company situated in Lahore Pakistan, we are offering Web Development, Web Designing, SEO and Social Media promotions of Brands in very affordable prices.
We offer our clients global development resources, 24-hour service and support, and we have more than 10 years of professional development experience. We are Microsoft certified professional especially in web development. "
7) Complete flow of service category, subcategory and services
if user click on  on subcateogry " show list of "SupplierServices" from
 table "SupplierServices"
in admin section we have already curd of these screeens

**Comment by serviceproviderpk** [comment]
7. - When user add "Followup" entry, send email to the service@.ser...pk
8. - in follow up screen add "Delete" button when user click on delete after confirmation user will add some comments in text box. then we will add some comment(reason of deletion) after this email will be sent to customer.
9. - Also use breadcrumb in followup and edit enqyiry page

**Comment by serviceproviderpk** [comment]
10) Task email and time sheet email sh'd be not SAME
task menu / time sheet menu submission

**Comment by serviceproviderpk** [comment]
Zaif / Shahid

Make sure services section and phone direcotry section working fine.

11) in all admin pages, use link of detail page.
like if i lick on title in grid of amdin it sh'd show detail page on front end page.
e.g
![image](https://user-images.githubusercontent.com/19146254/44008785-8cad861e-9ec0-11e8-865f-f04d5fdaa19a.png)

12) Client and client invoices features with proper working.
User type as client,
then UserSevices
according the services create invoice.
every service will have some ServiceDate
all changes will be done via script
use linq to sql instead of Store procedure.

**Comment by serviceproviderpk** [comment]
Customer menu   **RFR**

Customers **RFR**

Comnaynanem Name,Email,Phone,Address,description **RFR**

CustomerContacts(CustomerId,Name,email,phone,address,EnableEmail) **RFR**

CustomerServices:ID,CustomerId,ServiceName,Description, Price,Quanity,ServiceDateTime **RFR**

**Comment by serviceproviderpk** [comment]
update Enquiry set CreatedByuserID=1 where CreatedByuserID is null **RFR**

1) user is not logged in then submit an enqyiry . we will set admin id hardcode. **RFR**
2) on edit enqury  show dropdown of users
3) if admin show all fllowup other wise show follow of that user only **RFR**
4) Creentails link will be only for admin. Now it is in Cutomer dropdown link **RFR**
