### ISSUE TITLE
Fun2Fresh App Feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#215]
-

**Comment by serviceproviderpk** [comment]
1) Menu Settings

1) "My Profile" menu will have following sub menu
- My  To do list
- My Meetings
- My Readings
- My Contacts
- My Expenses
2) My Interests
  show menu according to the User Interests
3) Pic of the Week

4)  My Settings will have following sub menu
- My Profile
- Edit Profile
- Change Password

in footer  of left menu bar show logout button

**Comment by serviceproviderpk** [comment]
2)  From Login page,  remove extra space from top/bottom, user must not be scrool down to see login button.
b) on login and register page add new link "Back to home"
when user lick on it show home page of the app.

**Comment by serviceproviderpk** [comment]
3) in top header reduce logo height   40% please. so that it give some good look

**Comment by Muhammadkhalid66** [comment]
Menu Settings

"My Profile" menu will have following sub menu

My To do list
My Meetings
My Readings
My Contacts
My Expenses
My Interests
show menu according to the User Interests

Pic of the Week

My Settings will have following sub menu

My Profile
Edit Profile
Change Password
in footer of left menu bar show logout button

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
1-Menu Settings

2-"My Profile" menu will have following sub menu Fix

My To do list
My Meetings
My Readings
My Contacts
My Expenses
My Interests
3-show menu according to the User Interests Fix

Pic of the Week

My Settings will have following sub menu Fix

My Profile 
Edit Profile 
Change Password 
in footer of left menu bar show logout button Fix

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
From Login page, remove extra space from top/bottom, user must not be scrool down to see login button. Fix
b) on login and register page add new link "Back to home"  Fix
when user lick on it show home page of the app.


@serviceproviderpk

**Comment by serviceproviderpk** [comment]
1) from header reduce height of the logo 20% more
2)  in  left bar, for sub menu display arrow, 
![image](https://user-images.githubusercontent.com/19146254/71497400-d4871d80-2879-11ea-976d-769d6210dd34.png)

note! it was already available in the code when i shared with you first time.

**Comment by serviceproviderpk** [comment]
3) Logged in not working. its really amazing, you did lot of effort and login page not working!!

**Comment by serviceproviderpk** [comment]
4) Change position of both link 
![image](https://user-images.githubusercontent.com/19146254/71497514-5e36eb00-287a-11ea-86bb-49888e243721.png)
a) Forget Password  (left side)
b) Create Account (right side)
c) Improve formatting of  forgot Password page. its looking different from the theme
d) use sub heading for all pages with proper formatting

use proper css for both link

**Comment by serviceproviderpk** [comment]
5) Create new account as visitor, and make sure everything is working fine.
6) login as admin make sure everthing is working fine.
8) in left menu  "My Interests" remove the word "My" from sub menu"
when user will click on them we will display all data
7) message me on whatsapp, from myside everything is ready from my side.
then i will test and share me feedback.
i wish to submit in play store tomorrow.

**Comment by serviceproviderpk** [comment]
9) from add Gold words remove following 
PageTitle
PageKeyword
PageDescription

Please give some good look to create pages.
show only required fields.

**Comment by Muhammadkhalid66** [comment]
Change position of both link Fix

a) Forget Password (left side)
b) Create Account (right side) 
c) Improve formatting of forgot Password page. its looking different from the theme Fix
d) use sub heading for all pages with proper formatting Fix


@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
it's also Working sir i test in my Own cell.
3-Logged in not working. its really amazing, you did lot of effort and login page not working!! Fix 

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
9-from add Gold words remove following
PageTitle Fix
PageKeyword Fix
PageDescription Fix
Please give some good look to create pages. Fix
show only required fields. Fix

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
Sir wo code nai mila mujha skype pa mana us code ko download krna ki koshash ki mgr nai howa.

mana khud sa kr dia ha fix
from header reduce height of the logo 20% more Fix
in left bar, for sub menu display arrow, Fix 
note! it was already available in the code when i shared with you first time. Fix

@serviceproviderpk
