### ISSUE TITLE
Fun2Fresh MAP FEEDBACK

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#216]

**Comment by serviceproviderpk** [comment]
1) My interests
from submenu remove my word
when user click on any sub menu show all data

**Comment by serviceproviderpk** [comment]
/Goldenwords/Index

a) /Goldenwords/Index?userid=1   (my golden words)
b) a) /Goldenwords/Index   ( golden words)

**Comment by serviceproviderpk** [comment]
2) if user not logged in and try access user specific pages redirect on login page.

**Comment by serviceproviderpk** [comment]
3) on all add/edit scree use proper formatting and proper heading with proper spacing
proper labeling

**Comment by serviceproviderpk** [comment]
4) on Register page show following fields

1) Firs Last , Last Name, Email, Password, about me

**Comment by Muhammadkhalid66** [comment]
on Register page show following fields Fix

Firs Last , Last Name, Email, Password, about me Fix

@serviceproviderpk

**Comment by serviceproviderpk** [comment]
6) http://fun2fresh.com/Map/ToDoList
a) hide Task Type
b) show

**Comment by serviceproviderpk** [comment]
7)   http://fun2fresh.com/Map/ShowGoldenWords
a) in footer display Posted by: last name  Posted on: Date time
b) Display category button below the pages and rename it to "Browse by category"
![image](https://user-images.githubusercontent.com/19146254/71551816-c79d3200-2a11-11ea-898e-6471d7b4e7d7.png)
c) Create Golden Word will have following fields (hide other fields)
Choose Category
Description
Image
Save and Cancel button

if user click on "Cancel" redirect to "list of Golden words
if user click on save redirect to thanks page with

You have successfully save the record.

**Comment by serviceproviderpk** [comment]
8) http://fun2fresh.com/Map/ShowPoetry
dispaly category button in bottom.

**Comment by serviceproviderpk** [comment]
9) on create poetry show following fileds only

a) choose category
b)Description
c)Choose Image

Save and Cancel button

**Comment by serviceproviderpk** [comment]
10) http://fun2fresh.com/Map/ShowHandiCrafts
display category in footer


in create screen show following fiedls
a) Choose category
b)Description
c) Choose image
Save and Cancel button remove other fields


in list of handicraft display
Posted by: last name and Posted on: date time

**Comment by serviceproviderpk** [comment]
11) Picture of the week list 
a ) show Posted by and Posted on
b) show detail link
c) link must be shareable on whatsapp using share this or add this plugin. as we did for newera

**Comment by serviceproviderpk** [comment]
12) change to "Picture of the week"
![image](https://user-images.githubusercontent.com/19146254/71552005-13050f80-2a15-11ea-9be0-1fce15bf7f31.png)

**Comment by serviceproviderpk** [comment]
13) test whole app as visitor and make sure everthing is working fine.

**Comment by serviceproviderpk** [comment]
13) in edit profile display following fields with following sequence
a) First name
b) Last name
)Date of birth
) Email
) Phone

b) Designation
b) About me
c) city
e) Address
f) uploaded photo with upload buttton

**Comment by serviceproviderpk** [comment]
14) if user is not logged in he can view all list pages like

Picture of the week
SMS
poetry
golden words

**Comment by serviceproviderpk** [comment]
15) in add Expense show following fields
- Choose type (Income , Expense) 
- Description
- Amount
Save and cancel button
when type is income save amount ad + if expense save amount as -

in expense list show total in footer.
on top of the the list show date range so user can check balance with in date range

**Comment by serviceproviderpk** [comment]
16) in Create Todo List
show follwowing felds

Task Date
Description

and save cancel button

**Comment by serviceproviderpk** [comment]
17) http://fun2fresh.com/Map/MyMeeting 
a) in create meeting show
Meeting Date
Description

Save & Cancel button

b) and list of meeting show delet button
http://fun2fresh.com/Map/ShowMyMeeting

**Comment by serviceproviderpk** [comment]
@Muhammadkhalid66  we need to complete above feedback today in all cases. there is nothing new. just like simple CRUD

**Comment by Muhammadkhalid66** [comment]
12. change to "Picture of the week" on landing page .

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
6- http://fun2fresh.com/Map/ToDoList
a) hide Task Type Fix
b) show

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
17-http://fun2fresh.com/Map/MyMeeting
a) in create meeting show Fix
Meeting Date
Description
Save & Cancel button Sir we Submit and Cancel all pages Fix

b) and list of meeting show delet button Fix

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
16-in Create Todo List
show follwowing felds  Fix  
Task Date
Description

and save cancel button  Fix


@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
13-n edit profile display following fields with following sequence  Fixed
a) First name
b) Last name
)Date of birth
) Email
) Phone
b) Designation
b) About me
c) city
e) Address
f) uploaded photo with upload buttton   


@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
10-http://fun2fresh.com/Map/ShowHandiCrafts
display category in footer  Fix
in create screen show following fiedls  Fix
a) Choose category  
b)Description
c) Choose image
Save and Cancel button remove other fields

in list of handicraft display
Posted by: last name   Fix

[Note]: there is no datetime column found in DB 

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
14-if user is not logged in he can view all list pages like
Picture of the week Fix
SMS Fix 
poetry Fix
golden words  Fix

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
change all create and edit screens button text save and cancel Fix

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
add created date in handicraft DB and show on handicraft posted on and posted by in respective screen. Fix 

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
9-on create poetry show following fileds only Fix 
a) choose category
b)Description
c)Choose Image

Save and Cancel button Fix


@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
7-http://fun2fresh.com/Map/ShowGoldenWords
a) in footer display Posted by: last name Posted on: Date time Fix
b) Display category button below the pages and rename it to "Browse by category" Fix

@serviceproviderpk
