### ISSUE TITLE
EMS Software

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#23]

**Comment by serviceproviderpk** [comment]
1) if a branch is selected, replace "Select Branch" with "Actual branch name"

**Comment by serviceproviderpk** [comment]
5- left top bottom space s'd be same as 
![image](https://user-images.githubusercontent.com/19146254/36630743-2490c766-198d-11e8-907d-b74813c3c685.png)
6) on crud spacing sh'd be same as 
![image](https://user-images.githubusercontent.com/19146254/36630752-4605d2ba-198d-11e8-9492-5c7c1e8b65c5.png)

**Comment by serviceproviderpk** [comment]
1) Please add forgot password and register button and functionality(**fixed**)
2) On Login page also add logo of "EMS"(**fixed**)
3) Also maintain Login hisotry, it will help how many users are logged and using demo.ems.com(**fixed**)
4) info@EducationManagementSystem.net this email is working?
5) in "SystemDefaultSettings" add new field "SMSAPIURL" (**fixed**)
6) Tables in database which are not used. remove them please carefully, before removing create a list show share with team.(**fixed**)
7) admin of demo will be "info@educationmanagementsystem.net" instead of "admin@admin.com"
any time we can reset/forgot passwrod option.(**fixed**)
8) If user is logged in and choose any branch , branch name sh'd be selected and display in dropdown(**fixed**)
![image](https://user-images.githubusercontent.com/19146254/36881844-3e65f22e-1df2-11e8-8043-208484973dcc.png)
9) Please show tool tip and remove "Registeration alert " from these icons
![image](https://user-images.githubusercontent.com/19146254/36881894-84d4ed82-1df2-11e8-80ed-224fb0541648.png)
10) Rename "FrontEnd Website" with "Website"(**Fixed**)
11) remove extra space(top,left,right,bottom) , keep space of minimum 5px-10px(**Fixed**)
![image](https://user-images.githubusercontent.com/19146254/36882068-87708d70-1df3-11e8-9ee1-25bf6b2728cc.png)
12) please remove extra space(**Fixed**)
![image](https://user-images.githubusercontent.com/19146254/36882099-b478ff28-1df3-11e8-896d-8bf25f101ab7.png)
13) Every page sh'd have proper "Heading, BreadCrumb"  **[in all pages!!!]**

**Comment by serviceproviderpk** [comment]
14. use higlighted button in all over the system for "Save" and Cancel(**Fixed**)
![image](https://user-images.githubusercontent.com/19146254/36882414-877b4740-1df5-11e8-92a5-8a26685555e5.png)


15. in Quick links  add one more link "Reports"
when user will click on it. we will show report, module name, name,Description, in a grid, when user will click on relevent report will be displayed.
i think rizwan has already created this table if not

a) RPT_Module Table: "ModuleName,ModuleDescriptin"(**Fixed**)

b)RPT_Reports: ModuleId,ReportName,Descriptions,Parameters,OtherDetails, URL(**Fixed**)


16) use tool tip for "Refresh,Add, Quick Add" 
17) Remove  hyperlink class from tab text, also use diffrent icon for  terminate and stuck off
![image](https://user-images.githubusercontent.com/19146254/36882571-7caa4d56-1df6-11e8-8fbf-e9075abe9b18.png)
17) remove these type of filters from all screen, just add which are used in "Manage Enquiry"(**Fixed**)

![image](https://user-images.githubusercontent.com/19146254/36882639-dccc1cb4-1df6-11e8-863d-e432bed673b3.png)
18) Please change fa fa icon those are highlighted
![image](https://user-images.githubusercontent.com/19146254/36882687-2b08cc74-1df7-11e8-8244-080f70ef6b51.png)
19) Add copy rights in footer as below

**Comment by serviceproviderpk** [comment]
21) From menu bar remove left padding and  text sh'd be in one row in all menus.
![image](https://user-images.githubusercontent.com/19146254/36882769-a5eb775c-1df7-11e8-9ebb-c1f0d98b8069.png)(**Fixed**)

**Comment by adilshehbaz** [comment]
8.If user is logged in and choose any branch , branch name sh'd be selected and display in dropdown **(Fixed)**
2.On Login page also add logo of "EMS" **Fixed**
3. Please show tool tip and remove "Registeration alert " from these icons **fixed**
19-  Add copy rights in footer as below **fixed**

**Comment by khalidjavaid** [comment]
[](url)
