### ISSUE TITLE
PM Initial Feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#248]

**Comment by serviceproviderpk** [comment]
1) **Fixed** in all pages find "School Management Software" and replace with "Paper Maker"
2) remove the item which are crossed in picture.
![image](https://user-images.githubusercontent.com/19146254/76374350-c61ead00-6364-11ea-87b8-4fe919acb598.png)

**Comment by serviceproviderpk** [comment]
3)**Fixed** Use same layout page for Login/Forget Password and Register page
Logo, background-color and section color will be set in layout page. 
b)text boxes and page heading will be in inner page

Note! Please discuss it with me.

**Comment by serviceproviderpk** [comment]
4) **fixed** change left menu and top related to below picture use same color and same icons
![image](https://user-images.githubusercontent.com/19146254/76375561-f3208f00-6367-11ea-8e48-0063258d340a.png)

**Comment by serviceproviderpk** [comment]
5) **fixed** Create a new page, with name "Account Details"
when any type of user is logged redirect him him "Account Details page. that will have following looking and feel
![image](https://user-images.githubusercontent.com/19146254/76375739-662a0580-6368-11ea-9662-87cc73af7e85.png)

**Comment by serviceproviderpk** [comment]
6) **fixed**
![image](https://user-images.githubusercontent.com/19146254/76491099-b5e2fc80-644e-11ea-82e2-eaa86641b8be.png)

a) Change "Students" to Publisher
b) Change Emploee to "Staff"
c) Sessions "Classes"
fix

**Comment by serviceproviderpk** [comment]
7) **fixed** remove below menu items
![image](https://user-images.githubusercontent.com/19146254/76491220-03f80000-644f-11ea-8491-3f1c90a905b5.png)
fix

**Comment by serviceproviderpk** [comment]
8) **fixed**
![image](https://user-images.githubusercontent.com/19146254/76491338-44577e00-644f-11ea-9026-b06a5767b960.png)
fix

**Comment by serviceproviderpk** [comment]
9)**fixed** remove "Web Portal" from menu
also remove from available rights   
fix

**Comment by serviceproviderpk** [comment]
10)  "Help "
Account/NeedHelp
from every things form this page.

and text display following things

How Paper Maker Can be used?

Publisher
Classes
Subjects
Chapters
and so on...

**Comment by serviceproviderpk** [comment]
11)**fixed** Manage Publisher

a) on add/edit remove password text box
b)remove this line
![image](https://user-images.githubusercontent.com/19146254/76491917-b2507500-6450-11ea-8bb4-e655f15d9acf.png)
c) check spelling of resentidals
d) IsActive will be "Cheked by default
fix

**Comment by serviceproviderpk** [comment]
12)**fixed** Published list display following columsn
a) Created Date,Publihser Id,Name,Registration Number,Email,Mobile Number
Fix

**Comment by serviceproviderpk** [comment]
13) **fixed** in Account details change icons

- 1) My Accounts "Edit Profile"
- 2) Dashboard to "Account Details"
- 3) My Contacts to "Subjects"
- 4) "Order Now" to  "Chapters"
- 5) Favorite icons to"Topics"
- 6) Services to "Generate Paper"
**************************Fixed******************

**Comment by serviceproviderpk** [comment]
14)**fixed** Change favicon and logo 

![image](https://user-images.githubusercontent.com/19146254/76493247-06108d80-6454-11ea-8b82-5cdbbefb5ec1.png)
****************************Fiixed*****************************************
![FavIcons](https://user-images.githubusercontent.com/46710856/77069427-38992800-6a0a-11ea-876b-e0f9ca097167.PNG)

**Comment by serviceproviderpk** [comment]
15)** fixed** in grids, show latest record on top

**Comment by serviceproviderpk** [comment]
16) **not fixed** Save color blue and Cancel button color red in all screens

**Comment by serviceproviderpk** [comment]
17)**fixed** on Create Questions, if choose chapter show related Topic ONLY

**Comment by serviceproviderpk** [comment]
18) **fixed** on Paper configation show relted page heading, sub heading and  "Add new"button

**Comment by serviceproviderpk** [comment]
19) **fixed** show logo on login,forget passowrd
20) remove "Try free demo"
![image](https://user-images.githubusercontent.com/19146254/76596416-f0689a00-651f-11ea-83e1-f7d2679874d5.png)

**Comment by serviceproviderpk** [comment]
21)**fixed**  When user is logged in redirect on this page

http://beta.papermaker.biz/Home/AccountDetails

and show data form database
![image](https://user-images.githubusercontent.com/19146254/76596532-37568f80-6520-11ea-955d-9bc1f67f6024.png)

**Comment by serviceproviderpk** [comment]
22)**fixed** remove this section
![image](https://user-images.githubusercontent.com/19146254/76596819-ea26ed80-6520-11ea-9158-534a30d63ad3.png)

**Comment by serviceproviderpk** [comment]
23)**fixed** remove these
![image](https://user-images.githubusercontent.com/19146254/76596905-19d5f580-6521-11ea-8698-70c5a2bbd7ef.png)

**Comment by serviceproviderpk** [comment]
24) **fixed** when user click on "?"
Please create a page on that page show all steps that we need to use this portal
![image](https://user-images.githubusercontent.com/19146254/76596970-4558e000-6521-11ea-8b23-6c56c5642480.png)

**Comment by serviceproviderpk** [comment]
25)**fixed** add page heading and breadcurmb and sub heading etc
![image](https://user-images.githubusercontent.com/19146254/76597131-8d780280-6521-11ea-8da6-574d45b7ba20.png)

**Comment by serviceproviderpk** [comment]
26)**fixed** please add logo in our local database, and change all settings

then re-upload code and restore database on server

**Comment by sppk** [comment]
27)In paper Configuration
Manage question
a)edit screen must show relative list accoroding to question
b)don't increase list items automatically

**Comment by serviceproviderpk** [comment]
28) if i am logged in as admin, i sh'd be ability to add/edit session

**Comment by serviceproviderpk** [comment]
29) **fixed** i was logged on branch, after logged in, I shd be able to see my  publiser,class,paper,chapter,topic etc.

**Comment by serviceproviderpk** [comment]
30) **not fixed** Quick access 
![image](https://user-images.githubusercontent.com/19146254/76704932-2794a200-66fe-11ea-9794-6e5a0942d292.png)

only show following links


    a) PAPER CONFIG
    b) GENRATE PAPER
c) Reports

**Comment by serviceproviderpk** [comment]
31)**Not Fixed** Edit Profile
"Disable link of "Account details
b) remove signature
![image](https://user-images.githubusercontent.com/19146254/76705015-a7bb0780-66fe-11ea-9eed-2fea795dacd5.png)

**Comment by serviceproviderpk** [comment]
32) remove school software logo from code and datbase.
on invalid or session null i see school software logo

**Comment by serviceproviderpk** [comment]
33) **Not Fixed** in All screen in which are using *
show place holder
example for phone:  e.g 0331 4769553

Email  e.g youremail@domain.com

**Comment by serviceproviderpk** [comment]
34)**Not Fixed** remove "IsActive" from all classes
from backend we will set IsActive=1 for all tables

![image](https://user-images.githubusercontent.com/19146254/76705486-2ebdaf00-6702-11ea-86b8-6287a80afa14.png)

b) in all tables add "IsDeleted" if missing in any table.
when record will be saved we will set it as 0

and will add Delete btutton, that will do soft deletion

in grid we will add Delete button

**Comment by serviceproviderpk** [comment]
35)**Not Fixed** Chapter list shd be selected of choosed subject right now its dislaying all

i choosed "HTML" it is displaying chapter of all books
![image](https://user-images.githubusercontent.com/19146254/76705757-21092900-6704-11ea-81f1-f27b177e2a5c.png)
******************************Fixed****************************************

**Comment by serviceproviderpk** [comment]
36) Configure a paper with sample data

**Comment by serviceproviderpk** [comment]
37)**Not Fix** move button on top 
![image](https://user-images.githubusercontent.com/19146254/76705857-169b5f00-6705-11ea-8cd2-a6f4bca69951.png)

**Comment by serviceproviderpk** [comment]
38) Not Fixed show "Save Paper", "Print Paper"  "Back" show on right side

![image](https://user-images.githubusercontent.com/19146254/76705946-c83a9000-6705-11ea-9cc7-e2efe053635c.png)

**Comment by serviceproviderpk** [comment]
39) add link and  display Saved paper

**Comment by serviceproviderpk** [comment]
40) Set page header and footer same as given in sample paper

**Comment by serviceproviderpk** [comment]
41)**Fixed** REMOVE THIS LOGO FORM THIS PATH
http://beta.papermaker.biz/img/logo.png

AND USE NEW ONE.

STILL ISEE THIS ON LOGIN PAGE if enter invalid user name and password

![image](https://user-images.githubusercontent.com/19146254/76706647-da6afd00-670a-11ea-92a5-350d55a8e51a.png)

***************************************Fixed************************************
![logo](https://user-images.githubusercontent.com/46710856/77069178-c0cafd80-6a09-11ea-9252-596574512b9d.PNG)
