### ISSUE TITLE
SaudiPhone

### ISSUE THREAD

**Issue by adilshehbaz** [serviceproviderpk/sp.pk#25]
0) When user click on "Mobile Phones"
a) show list of Mobile phone category only
b) next menu will be "Apple" , Samsung, Nokia, Huwai, LG
move search section on top or near banner
c) Tablets
d) Laptops > show its all category

**Comment by adilshehbaz** [comment]
1- Menu Setting 
![menu](https://user-images.githubusercontent.com/28675602/37447058-f6e6edfe-2841-11e8-9bda-c35075a0b256.png)

**Comment by adilshehbaz** [comment]
2- BeardCrumb and Title of Product in same row and also same colour...push breadcrumb to right corner
![menu](https://user-images.githubusercontent.com/28675602/37447084-2eac0062-2842-11e8-83e3-957d2517a992.png)

**Comment by adilshehbaz** [comment]
3- Logo Height reduce to 65px
![menu](https://user-images.githubusercontent.com/28675602/37447100-4a346c84-2842-11e8-894c-3aecfc62a8cb.png)

**Comment by adilshehbaz** [comment]
4- Size of Mobile to big
![menu](https://user-images.githubusercontent.com/28675602/37447109-6225de2c-2842-11e8-901c-0d33e1b02120.png)

**Comment by adilshehbaz** [comment]
5- **(Fixed)** Remove this space from home page or show any type of mobiles on this
![menu](https://user-images.githubusercontent.com/28675602/37447138-8c5f863e-2842-11e8-8ced-749c083678e0.png)

**Comment by adilshehbaz** [comment]
6- Change bread crumb and title on mobiles list
![menu](https://user-images.githubusercontent.com/28675602/37447244-fd14bff2-2842-11e8-9272-104e4b51c949.png)

**Comment by adilshehbaz** [comment]
7- Show All categories of mobiles and make some special links
![menu](https://user-images.githubusercontent.com/28675602/37447404-cb8ea672-2843-11e8-884c-adb3f0c9bff7.png)

**Comment by adilshehbaz** [comment]
8- First foter showing href link other are not...remove from first
![menu](https://user-images.githubusercontent.com/28675602/37447431-eaaeeb3e-2843-11e8-8c99-1c5d633a0f19.png)

**Comment by adilshehbaz** [comment]
9- Show any link here
![menu](https://user-images.githubusercontent.com/28675602/37447445-fb3623f0-2843-11e8-8178-4f4cb55c8e2a.png)

**Comment by adilshehbaz** [comment]
10- Looking very ajeeeb
![menu](https://user-images.githubusercontent.com/28675602/37447482-1be79598-2844-11e8-94a8-b3a3a5b51096.png)

**Comment by adilshehbaz** [comment]
11- Remove this
![menu](https://user-images.githubusercontent.com/28675602/37447506-372883e4-2844-11e8-9f49-343a477749a5.png)

**Comment by adilshehbaz** [comment]
12- top margin
![menu](https://user-images.githubusercontent.com/28675602/37447527-5182b8f4-2844-11e8-96f8-5ff889351da2.png)

**Comment by serviceproviderpk** [comment]
**Sir please explain it**
will add all category as below
![image](https://user-images.githubusercontent.com/19146254/39099665-d3a0fce4-4697-11e8-9232-8403197a172e.png)

**Comment by serviceproviderpk** [comment]
in footer add link  "Mobile by City"

a) show city  name in a list
b) city details

CityId,CityName,Description,Photo,SNO
