### ISSUE TITLE
Fun2fresh March202020

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#250]

**Comment by serviceproviderpk** [comment]
1) if any one visit website , it shd open this page
  http://fun2fresh.com/map/index

**Comment by serviceproviderpk** [comment]
2) add new link in menu bar
"Members"
display list of member latest on top

**Comment by serviceproviderpk** [comment]
3) add these link after every item
![image](https://user-images.githubusercontent.com/19146254/77142995-9f1e5480-6aa3-11ea-9e97-e9c70f7f3777.png)

**Comment by serviceproviderpk** [comment]
4) if user open website in brwoser on top show image of andrdid app
if user click on this redirect user app link in play store
https://play.google.com/store/apps/details?id=com.fun2fresh.fun_fresh

**Comment by serviceproviderpk** [comment]
5) dislay category like this

![image](https://user-images.githubusercontent.com/19146254/77154567-c5e98480-6abd-11ea-801c-272262f78f3e.png)

**Comment by ranahassaan1** [comment]
f any one visit website , it shd open this page
http://fun2fresh.com/map/index FIX
@sppk

**Comment by ranahassaan1** [comment]
add new link in menu bar
"Members"
display list of member latest on top FIX

**Comment by sppk** [comment]
6) change  poetry  to health

**Comment by sppk** [comment]
7)add news section
show news  from rss of dunya and bbc urdu

**Comment by ranahassaan1** [comment]
ACK

**Comment by ranahassaan1** [comment]
7)add news section
show news from rss of dunya and bbc urdu 
can you please explain this task

**Comment by ranahassaan1** [comment]
4.  if user open website in brwoser on top show image of andrdid app
if user click on this redirect user app link in play store
https://play.google.com/store/apps/details?id=com.fun2fresh.fun_fresh FIx

**Comment by ranahassaan1** [comment]
5.dislay category like this FIX

**Comment by sppk** [comment]
6)its must be in one line
![image](https://user-images.githubusercontent.com/47495376/77880723-31b5b500-7255-11ea-8955-db3994e1a2f1.png)

**Comment by sppk** [comment]
7)After Logged in
1)Go to members =>Click on Sheraz but I show Hassan profile
2)the info of members is also disturb
![image](https://user-images.githubusercontent.com/47495376/77881266-83ab0a80-7256-11ea-8328-bceaa1d97648.png)
![image](https://user-images.githubusercontent.com/47495376/77881290-93c2ea00-7256-11ea-9c1c-676115471172.png)

**Comment by ranahassaan1** [comment]
6)sign up=>its must be in one line FIX

**Comment by ranahassaan1** [comment]
7)After Logged in
1)Go to members =>Click on Sheraz but I show Hassan profile( it is static page it will connected with database)
2)the info of members is also disturb Fix

**Comment by sppk** [comment]
8)spelling mistake
 perority to priority
![image](https://user-images.githubusercontent.com/47495376/78981703-ebf0ca80-7b39-11ea-83e4-9e501b30bbc5.png)

**Comment by sppk** [comment]
9)How to set time in Meeting
   By Default its show 12:00AM
![image](https://user-images.githubusercontent.com/47495376/78982193-0aa39100-7b3b-11ea-9ba2-979f77a36e09.png)

**Comment by sppk** [comment]
10)On every Deatail page
     Delete must show alert Notification "Are you sure to Delete"
![image](https://user-images.githubusercontent.com/47495376/78982350-62da9300-7b3b-11ea-94ef-e5d63f7ead8c.png)

**Comment by sppk** [comment]
11) change Add button
![image](https://user-images.githubusercontent.com/47495376/78982684-1ba0d200-7b3c-11ea-909a-5a9ae6a46b83.png)
![image](https://user-images.githubusercontent.com/47495376/78982737-2f4c3880-7b3c-11ea-9484-0beb8bedd059.png)

**Comment by sppk** [comment]
12)Remove Time from every page only date shown
![image](https://user-images.githubusercontent.com/47495376/78982927-94a02980-7b3c-11ea-9f12-ed7e20d46512.png)

**Comment by sppk** [comment]
13)Poetry Detail page Disturb
     set all the UI of Poetry
![image](https://user-images.githubusercontent.com/47495376/78983058-e0eb6980-7b3c-11ea-8157-55eee6347bd0.png)

**Comment by sppk** [comment]
14)I am already login but when I add poetry then it  redirect to login page
![image](https://user-images.githubusercontent.com/47495376/78983233-417aa680-7b3d-11ea-8cf9-d6399bbbd9be.png)

**Comment by sppk** [comment]
15)Picture of the weak is Empty page Not in working
![image](https://user-images.githubusercontent.com/47495376/78983570-e8f7d900-7b3d-11ea-8a9b-277b2af3b27b.png)

**Comment by ranahassaan1** [comment]
11.change Add button FIX

**Comment by ranahassaan1** [comment]
13.Poetry Detail page Disturb
set all the UI of Poetry FIX

**Comment by sppk** [comment]
13)picture of the week
http://fun2fresh.com/Map/showPhotos
If We Dislike the picture
then we also have access to Like again on same picture
and previous Dislike is remove 
![image](https://user-images.githubusercontent.com/47495376/79418785-e2021800-7fce-11ea-9637-4a2eff530249.png)

**Comment by sppk** [comment]
14)Time Table
There is no Edit and Delete Option
Also you add notification option on daily basis
![image](https://user-images.githubusercontent.com/47495376/79419222-d82ce480-7fcf-11ea-9a0c-521403a25fa5.png)

**Comment by sppk** [comment]
15)Members
http://fun2fresh.com/Map/Members
Remove all previous data of Members from Database
Also add pagination 
![image](https://user-images.githubusercontent.com/47495376/79419579-83d63480-7fd0-11ea-93e8-4355223e1869.png)

**Comment by sppk** [comment]
16) Member Detail Page
http://fun2fresh.com/Map/MembersDetail/10095
Use Diferent color for Name 
![image](https://user-images.githubusercontent.com/47495376/79419917-38705600-7fd1-11ea-92fc-b3ce0e73ac61.png)

**Comment by sppk** [comment]
17)Golden Words
http://fun2fresh.com/Map/ShowGoldenWords?catid=14
Posted By:______________ it must be in one line
if not set in one line
Please adjust it as looking good
![image](https://user-images.githubusercontent.com/47495376/79420274-0f9c9080-7fd2-11ea-985f-6b823fe5f1da.png)

**Comment by sppk** [comment]
18)News
work also on News Section.
it is not in working
http://fun2fresh.com/Map/News
![image](https://user-images.githubusercontent.com/47495376/79421760-e8938e00-7fd4-11ea-9b88-0d0c1290381b.png)

**Comment by serviceproviderpk** [comment]
19) remove extra spaces plz 
![image](https://user-images.githubusercontent.com/19146254/79436202-00c1d800-7fea-11ea-9317-064aac53836b.png)

rename "Create Time Table" with "Manage Time Table"

**Comment by serviceproviderpk** [comment]
20) Remove my meeting link from dashboard and left menu
21) MY Dashobard will display link with follow sequence

 To DO List, Time Table,  My Expenses
Golden Words, SMS , Poetry, Picture of the Week, Handicraft,

**Comment by serviceproviderpk** [comment]
22) Change  "My Account" with "Time Table"
![image](https://user-images.githubusercontent.com/19146254/79438913-990d8c00-7fed-11ea-9715-1a5da058a93d.png)

**Comment by sppk** [comment]
23)
http://fun2fresh.com/Map/Index
Remove Extra space
![image](https://user-images.githubusercontent.com/47495376/79628017-8ebad180-8156-11ea-9d14-e303ef6a6d36.png)

**Comment by sppk** [comment]
24)
Remove Extra space
![image](https://user-images.githubusercontent.com/47495376/79628056-05f06580-8157-11ea-8936-f9083c361d3e.png)

**Comment by sppk** [comment]
25)Dashboard 
Mobile view
![image](https://user-images.githubusercontent.com/47495376/79628196-4c928f80-8158-11ea-8107-d978f942f7db.png)
![image](https://user-images.githubusercontent.com/47495376/79628215-659b4080-8158-11ea-8f53-c901fd11ca11.png)

**Comment by sppk** [comment]
26)Fun2Fresh
ITS ONLY PLACE THAT KEEPS YOU FRESH
Add same margin from top and bottom
![image](https://user-images.githubusercontent.com/47495376/79628354-ae9fc480-8159-11ea-986c-460a8b20247f.png)

**Comment by sppk** [comment]
25)please set its location
![image](https://user-images.githubusercontent.com/47495376/79941539-fb4b0e80-847d-11ea-9c15-92e9ee02461f.png)
http://fun2fresh.com/Map/GoldenWordsDetails/32?catid=14

**Comment by sppk** [comment]
26)In a Mobile view
please change pop up 
choose best one
![image](https://user-images.githubusercontent.com/47495376/79941661-3f3e1380-847e-11ea-919a-4fd08f7313a4.png)
http://fun2fresh.com/Map/GoldenWordsDetails/32?catid=14

**Comment by sppk** [comment]
27)Edit screen
![image](https://user-images.githubusercontent.com/47495376/79941798-8e844400-847e-11ea-986b-2716f17580d6.png)

**Comment by sppk** [comment]
28) How to delete Golden word

**Comment by sppk** [comment]
29)please add validation on add choose image
when choose incorrect file the it validate

**Comment by sppk** [comment]
30)change location of add button
![image](https://user-images.githubusercontent.com/47495376/79942124-8973c480-847f-11ea-96a1-00126ab92eec.png)

**Comment by serviceproviderpk** [comment]
31) Full row must be clickable
![image](https://user-images.githubusercontent.com/19146254/79948461-55070500-848d-11ea-86de-a30d4ec86dd8.png)
32) in top of first add link of "My Bookmarking"

**Comment by serviceproviderpk** [comment]
33) in every section add 2 records and for category add proper description show that it can  give some good look.

**Comment by serviceproviderpk** [comment]
34)  if i click on below link 
![image](https://user-images.githubusercontent.com/19146254/79950870-2723bf80-8491-11ea-83f6-ef84c91c7871.png)

getting error

![image](https://user-images.githubusercontent.com/19146254/79950826-12dfc280-8491-11ea-8c7c-28efcb3e3624.png)

**Comment by serviceproviderpk** [comment]
35) use color schme for "Action" as you are using previous and next button

**Comment by serviceproviderpk** [comment]
36) Forget Password and create Account padding must be 10px from bottom and top

![image](https://user-images.githubusercontent.com/19146254/79952344-b7630400-8493-11ea-8232-7c08f10cbed1.png)

**Comment by serviceproviderpk** [comment]
37) Priorty must be on right side
![image](https://user-images.githubusercontent.com/19146254/79952505-f8f3af00-8493-11ea-89b3-57df6aa79d33.png)

**Comment by serviceproviderpk** [comment]
38) remove this button
![image](https://user-images.githubusercontent.com/19146254/79952554-0a3cbb80-8494-11ea-8200-1bbd842edc52.png)

**Comment by serviceproviderpk** [comment]
40) on detail page "Action" but shd be in proper working form
39) Book marking list
show latest on top

and use some meaning title of book marking

![image](https://user-images.githubusercontent.com/19146254/79952744-4ff98400-8494-11ea-859c-c498e681192a.png)

right now title is "Details"

**Comment by serviceproviderpk** [comment]
40) do category, list page and detail page same as we did for Golden words

**Comment by serviceproviderpk** [comment]
41) text shd be in center
![image](https://user-images.githubusercontent.com/19146254/79957902-b6ce6b80-849b-11ea-896b-5dbabffcb85c.png)
and make it bold

**Comment by sppk** [comment]
42)Handicraft/Goldenwords
Add button not shown in mobile view
and in Desktop add button is out of mobile
http://fun2fresh.com/Map/ShowGoldenWords?catid=14
![image](https://user-images.githubusercontent.com/47495376/79975364-4aac3180-84b4-11ea-836d-4e05e83aa05e.png)

**Comment by sppk** [comment]
43)
I am logged in user
Handicraft=>click on add button
its again and again redirect to login form
![image](https://user-images.githubusercontent.com/47495376/79975722-db830d00-84b4-11ea-8b88-2f46d3711248.png)

**Comment by sppk** [comment]
44)Picture of the Week
Desktop
http://fun2fresh.com/Map/showPhotos

**Comment by sppk** [comment]
45)
Forgot password? are start where button Start
Create Account? End where button End
![image](https://user-images.githubusercontent.com/47495376/80182478-6cc2c280-8620-11ea-97ad-d42f51c8ee25.png)

**Comment by sppk** [comment]
46)All pages not complete show on Different Devices 
Please add scroll bar

**Comment by sppk** [comment]
47)Priority must be on right side
![image](https://user-images.githubusercontent.com/47495376/80183301-050d7700-8622-11ea-8e6b-76e057aa1cb6.png)

**Comment by sppk** [comment]
48)Golden Words
create page=>choose file 
I choose audio file and I surprise it begin to upload
Plz add validation
Only Images etc...upload 
![image](https://user-images.githubusercontent.com/47495376/80183746-d17f1c80-8622-11ea-9541-e90e8397a8df.png)

**Comment by sppk** [comment]
49)Handicraft,Picture of the and other pages apply validation 
 which type of file user can upload

**Comment by sppk** [comment]
50)SMS category must be in one line
http://fun2fresh.com/Map/Sms
![image](https://user-images.githubusercontent.com/47495376/80185703-3720d800-8626-11ea-9fef-cd659680c4f6.png)

**Comment by sppk** [comment]
SMS
How we can identify what is this?
Please show it in proper format?
You can use column Heading.
http://fun2fresh.com/Map/ShowSms
![image](https://user-images.githubusercontent.com/47495376/80185918-9d0d5f80-8626-11ea-8bb4-88092711bf03.png)

**Comment by sppk** [comment]
![image](https://user-images.githubusercontent.com/47495376/80186549-98957680-8627-11ea-9107-07831848154a.png)

**Comment by sppk** [comment]
Myprofile
add space from bottom 
scroll bar add
data show on top
![image](https://user-images.githubusercontent.com/47495376/80187110-82d48100-8628-11ea-872d-13938c71f59d.png)

**Comment by Muhammadkhalid66** [comment]
Myprofile
add space from bottom 
scroll bar add
data show on top
![image](https://user-images.githubusercontent.com/47495376/80187110-82d48100-8628-11ea-872d-13938c71f59d.png)

to 

![image](https://user-images.githubusercontent.com/41336284/80190583-fa58df00-862d-11ea-8035-5c34e1a0cfd1.png)


@serviceproviderpk

**Comment by serviceproviderpk** [comment]
01) Right , left  and top padding/spacing must be same in all screen
i will suggest leave space empty 5px

![image](https://user-images.githubusercontent.com/19146254/80266724-d42b5180-86b6-11ea-8ac2-109d97d21d7a.png)

**Comment by serviceproviderpk** [comment]
2) My Dashobard
http://fun2fresh.com/Map/Dashboard

remove extra section
![image](https://user-images.githubusercontent.com/19146254/80266883-bf9b8900-86b7-11ea-8f9a-f7dfbf389ec8.png)

**Comment by serviceproviderpk** [comment]
3) after home add new menu "Dashboard"
when user click on it show user Dashobard
![image](https://user-images.githubusercontent.com/19146254/80266940-1acd7b80-86b8-11ea-9272-8dd1dfd22ba1.png)

**Comment by serviceproviderpk** [comment]
4)  in Dashboard" after the Handi Craft
display heading "My Profile" and show all link those are added in my Settings

My Settings
  My Profile
  Edit Profile
  Change Password

**Comment by serviceproviderpk** [comment]
5) on Home page and Dashboard  give 5px space from top.left and right

**Comment by serviceproviderpk** [comment]
6) Below the heading add this line

"Upload any Natural picture that is captured from your cell phone, If your  picture have more likes, You will get  amazing gift from f2fresh Team. Click here to Upload"

Clik

![image](https://user-images.githubusercontent.com/19146254/80267104-e7d7b780-86b8-11ea-8d6d-6469ab30b16e.png)

**Comment by serviceproviderpk** [comment]
7) Change "Week" with Month

"Picture of the Month"
"Last Month" and "Old"

**Comment by serviceproviderpk** [comment]
8) add last tab as "Winner" only show the picutre that is makred as winner
display following details of the user

Full Name, City, Country

**Comment by serviceproviderpk** [comment]
9) Home and Dashobard make sure   if user click on part of the row. it must be clickable and redierect user to next page
![image](https://user-images.githubusercontent.com/19146254/80267425-46516580-86ba-11ea-855e-c9889be224a7.png)

**Comment by serviceproviderpk** [comment]
10) Improve page heading and font as welll
![image](https://user-images.githubusercontent.com/19146254/80267450-726ce680-86ba-11ea-9870-edc13c4a5cf0.png)

**Comment by serviceproviderpk** [comment]
Book marking not working in  Poetry and Golden words, 

make sure it shd work in all details pages

**Comment by Muhammadkhalid66** [comment]
10: 

![image](https://user-images.githubusercontent.com/41336284/80271009-7149b280-86d6-11ea-95d6-be71fb4023b3.png)


change "my todo list" to    "todo list" and increase font size 9 to 11 px

**Comment by sppk** [comment]
11)picture of the week
cover space of tabs
![image](https://user-images.githubusercontent.com/47495376/80277472-9f47ea80-8708-11ea-8cac-9668b1103b82.png)

**Comment by sppk** [comment]
12)More section
Dashboard picture/Text not proper show
![image](https://user-images.githubusercontent.com/47495376/80277555-31e88980-8709-11ea-8692-26cf35e5676f.png)

**Comment by sppk** [comment]
13) Members
Name not readable
![image](https://user-images.githubusercontent.com/47495376/80277642-d66acb80-8709-11ea-99d3-2834e336a66c.png)

**Comment by sppk** [comment]
14)SMS
Add some space from right space
http://fun2fresh.com/Map/ShowSms?catid=1
![image](https://user-images.githubusercontent.com/47495376/80277762-b38ce700-870a-11ea-90f7-cb2b3e9a1d6a.png)

**Comment by Muhammadkhalid66** [comment]
2) My Dashobard
http://fun2fresh.com/Map/Dashboard fix

remove extra section
![image](https://user-images.githubusercontent.com/19146254/80266883-bf9b8900-86b7-11ea-8f9a-f7dfbf389ec8.png)


to 


![image](https://user-images.githubusercontent.com/41336284/80277958-0d41e100-870c-11ea-8a55-ecfacad9d551.png)


@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
11)picture of the week
cover space of tabs
![image](https://user-images.githubusercontent.com/47495376/80277472-9f47ea80-8708-11ea-8cac-9668b1103b82.png)

to 

![image](https://user-images.githubusercontent.com/41336284/80278150-4dee2a00-870d-11ea-990f-73c65f6d0f31.png)

fix 
@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
![image](https://user-images.githubusercontent.com/41336284/80278284-6579e280-870e-11ea-8f41-591fb2830b2e.png)


fix 

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
3- 

![image](https://user-images.githubusercontent.com/41336284/80278677-be974580-8711-11ea-9083-049c35953a56.png)

fix 

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
![image](https://user-images.githubusercontent.com/41336284/80279138-02d81500-8715-11ea-82f2-da16a5993349.png)
  fix margin left right, top 5px 

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
![image](https://user-images.githubusercontent.com/41336284/80279185-4cc0fb00-8715-11ea-877d-d10fde8cbb53.png)
Fix 

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
12- more action   fix

![image](https://user-images.githubusercontent.com/41336284/80279218-7843e580-8715-11ea-8e45-070171cc2df4.png)


@serviceproviderpk

**Comment by sppk** [comment]
My Profile,My interest and My setting
All text must be clickable
![image](https://user-images.githubusercontent.com/47495376/80280901-b0045a80-8720-11ea-8d21-22fd11f8dffc.png)

**Comment by serviceproviderpk** [comment]
1) My Dashboard

a) remove this section
![image](https://user-images.githubusercontent.com/19146254/80295695-533f8900-878e-11ea-9e5d-e2c557f995ad.png)
b) Change "Dashboard:" to "My Dashboard" and text must be in center of the page
c) Also add new item "My Bookmarking"

**Comment by serviceproviderpk** [comment]
7)  "+" button position must be  right bottom as we already discussed and approved it.
in may mobile i see this in "Center of the" mobile screen bottom
8) Footer menu overlapping in my mobile, if this is due to number of menu size then you can rmeove
"Time Table" link from the bottom menu bar.

**Comment by serviceproviderpk** [comment]
9) Improve page heading in all pages. its not looking good.
![image](https://user-images.githubusercontent.com/19146254/80295863-d3b2b980-878f-11ea-81c8-520cdbfbfc97.png)

**Comment by serviceproviderpk** [comment]
10) "make it as link" when user click on it open page that we are using to submit picture
![image](https://user-images.githubusercontent.com/19146254/80295879-fe9d0d80-878f-11ea-8011-e1444a158f68.png)

**Comment by serviceproviderpk** [comment]
11) As  "news" is not in working form remove it from the left menu bar
12)  "Members" menu will be visible ONLY Admin

**Comment by serviceproviderpk** [comment]
13) @Muhammadkhalid66  Please test above task in your cell phone after fixing

**Comment by serviceproviderpk** [comment]
14) Please check in all code and latest db Send me published version with DB script
i will upload on someother domains it make it live

**Comment by serviceproviderpk** [comment]
14) Flush dummy data from all sections except "To do list"
and add 2 entry in each section

**Comment by serviceproviderpk** [comment]
15) Add captha on register  page

**Comment by Muhammadkhalid66** [comment]
11-As "news" is not in working form remove it from the left menu bar fix 
12-"Members" menu will be visible ONLY Admin fix

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
10: Change Picture of the Week with "Picture of the Month" in all lablesl fix 
"make it as link" when user click on it open page that we are using to submit picture Fix 

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
9-Improve page heading in all pages. its not looking good. fix

![image](https://user-images.githubusercontent.com/41336284/80348080-b14f9780-8886-11ea-91ce-a498506ce6a8.png)


@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
7-"+" button position must be right bottom as we already discussed and approved it.
in may mobile i see this in "Center of the" mobile screen bottom  fix
8-Footer menu overlapping in my mobile, if this is due to number of menu size then you can rmeove
"Time Table" link from the bottom menu bar.  fix

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
6-My Dashboard
a) remove this section

b) Change "Dashboard:" to "My Dashboard" and text must be in center of the page fix 
c) Also add new item "My Bookmarking" fix 

to 
![image](https://user-images.githubusercontent.com/41336284/80348516-566a7000-8887-11ea-990f-86c70b0ee29f.png)

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
3-Right , left and top padding/spacing must be same in all screen
i will suggest leave space empty 5px fix 
@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
4-in Dashboard" after the Handi Craft
display heading "My Profile" and show all link those are added in my Settings
My Settings
My Profile
Edit Profile
Change Password  fix 
![image](https://user-images.githubusercontent.com/41336284/80350404-1d7fca80-888a-11ea-8a8a-dbdc41095840.png)

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
2-  Fix
![image](https://user-images.githubusercontent.com/41336284/80350574-6041a280-888a-11ea-933e-03256fd0f33e.png)   

in all mobile devices 

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
1)spelling mistake
perority to priority  fix 

![image](https://user-images.githubusercontent.com/41336284/80350742-9da63000-888a-11ea-9e36-2aec6c74f4fc.png)

@serviceproviderpk

**Comment by sppk** [comment]
http://fun2fresh.com/Map/ShowMyContact
![image](https://user-images.githubusercontent.com/47495376/80350925-e231cb80-888a-11ea-9c66-b8d10628a7b5.png)

**Comment by sppk** [comment]
full page not show
![image](https://user-images.githubusercontent.com/47495376/80352443-57060500-888d-11ea-9a26-e83a1a747a90.png)

**Comment by sppk** [comment]
please move Logout Button below
![image](https://user-images.githubusercontent.com/47495376/80360236-748c9c00-8898-11ea-8746-7a1611d43fe5.png)

**Comment by sppk** [comment]
When Edit Picture the week
http://fun2fresh.com/Map/GetPhotosByUserId
![image](https://user-images.githubusercontent.com/47495376/80361096-cc77d280-8899-11ea-846a-163df834b37e.png)

**Comment by sppk** [comment]
Handicraft Edit screen cancel button
http://fun2fresh.com/Map/GetHandiCraftsByUserId
![image](https://user-images.githubusercontent.com/47495376/80361348-342e1d80-889a-11ea-98da-8e0846d72e30.png)

**Comment by serviceproviderpk** [comment]
My Dasboard must be in center  reduce font size use same as you used in "Home"
![image](https://user-images.githubusercontent.com/19146254/80360401-b9183780-8898-11ea-8a1e-4aba14237fc5.png)

**Comment by serviceproviderpk** [comment]
2) in all page (ALL Category list,  page list, detail give 10px padding from left and right ( so that it border must be visible)
![image](https://user-images.githubusercontent.com/19146254/80360601-05637780-8899-11ea-87d1-ed70e3bdac86.png)

**Comment by sppk** [comment]
please increase the background 
![image](https://user-images.githubusercontent.com/47495376/80361662-c504f900-889a-11ea-8b95-b02250be5113.png)

**Comment by Muhammadkhalid66** [comment]
Handicraft Edit screen cancel button Fix
Poetry Edit screen cancel button  Fix
SMS Edit screen cancel button  Fix
Golden Words Edit screen cancel   Fix
Pic of the month Edit screen cancel button  Fix

@serviceproviderpk

**Comment by Muhammadkhalid66** [comment]
15-Add captha on register page Fix

@serviceproviderpk

**Comment by sppk** [comment]
1)Whenever we add Book reading the Time 12:00 AM show
Please remove this time/Exact time show
http://fun2fresh.com/Map/MyReadingHistory/11
![image](https://user-images.githubusercontent.com/47495376/80441856-37bab680-8925-11ea-9ddf-36c154bbc889.png)

**Comment by sppk** [comment]
2)Book Reading
when we click on Delete button this white page show
 On Refreshing Entry Deleted 
http://fun2fresh.com/Map/ShowMybookHistory/11
![image](https://user-images.githubusercontent.com/47495376/80442125-c596a180-8925-11ea-8652-cd6ee67c2f96.png)

**Comment by sppk** [comment]
3)How this Action Link work
If it is for admin please give me Admin Email and Password
![image](https://user-images.githubusercontent.com/47495376/80442354-1f976700-8926-11ea-9e4a-45896a2719f2.png)

**Comment by sppk** [comment]
4)whenever we try to add time table
this Debugger is show and when I continue.It Redirect to Home page
![image](https://user-images.githubusercontent.com/47495376/80442711-f9be9200-8926-11ea-89e0-7d7acd91baf3.png)

**Comment by sppk** [comment]
5)I enter my golden words and click on save button 
then this windows appears
![image](https://user-images.githubusercontent.com/47495376/80446993-abfb5700-8931-11ea-98cb-0a43166055a8.png)
when we back and again open through category list then golden word show
![image](https://user-images.githubusercontent.com/47495376/80447080-dcdb8c00-8931-11ea-96fd-8b5ba502c99a.png)

**Comment by sppk** [comment]
6)Golden words after bookmarking
![image](https://user-images.githubusercontent.com/47495376/80447314-8589eb80-8932-11ea-91e1-d08cfe68316f.png)

**Comment by sppk** [comment]
7)SMS edit screen shows error
![image](https://user-images.githubusercontent.com/47495376/80447537-18c32100-8933-11ea-83a3-5fdb00404d98.png)
![image](https://user-images.githubusercontent.com/47495376/80447553-224c8900-8933-11ea-8343-2dceb011b89a.png)

**Comment by sppk** [comment]
8)I add data in poetry but it not save int it
![image](https://user-images.githubusercontent.com/47495376/80447758-c9312500-8933-11ea-8b0f-0e3326770336.png)

**Comment by sppk** [comment]
9)Picture of the Month not open
![image](https://user-images.githubusercontent.com/47495376/80448076-9b001500-8934-11ea-9c17-640dbb18bca7.png)

**Comment by sppk** [comment]
when we open edit profile 
the image remove
image must remain in it until we edit it also date
![image](https://user-images.githubusercontent.com/47495376/80448401-a0aa2a80-8935-11ea-9ece-7762433fe0d0.png)

**Comment by Muhammadkhalid66** [comment]
9-9)Picture of the Month not open fix 

@serviceproviderpk

**Comment by serviceproviderpk** [comment]
10) change "Faadback and Suggestions" Change to  "Your Feedback & Suggestions"
11) Add this link in "Footer" of Home  and Dasbhoard page
12) when someone submit the feedback chang this message  "Feedback send successed " to

"Thanks for your valuable feedback & suggestions"

**Comment by serviceproviderpk** [comment]
13) in Add Contact there is field "Ispublic" if user checked it. this phone numbr will be visible to everyone

**Comment by serviceproviderpk** [comment]
14) On home page change seqence of menu as


Picture of the Month
Golden Words
Funny SMS
Poerty
Handi Crafts
Phone Directory => Dispaly all nubmer whose IsPublic is true
Submit Your Feedback

**Comment by serviceproviderpk** [comment]
15) on My Dasbhaord change sequence of menu as

My Todo List
My Time Table
My Bookmarking
Book Reading
My Contacts
My Expenses

Golden Words
Funn SMS
Poetry
Handicrafts
Picture of the Month

**Comment by sppk** [comment]
11)when edit Pic of the Month
choose new picture
click on save button
![image](https://user-images.githubusercontent.com/47495376/80460518-62b90080-894d-11ea-8b67-e01215666c54.png)

**Comment by sppk** [comment]
12)edit Sms data
shows error message
![image](https://user-images.githubusercontent.com/47495376/80461985-82e9bf00-894f-11ea-8544-9c5ae9b9a789.png)

**Comment by serviceproviderpk** [comment]
Book reading details

please improve this page

![image](https://user-images.githubusercontent.com/19146254/80463062-0ce65780-8951-11ea-820a-182e56dc7689.png)

**Comment by Muhammadkhalid66** [comment]
book reading :
 i set font size both heading and detail same.
![image](https://user-images.githubusercontent.com/41336284/80469374-e973da80-8959-11ea-866c-bdd6da2e0068.png)

@serviceproviderpk

**Comment by sppk** [comment]
Dashboard
![image](https://user-images.githubusercontent.com/47495376/80489093-c86eb200-8978-11ea-800a-7058ad29cb37.png)
Home
![image](https://user-images.githubusercontent.com/47495376/80489164-dde3dc00-8978-11ea-8348-d1e740fcb334.png)

**Comment by serviceproviderpk** [comment]
10)  if user type is "Admin" add link "Manage Feedback" after submit your feedback
admin can view all feedback and can delete any feeddback

**Comment by serviceproviderpk** [comment]
11) if user type is **Admin** can see list of all Members
