### ISSUE TITLE
Exoticagem.com -> Shop

### ISSUE THREAD

**Issue by tipuazhar** [serviceproviderpk/sp.pk#254]
**Fix**
1) No email comes after placing an order:

![image](https://user-images.githubusercontent.com/29354031/77168017-8c6e4480-6ad0-11ea-88d0-7af284708e14.png)

**Comment by tipuazhar** [comment]
2.	After returning from privacy policy page I got this page

![image](https://user-images.githubusercontent.com/29354031/77168245-eff87200-6ad0-11ea-87a9-4ed203657aa4.png)


@amirlatif121  Can you please share the steps to reproduce this issue?

**Comment by tipuazhar** [comment]
Fix
3) I am logged in but at time of checkout I have to provide details again…. 

![image](https://user-images.githubusercontent.com/29354031/77168433-436ac000-6ad1-11ea-9f20-d00bbc9c3dfe.png)

**Comment by tipuazhar** [comment]
4) Integration of facebook pixel account

![image](https://user-images.githubusercontent.com/29354031/78008854-3eb7ce80-7351-11ea-9803-a98003ed80ab.png)

solution:

IN system setting we will add new filed

"HeaderPluginScripts""

you can add code there.

**Comment by Muhammadkhalid66** [comment]
> 1. No email comes after placing an order:
> 
> ![image](https://user-images.githubusercontent.com/29354031/77168017-8c6e4480-6ad0-11ea-88d0-7af284708e14.png)

![image](https://user-images.githubusercontent.com/41336284/78751819-55cb7180-798c-11ea-8117-238b7c53b49e.png)

i place order, email send in my account.

**Comment by tipuazhar** [comment]
> > 1. No email comes after placing an order:
> > 
> > ![image](https://user-images.githubusercontent.com/29354031/77168017-8c6e4480-6ad0-11ea-88d0-7af284708e14.png)
> 
> ![image](https://user-images.githubusercontent.com/41336284/78751819-55cb7180-798c-11ea-8117-238b7c53b49e.png)
> 
> i place order, email send in my account.

please use a fresh new account that is newly created.

Please try to subscribe two times to the website and see what is the behaviour of the website when completing different customer related tasks.

@tipuazhar 
@serviceproviderpk @sppk @Muhammadkhalid66 @amirlatif121

**Comment by tipuazhar** [comment]
@tipuazhar @serviceproviderpk @sppk @Muhammadkhalid66 @amirlatif121 

I have uploaded videos of the test being done on my screen to help the QA and DEV people to quickly identify the issues.

I will be uploading the videos on my youtube channel and sharing the link here.

https://youtu.be/scztIjnWiqU

The issue is with sorting A-Z where initially three items are shown one brand but when sorting is clicked only two items are shown please thoroughly test the use case scenario and than fix.

**Comment by tipuazhar** [comment]
![image](https://user-images.githubusercontent.com/29354031/79495656-fa594d80-8035-11ea-95d4-a2b99157dc58.png)

@tipuazhar @serviceproviderpk @sppk @Muhammadkhalid66 @amirlatif121

**Comment by tipuazhar** [comment]
@tipuazhar @serviceproviderpk @sppk @Muhammadkhalid66 @amirlatif121

![image](https://user-images.githubusercontent.com/29354031/79495755-2674ce80-8036-11ea-8796-530bdc9ab194.png)

![image](https://user-images.githubusercontent.com/29354031/79495837-40aeac80-8036-11ea-974e-4315e99bbc79.png)

The page does not scale up or scale down according to the size of the browser.

**Comment by tipuazhar** [comment]
![image](https://user-images.githubusercontent.com/29354031/79499149-8de14d00-803b-11ea-85f5-97e9c37d3678.png)

@tipuazhar @serviceproviderpk @sppk @Muhammadkhalid66 @amirlatif121

**Comment by tipuazhar** [comment]
![image](https://user-images.githubusercontent.com/29354031/79499444-02b48700-803c-11ea-8d55-c7b0c637e0cb.png)
@tipuazhar @serviceproviderpk @sppk @Muhammadkhalid66 @amirlatif121

**Comment by tipuazhar** [comment]
clicking on wish list selection button takes you to product detail, watch the video.

https://youtu.be/29M3STcvH4U

@tipuazhar @serviceproviderpk @sppk @Muhammadkhalid66 @amirlatif121

**Comment by tipuazhar** [comment]
Who was assigned the task of creating the logo for king gem last time ?

@tipuazhar @serviceproviderpk @sppk @Muhammadkhalid66

**Comment by tipuazhar** [comment]
![image](https://user-images.githubusercontent.com/29354031/79570720-06431f00-80cb-11ea-85d8-7ddc6ac6b7c0.png)

@tipuazhar @serviceproviderpk @sppk @Muhammadkhalid66 @amirlatif121

**Comment by tipuazhar** [comment]
![image](https://user-images.githubusercontent.com/29354031/79570991-73ef4b00-80cb-11ea-8d28-abafa40ca041.png)

@tipuazhar @serviceproviderpk @sppk @Muhammadkhalid66 @amirlatif121

**Comment by tipuazhar** [comment]
![image](https://user-images.githubusercontent.com/29354031/79571243-eeb86600-80cb-11ea-97a7-309ac76357ee.png)

@tipuazhar @serviceproviderpk @sppk @Muhammadkhalid66 @amirlatif121

**Comment by tipuazhar** [comment]
![image](https://user-images.githubusercontent.com/29354031/79571465-4787fe80-80cc-11ea-9666-2faeb25d75a7.png)

@tipuazhar @serviceproviderpk @sppk @Muhammadkhalid66 @amirlatif121
