### ISSUE TITLE
EMS_Sibling

### ISSUE THREAD

**Issue by nawabanjum** [serviceproviderpk/sp.pk#26]
1- separate screen for student registration with parent **Profile Tab** and save parentprofileid in student 
  table column  **StudentParentProfileId** 
  **Note** in edit screen if user want to assign parent drop-down option(in front must be add button to 
   create new parent profile)
2-sibling fee package create if not created/while branch created this package name must be created
3- **student reg screen** when we apply fee package on the student their value must be saved in 
   **Siblings_ParentStudentApplied_FeePackge**
4-New screen for fee collection where parent **drop-down** and all the sibling student must be shown 
   in html table with their fee package name,id ,fee packgeAppliedAmount and adjustedAmount(**goin 
  to pay**) ,transaction effected be on **Siblings_VoucherHead, Siblings_VoucherDetail** table
5-in front of every student  must be view transactions button 
6-fee collection **screen(old)** sibling student must be not showing.

In any inconvenience you can ping me

**Comment by nawabanjum** [comment]
Parent popup not closing on cancel button
**Fixed**

**Comment by nawabanjum** [comment]
On Parent Save alert message not showing proper ,and check email if alreadt exists
**fixed**

**Comment by nawabanjum** [comment]
required message are not according to over all system.
**fixed**

**Comment by nawabanjum** [comment]
in parent profile add column CNIC ,after select parent from the drop down ,father name ,CNIC ,Cellno1 must be auto fill as discussed 
**fixed**

**Comment by nawabanjum** [comment]
![package](https://user-images.githubusercontent.com/16934768/37723370-102426c0-2d50-11e8-8039-567a93988f2d.PNG)
there must be another textboxes for applied package amount **Fixed**

**Comment by nawabanjum** [comment]
On save Button if user not applied package then must be warning message ,please must select package or add student from other screen  **noy fixed**

**Comment by nawabanjum** [comment]
must save student in **ParentStudent** Also **fixed**

**Comment by nawabanjum** [comment]
check each and Every thing again please ,it is not as we discussed,
it is only 1 and half day work,but  i don't know why it is taking too much time.
if you are not comfortable for doing this let us know please.  
**AJ Half Day me hi kr diya hai**

**Comment by serviceproviderpk** [comment]
(Y)

**Comment by RizwanSaqib** [comment]
1. Make first student default as per  asif  suggestion. (Registration date wise)
2. Generate fee with only for default student
3.Fee collection will be against default student
4.If default student is going to pass out then make another student as a default and all the charges (collections,advance fee , Other transactions,etc)will be shown next default student

Created by (**Nawab**)

**Comment by adilshehbaz** [comment]
1- How to get balance of each student  on Fee Receipt Of Sibling

2- Books Balance on Fee Receipt @nawabanjum
