### ISSUE TITLE
EMS Feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#27]

**Comment by adilshehbaz** [comment]
1- Login time too much

@please requst to nawab give you some guideline to fix it.

**Comment by adilshehbaz** [comment]
2- Their is no validation when i click on signin button without credentials **(FIXED)**
![image](https://user-images.githubusercontent.com/28675602/37697764-7974e6aa-2d00-11e8-8ac7-c2ab050682ab.png)

**Comment by adilshehbaz** [comment]
3- Their is no validation when i click on "Send Me" button without credentials (**Fixed**)
![image](https://user-images.githubusercontent.com/28675602/37697796-b0cc48a0-2d00-11e8-9184-51c051d65f5e.png)

**Comment by adilshehbaz** [comment]
3- Font Size and Proper Action Name   (**Fixed**)
![image](https://user-images.githubusercontent.com/28675602/37698385-7fd6db12-2d04-11e8-95f1-a194d33ca9ab.png)

**Comment by adilshehbaz** [comment]
4- On Mouse Hover Change Colour of Text
![image](https://user-images.githubusercontent.com/28675602/37698421-b34e5c86-2d04-11e8-96c1-12223a1827bf.png)

**Fixed**

**Comment by adilshehbaz** [comment]
5- On Hover Change Colour to Green **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37698440-cfc594ba-2d04-11e8-8656-8fb96456fc4f.png)

**Comment by adilshehbaz** [comment]
6- Dropdown background color same as drop down of session **(FRF)**
![image](https://user-images.githubusercontent.com/28675602/37698478-fabafb60-2d04-11e8-949c-3cdfb5913a1b.png)

**Comment by adilshehbaz** [comment]
7-When i click on students, report manu also active  **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37698553-3fa3cfe0-2d05-11e8-8b80-e99e890a9b59.png)

**Comment by adilshehbaz** [comment]
8- Remove alert when i click on add in RPT_Module and in Reports  **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37698624-84f93a76-2d05-11e8-9b58-0478c79f013a.png)

**Comment by adilshehbaz** [comment]
9- No validation on RPT_modulem, also change title to description **(RPT Module has been commented)**
![image](https://user-images.githubusercontent.com/28675602/37698682-bd17678e-2d05-11e8-8d90-6f750eb7b7f8.png)

**Comment by adilshehbaz** [comment]
10- Report Add their is only one validation in Module Name, Also check other fields to validation **(Commented)**
![image](https://user-images.githubusercontent.com/28675602/37698725-f0c79cca-2d05-11e8-997c-b654d7201a04.png)

**Comment by adilshehbaz** [comment]
11- RPT_Module Add not unblocking UI on Submit **(Commented)**
![image](https://user-images.githubusercontent.com/28675602/37698765-322db51e-2d06-11e8-9d46-76a4c0018650.png)

**Comment by adilshehbaz** [comment]
12- Report Add Unblocking UI issue, and change input of isActive to checkbox, also space between ModuleName  **(Commented)**
![image](https://user-images.githubusercontent.com/28675602/37698837-7a359ff2-2d06-11e8-8430-8aae35765f38.png)

**Comment by adilshehbaz** [comment]
13- Create Branch Mobile No Validate Not Working like 0000-00000000 **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37704262-35f6f9d0-2d1a-11e8-9f70-7133880f798b.png)

**Comment by adilshehbaz** [comment]
14- Dummy Image missing in create branch **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37704334-576cbf96-2d1a-11e8-9223-0ef7be6ff771.png)

**Comment by adilshehbaz** [comment]
15- Create Class Total of Fee Packages Not Working
![image](https://user-images.githubusercontent.com/28675602/37704460-a697b468-2d1a-11e8-97e3-b0ca17b143a7.png)

**Comment by adilshehbaz** [comment]
16- Need to use pagination on activity log + Login + History Order By Desc in System Setting **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37704599-12aeb1a6-2d1b-11e8-8f40-d63185dee351.png)

**Comment by adilshehbaz** [comment]
17- Need to Remove GSM Checkbox from create event of sms **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37704665-45a66914-2d1b-11e8-8d64-78f8a81a5668.png)

**Comment by adilshehbaz** [comment]
18- Need to improve this screen of send general sms
![image](https://user-images.githubusercontent.com/28675602/37704740-7b2afc30-2d1b-11e8-98eb-cc9c590e3bc6.png)

**Comment by adilshehbaz** [comment]
19- Their is no role of department in system..
![image](https://user-images.githubusercontent.com/28675602/37704802-c0c45eee-2d1b-11e8-9f86-e8e34bf3c9a4.png)

**Comment by adilshehbaz** [comment]
20- in Student Inquiry If i click on delete option a popup occur, if i click on cancel button then unblock ui not stoped
![image](https://user-images.githubusercontent.com/28675602/37704875-0551dd84-2d1c-11e8-8e87-ef234158c380.png)

**Comment by adilshehbaz** [comment]
21- In Student Create when i want to accept inquiry as registered student, proper formate grid **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37704985-53a8457c-2d1c-11e8-8dde-c8faadb4cfc4.png)

**Comment by adilshehbaz** [comment]
22- Passout Option not working on student grid  **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37707535-438379ba-2d25-11e8-83e6-c3f6421488b9.png)

**Comment by adilshehbaz** [comment]
23- Parent Profile create Group dropdown showing all type of groups, just show a parent group **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37707657-b991c1de-2d25-11e8-85ac-3ae6b5bcd65d.png)

**Comment by adilshehbaz** [comment]
24- Parent Profile Create Profile Type dropdown showing all type of profiles, show only parent type **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37707705-e576d168-2d25-11e8-9bda-d3a0a0dc355a.png)

**Comment by adilshehbaz** [comment]
25- Remove Scroll bar from parent profile create screen
![image](https://user-images.githubusercontent.com/28675602/37707759-11cc2b3c-2d26-11e8-8836-bb07dfe33d46.png)

**Comment by adilshehbaz** [comment]
26- Change Grid of passout, terminate, struckoff and student history to same as active student, **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37707840-56674240-2d26-11e8-9841-437f10d51dc5.png)

**Comment by adilshehbaz** [comment]
27- Student dropdown on Student Create Screen showing no student, i add 2 student but their is no student
![image](https://user-images.githubusercontent.com/28675602/37707891-82e18c22-2d26-11e8-8064-7ed6a7bebcf5.png)

**Comment by adilshehbaz** [comment]
28- On Create Employee screen dummy image missing **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37707950-b55df550-2d26-11e8-9d6c-0a9786afbacd.png)

**Comment by adilshehbaz** [comment]
29- On Employee Create Screen their is a long list of account, Please show only current created account, **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37707986-d3b75b86-2d26-11e8-80c5-14ba0f6fb1b1.png)

**Comment by adilshehbaz** [comment]
30- Employee Salary Dropdown showing all branches employees dropdown. and not working, 
![image](https://user-images.githubusercontent.com/28675602/37708051-00321f2a-2d27-11e8-9193-8e30e37bf996.png)

**Comment by adilshehbaz** [comment]
31- Create Annual result grid not working, date, exam type etc
![image](https://user-images.githubusercontent.com/28675602/37708255-bb25cb1a-2d27-11e8-93d6-1277fdda3a43.png)

**Comment by adilshehbaz** [comment]
32- In Print Preview of Award list, showing menu also **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37708312-fe327cb4-2d27-11e8-9b0a-44ed2d81c9a5.png)

**Comment by adilshehbaz** [comment]
33- Generate Fee showing multiple roles with duplication  **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37708348-2958b868-2d28-11e8-846c-9b22f5e718eb.png)

**Comment by adilshehbaz** [comment]
34- Error converting varchar to date time error on internal email **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37709211-4fce9fe6-2d2b-11e8-887f-f937c150e8e9.png)

**Comment by adilshehbaz** [comment]
35- No need this cancel button on send sms to defaulter screen **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37709253-7772deea-2d2b-11e8-9abc-6bba4a203f20.png)

**Comment by adilshehbaz** [comment]
36- Need to remove send general sms menu from system setting it is already exist in message system **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37709309-a41a5180-2d2b-11e8-8987-5ac13cf9248f.png)

**Comment by adilshehbaz** [comment]
38- Reminder grid showing all reminders of all branches, **(RFR)**
![image](https://user-images.githubusercontent.com/28675602/37709337-bcd9941a-2d2b-11e8-9428-d0513fcda8ea.png)

**Comment by adilshehbaz** [comment]
39- change Opening balance bread crumb (RFR)
![image](https://user-images.githubusercontent.com/28675602/37709417-f4aec2e8-2d2b-11e8-8fc2-69a4f05be5e9.png)

**Comment by adilshehbaz** [comment]
40- Opening Balance Create not working due to date,**(RFR)**
and also change credit to voucher no
![image](https://user-images.githubusercontent.com/28675602/37709452-16cb4982-2d2c-11e8-8031-58b7ea3704a3.png)

**Comment by adilshehbaz** [comment]
41- Trail Balance Not working
![image](https://user-images.githubusercontent.com/28675602/37709516-427bb18e-2d2c-11e8-88aa-3208468de704.png)

**Comment by adilshehbaz** [comment]
42- balance sheet error of date converting  **RFR**
![image](https://user-images.githubusercontent.com/28675602/37709567-62c6dcde-2d2c-11e8-85da-368f21be1cff.png)

**Comment by adilshehbaz** [comment]
43- Create teacher goto next tab not auto working and subjects also not binding
![image](https://user-images.githubusercontent.com/28675602/37709625-a1e3609a-2d2c-11e8-910b-03937f88240f.png)

**Comment by adilshehbaz** [comment]
44- Staf attendance report not showing proper data
![image](https://user-images.githubusercontent.com/28675602/37709696-d98f8d52-2d2c-11e8-8554-24e7eee06cff.png)

**Comment by adilshehbaz** [comment]
45- Fee reporting not working with proper data

**Comment by RizwanSaqib** [comment]
46-
Go on Reports Click on it  and There is Four Option click on second Feature [Fee Report] It can not be work Proper give an Error Please Fixed it
![1](https://user-images.githubusercontent.com/38240379/38547507-a546366c-3cc8-11e8-94d4-24cf71fd64da.PNG)

**Comment by RizwanSaqib** [comment]
47-
Go Genrate fee and Right click on any student  there is Option

1) single chalan form
2) Genrate chalan form 

Single chalan form and generate chalan form  can not Work correctly raise error on run time

![3](https://user-images.githubusercontent.com/38240379/38548483-5c54fbc0-3ccb-11e8-866e-673cd0061c9a.PNG)

**Comment by RizwanSaqib** [comment]
48-
Go in Students Click on it There is Five Option Click on Second Option [Manage Students] There is List of students Right click on Student And click on Pass out  Student can not Shift in Pass out students
![2](https://user-images.githubusercontent.com/38240379/38548783-096f234e-3ccc-11e8-9a97-ef13febfda06.PNG)

**Comment by RizwanSaqib** [comment]
49
First we go in Staff click on it there is Two option click on Staff salary Fill Salary of Employee and load it  there is Screen of Salary and Deduction The Deduction of salary cannot Work Proper

![1](https://user-images.githubusercontent.com/38240379/38602110-3ec710da-3d83-11e8-8879-8e462fb9f80c.png)

**Comment by RizwanSaqib** [comment]
50 --
First Click on Organization then Click on Edit Profile when We Select Image and Upload Successfully  But image can not show on Dash board Image
![2](https://user-images.githubusercontent.com/38240379/38602965-c7c571e0-3d85-11e8-902f-f49b0ee124b1.PNG)

**Comment by serviceproviderpk** [comment]
@adilshehbaz  @UsmanJafar321 Usman please make sure above issues fixed, let me know when done.

Thanks,

**Comment by RizwanSaqib** [comment]
51--
When i Define fee package in class the Fee Package  Sequence Change Automatically in this image Monthly Fee in Top But when i create in Other classes Misc Charges on the Top
![screencapture-demo-educationmanagementsystem-net-student-index-2018-04-12-16_13_49](https://user-images.githubusercontent.com/38240379/38674353-a553506c-3e6d-11e8-8800-09a5deb89d14.png)

**Comment by RizwanSaqib** [comment]
52--
Click on Student there is Feature Manage Parents click on It There is Image option Kindly use Default missing image Here
![screencapture-demo-educationmanagementsystem-net-manageparentprofile-index-2018-04-12-16_52_29](https://user-images.githubusercontent.com/38240379/38675831-7a835eb8-3e72-11e8-89f8-806a53e01a9f.png)

**Comment by RizwanSaqib** [comment]
53--
Go in Staff Option click on it There is Option Staff registration and Kindly change Image and put Default missing image
![1](https://user-images.githubusercontent.com/38240379/38676869-d41bfb08-3e75-11e8-99d1-c6aa1836f72a.PNG)

**Comment by RizwanSaqib** [comment]
54--
In Staff Feature There is option Staff registration click on it and There is option [Residential Contact number ] it Accept unlimited numbers  Kindly apply validation on it
![2](https://user-images.githubusercontent.com/38240379/38677159-d778bfba-3e76-11e8-9f01-8ce6e5334275.PNG)

**Comment by RizwanSaqib** [comment]
55--
In Staff Registration [ Add Fee Account ] button is not in Perfect place there is no Space Between two table Top of Button have space but bottom can not have space and attach with bottom Table
![3](https://user-images.githubusercontent.com/38240379/38677517-ec4ad8a0-3e77-11e8-86a0-8c9bbddcce10.PNG)

**Comment by RizwanSaqib** [comment]
56--
Click on Exam there is Option [ Annual Exam ] Click on it There is option Exam type but We don't have any Option to define which type of Exam type  and We can not Submit null value in Exam type so we can not submit the Page
![screencapture-demo-educationmanagementsystem-net-resultcard-index-2018-04-12-18_05_01](https://user-images.githubusercontent.com/38240379/38680208-25831fc2-3e7f-11e8-80f9-302f674eb555.png)

**Comment by RizwanSaqib** [comment]
57--
There is Feature on Dash board [Quick Links ] Click on it There is list of links but no one work correctly


![screencapture-demo-educationmanagementsystem-net-home-dashboard-2018-04-12-18_33_28](https://user-images.githubusercontent.com/38240379/38680651-4835d298-3e80-11e8-83ff-7108ee8ddb24.png)

**Comment by RizwanSaqib** [comment]
58--
Student Voucher is Not like a Professional Dash board show with Voucher alignment of Vouchers and Detail need to Fix them 

![4](https://user-images.githubusercontent.com/38240379/38681716-ccb915be-3e82-11e8-8de1-68bec087d104.PNG)
![5](https://user-images.githubusercontent.com/38240379/38681816-0dc96aea-3e83-11e8-846a-f881627d1467.PNG)

**Comment by UsmanJafar321** [comment]
All issues are ready for review kindly check out them.
Thanks

**Comment by RizwanSaqib** [comment]
59--
Those selected Can not Work Please fix it
![6](https://user-images.githubusercontent.com/38240379/38682669-1fc98e12-3e85-11e8-95c4-c702bee94e64.PNG)

**Comment by RizwanSaqib** [comment]
60--
In Accounts click on Opening balance Fill all entries i give today date but when i submit it give nex day date 
![7](https://user-images.githubusercontent.com/38240379/38683268-7df6ed76-3e86-11e8-8fea-3711ee73073f.PNG)

**Comment by RizwanSaqib** [comment]
61--
In Accounts there is Option [Voucher Entry ]  click on on It and Fill the form If we give him 0 balance it Accept and Save him but when we edit O balance Voucher it raise an error ,Apply Validation on it can not save 0 balance Voucher 
![8](https://user-images.githubusercontent.com/38240379/38683876-db9a172c-3e87-11e8-8bde-23b3825ac1b9.PNG)

**Comment by RizwanSaqib** [comment]
62--
In Accounts Click on Ledger  There  2 Buttons of Print But first Button of Print can not work
![9](https://user-images.githubusercontent.com/38240379/38684385-0791c36a-3e89-11e8-9fe8-0dd3c352a9bd.PNG)

**Comment by RizwanSaqib** [comment]
63--
In Account select Trail balance there is Multiple Print Option but Firs Button of Print can not work
![10](https://user-images.githubusercontent.com/38240379/38684649-99f9f2fe-3e89-11e8-8391-d780ba08ea9d.PNG)

**Comment by RizwanSaqib** [comment]
64--
In Account Profit and Loss account there is Multiple Buttons of Print But first button can not work
![11](https://user-images.githubusercontent.com/38240379/38684990-5f59445a-3e8a-11e8-82a5-21448f48d65e.PNG)

**Comment by RizwanSaqib** [comment]
65--

Same like Profit and loss  In balance sheet there is Multiple Buttons of Print and can not work

**Comment by UsmanJafar321** [comment]
59-
http://localhost:22048/ClassConfiguration/Index

total of sibbling

use PKR where we are showing price in all over the system, set it from AppConst class
