### ISSUE TITLE
EMS Feedback by SP

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#29]
0) need to optimize login page its taking ages to load.
@nawab can you please do some research on it and try to fix it. Please if possible.
1) If i create a student i can see applied "Package" details
![image](https://user-images.githubusercontent.com/19146254/38782932-ba6d5782-4114-11e8-9536-c54b617869f6.png)
but when i edit same student in "Edit mode" i see that section is empty?
![image](https://user-images.githubusercontent.com/19146254/38782962-1ee44a36-4115-11e8-961f-a099d78f58bf.png)

2) 
![image](https://user-images.githubusercontent.com/19146254/38782995-93a8da76-4115-11e8-9c96-f1bd96423e9f.png)
Can you please add  space of 5px only between label, text box of Date picker and "Button"
and use this type of button for "Search" button  **(RFR)**
![image](https://user-images.githubusercontent.com/19146254/38783007-b7b3f176-4115-11e8-87b4-635154475594.png)
OR
Search button sh'd be consistent in all over the website, you can use someother button as you like but shd look better.
**(FIXED)**

**Comment by serviceproviderpk** [comment]
3) Can we change  heading and breadcrumb section as below
![image](https://user-images.githubusercontent.com/19146254/38783054-77716476-4116-11e8-858c-23ba779c1dad.png)
**(FIXED)**

**Comment by serviceproviderpk** [comment]
4) Can we remove href class  from 
![image](https://user-images.githubusercontent.com/19146254/38783085-e7e3a52a-4116-11e8-940e-7147a50f0d21.png) right now its looking like a link although it is tab.  **(FIXED)**

**Comment by serviceproviderpk** [comment]
5) padding/spacing should be same for Grids and add/edit screen sh'd be same **(FIXED)**
![image](https://user-images.githubusercontent.com/19146254/38783110-4910fdfc-4117-11e8-90fc-ca03469870f0.png)
in all over the system.

**Comment by serviceproviderpk** [comment]
5) Still i can space is not consistent in all grid (Please test all screens) **(FIXED)**
a) 
![image](https://user-images.githubusercontent.com/19146254/38893928-2e088db0-42a5-11e8-909f-6ecae0b9f68f.png)

b) 
![image](https://user-images.githubusercontent.com/19146254/38894176-ed200930-42a5-11e8-8ae5-7909f05cfc21.png)
c) **(FIXED)**
![image](https://user-images.githubusercontent.com/19146254/38894404-92410464-42a6-11e8-8e44-aaad8c7ebb00.png)
d) Please check all screens



6)  on  Login page  add "Register" button near "Forgot Password" when user register.
Send email on admin servie.....pk
and logo sh'd be in the center of the box.**(FIXED)**

7) "Quick Links" all menu sh'd be in working form.
8) on Add/edit Branch "Save"  and "Cancel " button sh'd be below the "Bank Section" **(FIXED)**
09) on add/edit Branch please add validation for "Phone"  of min/max 11 digit. **(FIXED)**
10) if user donot upload any branch photo then add default photo **(FIXED)**
11) i am logged in as "admin@admin.com"but still i am unable to "Edit" Branch **(FIXED)**
12) on add new branch "Created Date" is null in grid. it sh'd have created date. **(FIXED)**
13) Use Different fa icon for "Quick links" and Session **(FIXED)**
![image](https://user-images.githubusercontent.com/19146254/38893798-d4e85e9a-42a4-11e8-81d6-9517bfcdd20d.png)

**Comment by RizwanSaqib** [comment]
When i select Branch demo 1 and go on Student Management it select automatically Branch demo 2 Please fix it  Also can not show Active students on Dash board   **(FIXED)**

![screencapture-demo-educationmanagementsystem-net-student-index-2018-04-18-09_52_14](https://user-images.githubusercontent.com/38240379/38912569-77a2f20e-42ef-11e8-826b-c163bb5279c7.png)

**Comment by RizwanSaqib** [comment]
7---

Please correct the following Spelling  **(FIXED)**

![screencapture-necs-educationmanagementsystem-net-contractsystem-managecontract-index-2018-04-19-17_00_42](https://user-images.githubusercontent.com/38240379/38990558-3718456c-43f4-11e8-9c58-c40b14268fe7.png)

**Comment by RizwanSaqib** [comment]
8---
Please Solve this Issue and Remove copy rights Show in List of Test reports by Students  **(FIXED)**
![a](https://user-images.githubusercontent.com/38240379/38991899-8c052870-43f8-11e8-9b67-3490007d852f.png)

**Comment by UsmanJafar321** [comment]
![layout](https://user-images.githubusercontent.com/36027265/39055510-db6ea85c-44cd-11e8-956a-014d02f446f7.png)
layout of screen is not proper **(FIXED)**

**Comment by RizwanSaqib** [comment]
10----
When i select Manage Student feature it show List of Student but when i click on Pass out Students ,Terminate Students And Struck off Student it show all list of Students Please fix it **(FIXED)**
![1](https://user-images.githubusercontent.com/38240379/39082271-cced9ee0-4569-11e8-9b71-43c2165c7c73.png)

**Comment by nawab** [comment]
@serviceproviderpk Hey guys you added a wrong person to your repository

**Comment by serviceproviderpk** [comment]
1) Change menu item color **(FIXED)**

![image](https://user-images.githubusercontent.com/19146254/39412917-7a195810-4c3c-11e8-84a1-b80823ec6994.png)

same as below 
![image](https://user-images.githubusercontent.com/19146254/39412925-8e749ab8-4c3c-11e8-9e7e-d8f0f002cbb1.png)
2) Rename this  
![image](https://user-images.githubusercontent.com/19146254/39412948-c5705aa2-4c3c-11e8-8c21-8ce6077e13f1.png)
with "Try Free Demo?"   **(FIXED)**
3) when user fill the form email sh'd be send to "service@serv..pk"
4) Use Phone Numbrer validation in ALL (*) Screen like
Inqyiry,Student,Staff,Branch and default settings
 **(FIXED)**
5) Remove extra spacing from following screen  **(FIXED)**
a) 
![image](https://user-images.githubusercontent.com/19146254/39413024-04b86366-4c3e-11e8-8c34-488d24919b34.png)

![image](https://user-images.githubusercontent.com/19146254/39413013-ef644336-4c3d-11e8-837f-224f8c66bc0e.png)

c) Check All screens as i requested several time. spacing from top left right  in grids and CRUD screen sh'd be consistent.

**Comment by serviceproviderpk** [comment]
@RizwanSaqib 
if above issues are fixed please re-test and remove them from Github.

**Comment by serviceproviderpk** [comment]
101) if user fill this form "http://demo.educationmanagementsystem.net/Account/Register"
a) use proper validation
b) email sh'd be send on "service@serv...pk
and show thanks page and on thanks page use this text
"Thank you for showing your interest we will share demo credentials with you with in fewhours."

**Comment by serviceproviderpk** [comment]
102) Create a new layout page,  "Login page" register page and forgot password page will use that layout page.
 **(FIXED)**

**Comment by serviceproviderpk** [comment]
103) from Dashobard can we please remove highlighted section
 **(FIXED)**
![image](https://user-images.githubusercontent.com/19146254/39556091-350909b6-4e97-11e8-956f-449f1e6374c1.png)
and replace "Home Portal" with "Dashobard"
and replace "Overview, Statistics and more" with
You can Manage Inquiry, Students,Staff, Fee, Attendance,Exam,Stock,Communication, SMS, Reports and much more..

**Comment by serviceproviderpk** [comment]
104) 
![image](https://user-images.githubusercontent.com/19146254/39556178-dd865490-4e97-11e8-9e0e-2508153a6901.png)
From and To  label sh'd be left side of the Date picker control and spacing between label and date picker sh'd be consistent.
 **(FIXED)**

**Comment by serviceproviderpk** [comment]
105) Copy Rights section sh'd be in center of the page
![image](https://user-images.githubusercontent.com/19146254/39556209-259421e0-4e98-11e8-945c-cb0a9ac99755.png)
and back ground sh'd be fully white.

also add text "For Quick help Call us on: +92 307 4585 990"
106) replace email  " info@EducationManagementSystem.net " with  EducationManagementSystem.net@gmail.com"
 **(FIXED)**


Create new gmail id @Adil and redirect its all email to service@serviceprovider.pk

**Comment by serviceproviderpk** [comment]
107) in Grids use width for column as required instead of dummy width e.g
![image](https://user-images.githubusercontent.com/19146254/39556344-30810e5a-4e99-11e8-865b-8381ba58b581.png)

Column sh'd be proper sequence for description field you can skip width it will be autocalcualted

**Comment by serviceproviderpk** [comment]
108) Remove exrtra spacing fro all over the pages
as 
![image](https://user-images.githubusercontent.com/19146254/39556395-70bd0316-4e99-11e8-9c6b-b1571956f749.png)

**Comment by serviceproviderpk** [comment]
109)  in menu list above the "Logout" menu add new menu "Login History"
show data in this page from login hisotry datbase table.
do it with Jquery , request zaif to do it.

**Comment by serviceproviderpk** [comment]
110) On reporting menu bar is hanged, you can take help from Adil to fix it.this issue is very important.
**(This issue has been fixed just refresh cache)**
 **(FIXED)**

**Comment by serviceproviderpk** [comment]
111) @RizwanSaqib 

Please make sure you have tested each feature by entering proper data.
there sh'd be data in all pages, reports, certificate ets.
it will also  help customer to view features using proper data.
data sh'd be meaning full

**Comment by serviceproviderpk** [comment]
112) @RizwanSaqib  test all sms using feature "replace sms" with email Adil will help you.

**Comment by serviceproviderpk** [comment]
113) @UsmanJafar321  on sms send screen we will have  preview screen
user intiallly preview the msg text and  phone numbers then we will send sms.

**Comment by serviceproviderpk** [comment]
114) Dashobard menu will have following sub item
a) "Software" it will show dashobard link "/Home/Dashboard"
b) Website  it will open website in new Tab
c) Parents Portal it will open new tab and will display "Parents Portal" i guess section is not ready.

**Comment by serviceproviderpk** [comment]
115) 
![image](https://user-images.githubusercontent.com/19146254/39908595-39e9cab6-5508-11e8-98be-2bb97dfbe5e3.png)
Dopdown text sh'd be

Student Name + father name+class+section ( we will use it in other screen where user can get confused)

**Comment by UsmanJafar321** [comment]
I have marked as "FIXED" those points that has been fixed.
