### ISSUE TITLE
feedback EMS

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#31]

**Comment by serviceproviderpk** [comment]
1) On   Dashboard   Students >  Add Student Inquiry, Please use validation message for all phone number
min and maximum lenght sh'd  11  character
**(Fixed)**

**Comment by RizwanSaqib** [comment]
2.
When i create And Edit Branch It can not b create and Edit  
Second Bank  details can not save 
Third issue Mobile Validation can not Work 
And fax number Allow to user type any type of number and alphabets
**(Fixed)**
![1](https://user-images.githubusercontent.com/38240379/39464506-49a71f40-4d37-11e8-8de7-b11f7eff1cd4.png)

**Comment by RizwanSaqib** [comment]
3.
1)When we add Student in Inquiry there is Phone number need to validation on it it save one or 2 numbers 
2)When i enter Total marks in Inquiry student it give an Exception of Web Fonts

**Comment by RizwanSaqib** [comment]
When i add new student Then alignment of Page Like this (Student get from Inquiry Student) **(FIXED)**

![screencapture-demo-educationmanagementsystem-net-student-index-2018-05-01-12_28_30](https://user-images.githubusercontent.com/38240379/39465206-7ffc4d0a-4d3b-11e8-9976-6cb0c8b03f53.png)

**Comment by RizwanSaqib** [comment]
There is Mobile career and Phone career but  after Careers Next Feature Religion then Cell 
How is it possible First we choose career then chose religion and after religion  enter mobile number **(FIXED)**
![screencapture-demo-educationmanagementsystem-net-student-index-2018-05-01-12_37_57](https://user-images.githubusercontent.com/38240379/39465477-1067d296-4d3d-11e8-8513-0454f53c4cc5.png)

**Comment by RizwanSaqib** [comment]
In Manage parents add parents profile  There is Mobile number need to Apply validation on it

**Comment by RizwanSaqib** [comment]
In Student application student list can not show **(FIXED)**
![1](https://user-images.githubusercontent.com/38240379/39465962-c69266a6-4d3f-11e8-8337-4b1b56c0ac5f.png)

**Comment by RizwanSaqib** [comment]
Please apply validation on Father CNIC Number and Mobile number  **(RFR)**
![2](https://user-images.githubusercontent.com/38240379/39468265-9773604e-4d4b-11e8-97cd-056ebb94fb4e.png)

**Comment by RizwanSaqib** [comment]
In student attendance after attendance of Student when we verify  Present and Absent Student page layout out of Form Please fix it **(FIXED)**
![3](https://user-images.githubusercontent.com/38240379/39468492-ae615cec-4d4c-11e8-976e-62890059843a.png)

**Comment by RizwanSaqib** [comment]
In Annual Result a field Name Exam type But There is no form where we define Exam Type
**(FIXED)**
![4](https://user-images.githubusercontent.com/38240379/39468896-cdc7d992-4d4e-11e8-9860-c8a55fdf86de.png)

**Comment by RizwanSaqib** [comment]
When i create New Student It can not Show Pop-Up of Student save And not redirect to Student list Screen Please Fix it **(FIXED)**

**This issue has already fixed form local side** 

![5](https://user-images.githubusercontent.com/38240379/39469198-80af9350-4d50-11e8-85d6-b0cbf6d519aa.PNG)

![6](https://user-images.githubusercontent.com/38240379/39469266-cb8d542a-4d50-11e8-9dd9-91d7fa596785.png)

**Comment by RizwanSaqib** [comment]
Go in generate fee  right click on screen and click on Generate chalan form  show below error **(RFR)**
**This issue has already fixed form local side.**
![1](https://user-images.githubusercontent.com/38240379/39469562-4ad934f0-4d52-11e8-9864-9494de22ea08.PNG)
![2](https://user-images.githubusercontent.com/38240379/39469574-520e5f98-4d52-11e8-875a-608714f30ab4.png)

**Comment by RizwanSaqib** [comment]
Page alignment can not Proper Please Fix all alignment **(FIXED)**
![3](https://user-images.githubusercontent.com/38240379/39470355-9f30c37a-4d56-11e8-8f31-5fd7382e3e9d.png)

**Comment by RizwanSaqib** [comment]
In Accounts Feature  Account Group There is Button list Can not work Properly **(FIXED)**

![4](https://user-images.githubusercontent.com/38240379/39470506-a4e3d806-4d57-11e8-9110-d2cb144ab81c.png)

**Comment by RizwanSaqib** [comment]
In Accounts Click on Ledger then Print any Ledger it  show print like this **(FIXED)**

![5](https://user-images.githubusercontent.com/38240379/39470815-3dc40ed2-4d59-11e8-85ae-457ad5955bb6.PNG)

**Comment by RizwanSaqib** [comment]
i have 9800 balance but it give us -9800 balance please fix the balance sheet Personally i am not satisfied with Profit and loss and Balance sheet **(FIXED)**
![6](https://user-images.githubusercontent.com/38240379/39471147-f5a54a42-4d5a-11e8-9055-59a792275552.png)

**Comment by RizwanSaqib** [comment]
Please fix the Alignment of Search **(FIXED)**
![1](https://user-images.githubusercontent.com/38240379/39471619-7d26c9ee-4d5d-11e8-9f40-48915d1bb38a.png)

**Comment by RizwanSaqib** [comment]
When i have add new student and Click on Save it can not show Pop-Up of Successfully Save 
**Issue has been fixed from local side.**
![2](https://user-images.githubusercontent.com/38240379/39699678-ab546a0a-5213-11e8-8878-de3a92b32720.png)

**Comment by RizwanSaqib** [comment]
Go on generate fee Right click on  Screen there is Option Genera Chalan Form and single chalan form Both are Show Error please fix 
**Issue has been fixed from local side.**

![image](https://user-images.githubusercontent.com/38240379/39702282-b33b0bf2-521d-11e8-86ff-84b58a20b01c.png)
![image](https://user-images.githubusercontent.com/38240379/39702322-d6dbaab2-521d-11e8-8742-5974d6d4419e.png)

**Comment by UsmanJafar321** [comment]
a) Its showing student id,class and section id instead of student name in searchbox
b) when click on print in fee information section its giving the following error.
![std_profile_error](https://user-images.githubusercontent.com/36027265/39754106-832f180a-52da-11e8-8d43-39786a3840e1.png)
![error_std](https://user-images.githubusercontent.com/36027265/39754161-a98042fe-52da-11e8-96a4-c03c1cb8381f.png)

**Comment by RizwanSaqib** [comment]
In (manage Students) Student Search Between Dates Can not Work
![1](https://user-images.githubusercontent.com/38240379/39758674-0035b3a4-52ea-11e8-99e0-9aa68417d175.png)


**RFR** Adil

**Comment by RizwanSaqib** [comment]
Go on manage student Right click on Screen There is Option of quick Registration When i add Student using Quick Registration then Show Error like this and can not save Student
![2](https://user-images.githubusercontent.com/38240379/39759209-84490064-52eb-11e8-90dd-a07a3cfff0c4.PNG)


**RFR** Adil

**Comment by RizwanSaqib** [comment]
When i add new student and apply standard package  in standard package define Total 25000 and Give 5000 Discount and Save it .Go on  Collect Fee Select the Student it can not show Current Balance of Student  if i Generate All classes Fee and again Collect fee of Student it Show only 300 Rupees
![3](https://user-images.githubusercontent.com/38240379/39760990-48813f38-52f0-11e8-9a03-f6fa1a5a73f0.png)


**RFR Adil**

**Comment by RizwanSaqib** [comment]
Login with Teacher Account and  Collect fee of Student then go in Reports Click on Fee Reports Detail It give us Only name of Student but dont show Receivable Amount
![4](https://user-images.githubusercontent.com/38240379/39764770-c31cf90e-52f9-11e8-8721-a600b043a020.png)

**RFR** Adil

**Comment by RizwanSaqib** [comment]
I have collect 2 students Fee by Teacher (Tayyab) but when i check Reports of Fee collection by Teacher total amount of Collection not show in Report of TEacher
![1](https://user-images.githubusercontent.com/38240379/39765235-ca894930-52fa-11e8-9a65-784514310a58.png)


**RFR** Adil

**Comment by RizwanSaqib** [comment]
Section List can not show in Student Award List please fix 
![2](https://user-images.githubusercontent.com/38240379/39772514-ea85d852-530e-11e8-823a-8b1eb0e1541c.png)

**RFR** Adil

**Comment by RizwanSaqib** [comment]
I collect Fee using Staff But in Ledger  Debit And Credit  = 0 and Total balance = 0
![3](https://user-images.githubusercontent.com/38240379/39773678-3ca276e2-5312-11e8-9390-d9a7e9a2eb99.png)


**RFR Adil**

**Comment by RizwanSaqib** [comment]
Collect Fee by Staff but main account of Staff in ledger can not show Credit balance in Ledger
![4](https://user-images.githubusercontent.com/38240379/39774408-2a82a4e4-5314-11e8-9788-70dd7b7a68a0.png)


**RFR Adil**
