### ISSUE TITLE
EMS Testing Status

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#38]
1)Create Branches
2)Create Session
3)Class Configuration 
a)Section
b)Define Fee Package for Class
4)Students
a)Manage Student
b)InquiryStudent
c)Manage Parents
5)Staff
a)Staff Registration
b)Staff Salary
6)Attendance
a)Student Attendance 
b)Staff Attendance
7)Exam
a)Test System
b)Annual Result
3) Award List
8) Fee
a)Collect Fee
b)Generate Fee
9)Communication System
a)Internal Email
10)Accounts
a)Ledger
b)Voucher Entry
c)Opening Balance
d)Chart of Account

11)Reports 
Student Reports
a)Issued Certificate list
b)Contact Info
c)Branch Wise Student
d)Monthly Reports
e)Attendance Summary
f)Class Attendance Report

12)Fee Reports
a)Student Defaulter list
b)Staff Collection Report

Test Report
a)Student Test report
b)Class Test Report
c)Multiple student Reports

**Comment by serviceproviderpk** [comment]
1) Branches
2) Session
3) Class Configuration
a) Subjects
b)Fee Package

**Comment by RizwanSaqib** [comment]
Class Configuration
---------------------
When i Create Class and Put Amount in Standard Package and Sibling It show the sum of Both of Package  So fix this issue Show amount separate 
This issue is same like metioned below already 
**@nawabanjum Sir will review this.**
![class](https://user-images.githubusercontent.com/38240379/40058007-4e26d30c-5869-11e8-9a7f-9b9a357ea8d5.png)

**Comment by RizwanSaqib** [comment]
When i add student in Student registration Increment can not Work please fix it

**(FIXED)**
![1](https://user-images.githubusercontent.com/38240379/40122466-5556388c-593d-11e8-9542-a8c00edf867e.png)

**Comment by RizwanSaqib** [comment]
When We pay salary to employee the Total present and absent of Employee can not show please fix it
**(FIXED)**
![2](https://user-images.githubusercontent.com/38240379/40124467-134dbadc-5942-11e8-851c-756ab6273342.png)

**Comment by RizwanSaqib** [comment]
When i Pay To employee and load the form it can not Load Give null value error So please fix it

**(FIXED)**
![1](https://user-images.githubusercontent.com/38240379/40125059-61b53f00-5943-11e8-9927-b4ae7743c278.png)

**Comment by RizwanSaqib** [comment]
Go in student attendance and and get student attendance then verify Absent student and Print report 
**(FIXED)**
![2](https://user-images.githubusercontent.com/38240379/40125535-995cef1a-5944-11e8-8a2e-3ba849addf5f.PNG)

**Comment by RizwanSaqib** [comment]
Go in Exam Module and Click on Annual Result when i create annual result it can not load and show error please fix 
**(FIXED)**
![3](https://user-images.githubusercontent.com/38240379/40157989-75fc0cd2-59bb-11e8-9e69-9cf23d8a00b9.png)

**Comment by RizwanSaqib** [comment]
When i add new student and apply fee on it 6000 Total and go in Collect Fee in Fee Module It Show 21100 Total Please fix it
**(FIXED)**
@adilshehbaz  Kindly review this feedback
![4](https://user-images.githubusercontent.com/38240379/40158542-8771fd0c-59be-11e8-9417-f197c12d31b7.png)

**Comment by RizwanSaqib** [comment]
I have send 3 time Email But can not Received on my Gmail i have Check in Spam ,and inbox Please Fix it
![5](https://user-images.githubusercontent.com/38240379/40159320-317c9d22-59c2-11e8-9c7e-07bdeb96d1f3.png)

**Comment by RizwanSaqib** [comment]
When i collect fee using Staff login and Login again with admin then Go in Accounts and click on ledger select staff account it can not show the total balance of staff in ledger
![6](https://user-images.githubusercontent.com/38240379/40160075-77676e2c-59c5-11e8-97e1-0b42f21531af.png)

**Comment by RizwanSaqib** [comment]
When i open any Report then Click on any Module it can not be worked when i refresh the System it work again please fix the issue

@adilshehbaz  please review this feedback

**Comment by RizwanSaqib** [comment]
Student Name did'nt show in student name please fix it
**(FIXED)**
![7](https://user-images.githubusercontent.com/38240379/40169919-94eb6db6-59e0-11e8-86fc-95cda59ac558.png)

**Comment by UsmanJafar321** [comment]
I have fixed issues and remaining few issues refer to @adilshehbaz  for review and this feedback completed excepted those issues referred to Adil.

**Comment by RizwanSaqib** [comment]
Apply Validation on Contact number in Stock Module (Warehouse)
**(FIXED)**
![1](https://user-images.githubusercontent.com/38240379/40220778-c8a77646-5a93-11e8-9c52-8f36f3d79f78.png)

**Comment by RizwanSaqib** [comment]
When in add Student in sibling and go to collect fee of Sibling it show only one student against Parent but i have add two students in sibbling
@adilshehbaz  Please review this issue.
![2](https://user-images.githubusercontent.com/38240379/40222434-e6e6470e-5a98-11e8-8896-4d3f33d46ef4.png)
![3](https://user-images.githubusercontent.com/38240379/40222469-067b4f9c-5a99-11e8-8aba-065c0381da73.png)
