### ISSUE TITLE
EMS Testing Status

### ISSUE THREAD

**Issue by RizwanSaqib** [serviceproviderpk/sp.pk#42]

**Comment by RizwanSaqib** [comment]
When i create new student there is multiple book charges Please fix it  **(FIXED)**
![1](https://user-images.githubusercontent.com/38240379/40640225-89e10b5e-632e-11e8-989b-3d7f2226da82.png)

**Comment by RizwanSaqib** [comment]
i have  create new Package of Sibling Fee It can not Apply and show  on Previous Classes 
**(RFR)**
![3](https://user-images.githubusercontent.com/38240379/40642077-5ce9bab8-6335-11e8-9af3-7fd5f3aeed57.png)

**Comment by RizwanSaqib** [comment]
When i fill the Leave form of student and enter from and to date of leave it can not be save and show the Pop-up  From date must be a date 
**This issue has been fixed on local side**
![4](https://user-images.githubusercontent.com/38240379/40643112-6f50bc6c-6338-11e8-9cc1-c98fae94f284.png)

**Comment by RizwanSaqib** [comment]
Go in student Profile select a student and click on Fee information Print detail it show error like this **(FIXED)**
![6](https://user-images.githubusercontent.com/38240379/40649830-4458a796-634b-11e8-949b-735761bd4184.png)

![5](https://user-images.githubusercontent.com/38240379/40643300-1a4c8312-6339-11e8-9a75-49f6b4dd849a.png)

**Comment by RizwanSaqib** [comment]
When i get attendance of Student and save it can not show Pop_up of Save attendance 
**Already Fixed on local side**
![7](https://user-images.githubusercontent.com/38240379/40652428-aa5405ee-6351-11e8-8c2e-c59d5130e4d7.png)

**Comment by RizwanSaqib** [comment]
In staff salary Total present and Absent of Employee can not show Please fix it
**(FIXED)**
![8](https://user-images.githubusercontent.com/38240379/40652632-302b0032-6352-11e8-95d6-edcb0db77aa8.png)

**Comment by RizwanSaqib** [comment]
I have add two Sibling students in class and apply fee Login with Teacher ID and collect Fee but it can not show total amount of Fee and Students of Sibbling
![9](https://user-images.githubusercontent.com/38240379/40657400-26e84b60-6361-11e8-98a3-ae6bcd46e665.png)

**Comment by RizwanSaqib** [comment]
I have add two Student in Sibbling then Login with Teacher Account and Collect Fee but it show error like this and
**(RFR)** 
![1](https://user-images.githubusercontent.com/38240379/40701967-716fb748-63f9-11e8-8cc8-8b74515429c5.png)

**Comment by RizwanSaqib** [comment]
In Test Report of Class there is some issue I give total marks 100 But in report it show Obtain marks 100 And Total marks in Percentage and in Percentage  1 ,2 ,3 Please fix **(FIXED)**
![2](https://user-images.githubusercontent.com/38240379/40703214-f048e892-63fd-11e8-88a8-26f592444cad.png)

**Comment by RizwanSaqib** [comment]
I have take Attendance of staff but It can not show in Reports please fix it
**(RFR)**
![3](https://user-images.githubusercontent.com/38240379/40703819-ded397ea-63ff-11e8-83c9-7f7d79ea6250.png)

**Comment by UsmanJafar321** [comment]
All feedback is ready for review kindly review this.
@adilshehbaz @nawabanjum @serviceproviderpk

**Comment by serviceproviderpk** [comment]
@adilshehbaz 
@UsmanJafar321  as latest code is deployed then retest above issue then change status from
"RFR" to "Fixed"

All time we will follow this follow
during local testing status will be  "RFR"
after deployment and testing on service change to "Fixed"

**Comment by UsmanJafar321** [comment]
In collect fee portion when clicked on any student its not showing student details
![ems error](https://user-images.githubusercontent.com/36027265/41658245-a41b63a2-744a-11e8-9bcc-ccc6d8b60f80.png)
