### ISSUE TITLE
YS by Adil

### ISSUE THREAD

**Issue by adilshehbaz** [serviceproviderpk/sp.pk#45]

**Comment by adilshehbaz** [comment]
Remove Mange Images and button to right align  **(FIXED)**
![image](https://user-images.githubusercontent.com/28675602/40791510-1e8aebce-6511-11e8-877d-40f3d91a3a50.png)

**Comment by adilshehbaz** [comment]
button to right align **(FIXED)**
![image](https://user-images.githubusercontent.com/28675602/40791525-2a571c84-6511-11e8-8fe6-ba407bfc6ffc.png)

**Comment by adilshehbaz** [comment]
right align button **(FIXED)**
![image](https://user-images.githubusercontent.com/28675602/40791570-407f28da-6511-11e8-95a8-36a1a601051a.png)

**Comment by adilshehbaz** [comment]
See on home index top left corner showing s ..please remove this **(FIXED)**
![image](https://user-images.githubusercontent.com/28675602/40791822-cfaf64ca-6511-11e8-8f3c-c6174cfaec0c.png)

**Comment by UsmanJafar321** [comment]
@adilshehbaz  all issues has been fixed kindly review that issues.
