### ISSUE TITLE
SaudiPhone.com

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#53]
1) On website below the"menu section" add section like this
![image](https://user-images.githubusercontent.com/19146254/41688927-8757c7ac-7507-11e8-8171-7adfba7fec51.png)
Ref: http://ae.cellsouq.com/en/product/?id=samsung-galaxy-note-7-price-in-dubai-uae-44418

Solution:

You will create a new table "PopularProducts" (Id,ProductID,CreatedDate)

in product list page (add new button "Mark as Popuplar") as user click on on it, new record will be added in above table.

in admin section you will create a new page that will show list of "PouplarProducts"
Any time you can delete products from table "PopularProducts"

you will create a partial view that will show PouplarProducts in layout page below the menu page.
b) you need get popular products from Server side Cache

**Comment by serviceproviderpk** [comment]
2) Where there is price in all website and in ALL page use symbol 
e.g 150 SAR
(SAR) will be set from BusinessManager by creating a new functions
![image](https://user-images.githubusercontent.com/19146254/41689264-3d531aba-7509-11e8-93dc-cf38c177fb07.png)

3) On Product detail page also show Price in USD as well as

you can convert price SAR to USD by calling any API
I can share API URL with you.

**Comment by serviceproviderpk** [comment]
4) On product Detail page
above the "Related Product" add new section
Similar Products

create a new partial view and show products of that category.
as below 
![image](https://user-images.githubusercontent.com/19146254/41689446-08868c12-750a-11e8-876f-d4f8e8a2883b.png)

**Comment by serviceproviderpk** [comment]
5) make sure duplicate meta tags/ html improvements
6) check website in mobile UI , its rendering fine.

**Comment by serviceproviderpk** [comment]
7) on home page for this partial view if user click on on product name, it sh'd show detail page
![image](https://user-images.githubusercontent.com/19146254/41690519-6bd214e4-750f-11e8-8116-334c46fb017a.png)

8) Add disquss plugin in product detail page
https://disqus.com/

**Comment by serviceproviderpk** [comment]
9) on product page add this line
![image](https://user-images.githubusercontent.com/19146254/41690784-99dfaaee-7510-11e8-9c62-2354223403f2.png) **FIXED**

product name and date will be set dynamic.

**Comment by serviceproviderpk** [comment]
0) Add size is distrubed in header plz fix it.   **FIXED**
1) Create Following pages

First Read Routing and then create following routes

2-Popular Mobile In KSA (routes for famous cities)
3- Most Viewed Products    **fixed**
4- Cheap Mobiles Phone List **fiexd**
5- Mobile Phone by Seller
6- Upcoming Mobiles
7- Most Costly Mobile Phone **fixed**

2) 
in footer add following section
Section 1 for above links
Section 2
![image](https://user-images.githubusercontent.com/19146254/38449444-9facf986-3a28-11e8-9a84-b90dd006f958.png)
Section 3
![image](https://user-images.githubusercontent.com/19146254/38449449-bca4cf3c-3a28-11e8-9222-6fbef442c460.png)

section 4
Routes with cities as blow
Mobile phone  price in Riyadh	
Mobile phone  price in Jeddah	
Mobile phone  price in Mecca	
Mobile phone  price in Medina	
Mobile phone  price in Al-Ahsa	
Mobile phone  price in Ta'if	
Mobile phone  price in Dammam	
Mobile phone  price in Buraidah	
Mobile phone  price in Khobar
Mobile phone  price in Tabuk

3) admin section add two linkis
TrendsCategory: TrendCategoryId,ParentID,Name,Description,NumberofViews,PageTitle,PageKeywords,PageDescrition,ImageURL

Trend: TrendCategoryid, Id,Name,Description,NumberofViews,PageTitle,PageKeywords,PageDescrition,ImageuRL

Trends  > Trend Details (on both pages show  partial left and right side
left (mot viwed, trends cateogry on right side)

**Comment by serviceproviderpk** [comment]
5) on product detail page relplace "Related product" section with Recent Viewed Products  **FIXED**
![image](https://user-images.githubusercontent.com/19146254/41819874-b87f0c8c-77e1-11e8-9bbc-65757d058583.png) 

Create A new table
"RecentlyViwed" (Id,ProductId,ViewedDate)
and show product in that section from above table.

**Comment by serviceproviderpk** [comment]
6) in footer add link "Disclaimer" we have already created this page. just link it. **Fixed**

**Comment by zaifullah786** [comment]
1) Fixed

**Comment by serviceproviderpk** [comment]
7) Please use cache for all pages that you have created so far.

also for user control that you have used in footer.

**Comment by serviceproviderpk** [comment]
8) we want to add new category "beauty"
think about it.https://www.noon.com/en-ae/cinema-edp-90-ml/N11201035A/p?o=fcbaa2343473cc3c

**Comment by zaifullah786** [comment]
All task except 3 and 8 are done

**Comment by adilshehbaz** [comment]
1) fixed
