### ISSUE TITLE
EMS Feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#55]
1) On Dashobard this chart is showing Zig Zag data, can we fix it?
 @adilshehbaz kindly review this
![image](https://user-images.githubusercontent.com/19146254/41804102-336d6bd4-76aa-11e8-9a5f-9d66f9ea54eb.png)

**Comment by serviceproviderpk** [comment]
2) Highlight button is not working, i clicked nothing happend
**(FIXED)**
![image](https://user-images.githubusercontent.com/19146254/41804133-c08e29b8-76aa-11e8-8818-41971b2f7060.png)

Please also use tool tip of these icon in all over the system

**Comment by serviceproviderpk** [comment]
@adilshehbaz 
Question

I have registered a student in class 4th, fee package applied.

how i will collect the payment? and add in system?

**Comment by serviceproviderpk** [comment]
3) Internal messaging menu not working 
menu whose are not working please hid from system
**(FIXED)**
![image](https://user-images.githubusercontent.com/19146254/41804277-0381a4be-76ad-11e8-8501-b46c931ae47c.png)

**Comment by serviceproviderpk** [comment]
4) add "+" icon as we are using in all screens
**(FIXED)**
![image](https://user-images.githubusercontent.com/19146254/41804282-42492c9e-76ad-11e8-95e0-4661bed48612.png)

and  latest and or up-coming reminder sh'd be on top.

**Comment by serviceproviderpk** [comment]
5) show latest on top on user login history page
**(FIXED)**
![image](https://user-images.githubusercontent.com/19146254/41804309-ae6e1d44-76ad-11e8-838e-480a5a323e83.png)

**Comment by serviceproviderpk** [comment]
6) when user create a branch, "CreatedDate" sh'd be saved in db and show in branch list page as well as.
**(FIXED)**

**Comment by serviceproviderpk** [comment]
7) on  sms send screen "Preview Button " not working.
![image](https://user-images.githubusercontent.com/19146254/41804329-2002176c-76ae-11e8-8958-1df6d35d71bf.png)

**Comment by serviceproviderpk** [comment]
8) as above screen(7) create a new page name it as
"SystemLookups" we will have list of  all lookup like EmployeType, Package name,PromotionType,GroupType(will change name only)

**Comment by serviceproviderpk** [comment]
9) Student drop down sh'd be search able **Fixed**
![image](https://user-images.githubusercontent.com/19146254/41804411-9045ac4a-76af-11e8-801b-130dcbf4b832.png)

dropdown text sh'd be (Student+Father Name+Class+section)
it was also in my previous feedback

**Comment by zaifullah786** [comment]
10) In admin on login picture is not shown in login menu **Fixed**

**Comment by zaifullah786** [comment]
11) remove validation zipcode in branch create form and other form **Fixed**

**Comment by zaifullah786** [comment]
12)on branch create form write institute name instead on name **Fixed**

**Comment by zaifullah786** [comment]
13) all branches are not shown in branch top menu

**Comment by zaifullah786** [comment]
14) in list page select a default row **Fixed**

**Comment by zaifullah786** [comment]
15) in ladger dropdown sort by alphabeticaly **Fixed**

**Comment by zaifullah786** [comment]
16) apply button is not working in student create form (fee detail section)

**Comment by zaifullah786** [comment]
17) change in generate fee rename fee to genrate fee **Fixed**

**Comment by zaifullah786** [comment]
18) work on grace day in generate fee form

**Comment by zaifullah786** [comment]
10) In admin on login picture is not shown in login menu **Fixed**
11) remove validation zipcode in branch create form and other form **Fixed**
12)on branch create form write institute name instead on name **Fixed**
