### ISSUE TITLE
Saudi-Phone  - SEO

### ISSUE THREAD

**Issue by tayyabmukhtar** [serviceproviderpk/sp.pk#61]
The Total Number of Link Exceeds in a page
![error 4](https://user-images.githubusercontent.com/40711981/42124075-fd096af8-7c75-11e8-8700-9b8ba546bcf0.PNG)

**Comment by zaifullah786** [comment]
This is for discussion because I have no idea what to do

**Comment by serviceproviderpk** [comment]
2) Underscores in Url
![error 3](https://user-images.githubusercontent.com/40711981/42124061-c7569ffc-7c75-11e8-90e4-e92a4962aee4.PNG)

**Comment by tayyabmukhtar** [comment]
AlT Attribute is Missing in Images. Proper AlT Attribute set in images
![error 5](https://user-images.githubusercontent.com/40711981/42364698-8b9d2af4-8115-11e8-81ab-118e10cd95e2.PNG)

**Comment by tayyabmukhtar** [comment]
WWW Redirects Issue
![error 6](https://user-images.githubusercontent.com/40711981/42364762-c3681822-8115-11e8-98d8-adc864884b1f.PNG)
