### ISSUE TITLE
Saudi Phones

### ISSUE THREAD

**Issue by zaifullah786** [serviceproviderpk/sp.pk#66]
0)
remove this section from all website and all pages

![image](https://user-images.githubusercontent.com/19146254/44242342-9d631f80-a1e2-11e8-83e2-585aa1e8506c.png)

**Comment by serviceproviderpk** [comment]
1) on home page for these show top 4, which are set as feattured   **RFR**
use store procedure and select ONLY required columns
![image](https://user-images.githubusercontent.com/19146254/44235402-cecbf300-a1c2-11e8-8cbf-45c3b7551e92.png)

and use cache as i used for top menu

**Comment by serviceproviderpk** [comment]
2) new and reviews list page convert to the   section   **RFR**

a) left side,  b) center section (show  list of news c) Right side by just as below page

http://saudi-phone.com/mobiles/Apple-mobile-price-in-saudi-arabia

**Comment by serviceproviderpk** [comment]
3) on news detail and reviews detail  **RFR**
in bottom show  news list  title only just like below

![image](https://user-images.githubusercontent.com/19146254/44236007-fde36400-a1c4-11e8-9f03-8c6f3304c3e4.png)

**Comment by serviceproviderpk** [comment]
4) Make sure on home page of the website Cache is used for all partial views.
if not used then use Cache for it.

**Comment by serviceproviderpk** [comment]
@zaifullah786  as you fixed ,Please update status in github.
