### ISSUE TITLE
Nawaz

### ISSUE THREAD

**Issue by mubashir633** [serviceproviderpk/sp.pk#7]

**Comment by MalikNawaz77** [comment]
paractice the following topics
Blocks
classes
iframe

**Comment by MalikNawaz77** [comment]
Practice the following topics:
HTML java script
HTML file paths
HTML head
HTML layouts

**Comment by MalikNawaz77** [comment]
Doing bootstrap:
basic knowledge
grid
typography
table
image
jumbotron

**Comment by MalikNawaz77** [comment]
BootStrap:
wells
Alerts
buttons
button groups

**Comment by WaqarShah** [comment]
Reports:
Student summary and 2 other reports, proper implementation of header and footer in reports.

**Comment by serviceproviderpk** [comment]
Please try complete reports ASAP.

**Comment by MalikNawaz77** [comment]
Bootstrap Tutorial Covers the following topics:
BS Glyphicons
BS Badges/Labels
BS Progress Bars
BS Pagination
BS Pager
BS List Groups
BS Panels
BS Dropdowns

**Comment by WaqarShah** [comment]
Leaving certificates, defaulter list,
fee receipt print new , 3 Reports will be completed today.

**Comment by MalikNawaz77** [comment]
Bootstrap Tutorial

BS Collapse
BS Tabs/Pills
BS Navbar

**Comment by MalikNawaz77** [comment]
Bootstrap Grids
&
CSS all tags

**Comment by WaqarShah** [comment]
Set Vertical Dropdown menu on Madrassa Project and remove old vertical menu bar.

**Comment by MalikNawaz77** [comment]
jQuery Tutorial
jQuery HOME
jQuery Intro
jQuery Get Started
jQuery Syntax
jQuery Selectors
jQuery Events

**Comment by MalikNawaz77** [comment]
make two screens in bootstrap 
& 
perform 1 task assigned by Nasir bhai.
