### ISSUE TITLE
Yooslay Quick Feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#70]
1) in email template and domain URL will bet set from code from the fucntion

BusinessMangger.Auto detect domain uRL

2) in order confirmation email show order item as below, overall template is looking fine.

![image](https://user-images.githubusercontent.com/19146254/42743545-5d1a303e-88de-11e8-9088-dc6123099111.png)
3) on payment page filled informaiton sh'd be displayed

![image](https://user-images.githubusercontent.com/19146254/42743605-e52a73c6-88de-11e8-95f5-98b885231ae0.png)

4) when user choose item size and color use block UI
5) on find address function use block UI
06) in all places where we have  used jquery use block UI
7) on home page for this section use heading "Brands"
![image](https://user-images.githubusercontent.com/19146254/42743674-602b04dc-88df-11e8-9fe3-dcf68613dc4e.png)
8) shipment proper flow as, item is shiped send email to the customer including shippmnet template

it will be same as order, just will show shippment id and details.
as above points done, upload latest code on live and beta.

**Comment by adilshehbaz** [comment]
in email template and domain URL will bet set from code from the fucntion
BusinessMangger.Auto detect domain uRL **Fixed**

**Comment by adilshehbaz** [comment]
on payment page filled informaiton sh'd be displayed **Fixed**

**Comment by adilshehbaz** [comment]
on home page for this section use heading "Brands" **Fixed**

**Comment by adilshehbaz** [comment]
shipment proper flow as, item is shiped send email to the customer including shippmnet template **Fixed**

**Comment by adilshehbaz** [comment]
when user choose item size and color use block UI **Fixed**
on find address function use block UI **Fixed**
in all places where we have used jquery use block UI **Fixed**

**Comment by serviceproviderpk** [comment]
8) for error message and success message, use bootstrap alerts css
like .alert-success, .alert-info, .alert-warning
a) if user enter worng email id then show msg **Fixed**
b) forgot passowrd if user enter  **Fixed**
c) on register page, if user has already created an account.  **Fixed**
d) change password in customer dashobard  **Fixed**
9) still order confirmation email looking very childish  **Fixed**
10)  Consistency in block UI, use any image instead of text
11) test whole website in mobile UI and fixed overlapping and rendering issueai

**Comment by serviceproviderpk** [comment]
11)  suscriber, "Send email"

user sh;d be able to "un subsribe" **Fixed**

**Comment by serviceproviderpk** [comment]
12) 

Email | asifjans@gmail.com
-- | --
2109


in forgot password email use bold
and show like
this 
Email: Email
Password: password **Fixed**

**Comment by zaifullah786** [comment]
8.for error message and success message, use bootstrap alerts css
like .alert-success, .alert-info, .alert-warning
a) if user enter worng email id then show msg Fixed
b) forgot passowrd if user enter Fixed
c) on register page, if user has already created an account. Fixed
d) change password in customer dashobard Fixed
9.still order confirmation email looking very childish Fixed

**Comment by zaifullah786** [comment]
11)  suscriber, "Send email"

user sh;d be able to "un subsribe" **Fixed**

**Comment by zaifullah786** [comment]
12) 

Email | asifjans@gmail.com
-- | --
2109


in forgot password email use bold
and show like
this 
Email: Email
Password: password **Fixed**

**Comment by serviceproviderpk** [comment]
13) use seprator in footer **fixed**

**Comment by serviceproviderpk** [comment]
14) Rename "Create an Account " to  "Register" **Fixed**

**Comment by serviceproviderpk** [comment]
**release on beta , with diffrnt db** **Done**

**Comment by zaifullah786** [comment]
13) use seprator in footer **fixed**

**Comment by zaifullah786** [comment]
14) Rename "Create an Account " to  "Register" **Fixed**

**Comment by zaifullah786** [comment]
**release on beta , with diffrnt db** **Done**

**Comment by serviceproviderpk** [comment]
1)  Send Email to susbscriber page
remove to email

and write message

> You can send your offers and latest deals to all subscriber by single click, Please enter subject and message and click on "Submit"

**Comment by serviceproviderpk** [comment]
2) On this page http://beta.yooslay.co.uk/Dashboard/ManageNotification/Index

Add new button "Remove all Notifications" as user click on  it, all notifications from system will be deleted.

make title as "Link"

on type of the notification
Redirect "Subscriber list " or "Order List"

**Comment by serviceproviderpk** [comment]
3) If user try to login, and his email is not verified, then re-send verification link to the user

**Comment by serviceproviderpk** [comment]
4) Danger! Please enter valid email and password!.

remove word "Danger!"  and Warning etc from  error/success msg

**Comment by serviceproviderpk** [comment]
5) For loading icon for all website use same icon "that will be loading image as below"
e.g
![image](https://user-images.githubusercontent.com/19146254/43034198-71de214e-8cf1-11e8-81ce-3e63d2f3009a.png)

**Comment by serviceproviderpk** [comment]
a

**Comment by serviceproviderpk** [comment]
8) from admin menu remove menu "Menu category" **Fixed**
![image](https://user-images.githubusercontent.com/19146254/43502400-1c41b17a-9574-11e8-972e-2018e98662e4.png)
9)rename promotion tool to "Communcation" **Fixed**
![image](https://user-images.githubusercontent.com/19146254/43502425-3891cae0-9574-11e8-8916-e172e704609c.png)

**Comment by serviceproviderpk** [comment]
10) in  slide show / banner table add option
Enabled,Disable

Only slider images will be displayed on home page if it is enabled. **Fixed**

any time we can enabled/disalbed any slider image.
Please dont forget to all sql script in dbscript folder.

**Comment by serviceproviderpk** [comment]
11) Please make sure searching is working fine on all types of the users,admin,editor **Fixed**
![image](https://user-images.githubusercontent.com/19146254/43503169-8b5bb8aa-9577-11e8-9550-a79ebdd3f927.png)
search by name and customer id

**Comment by serviceproviderpk** [comment]
12) on forget password Please use  bootstrap alertbox **FIxed**
![image](https://user-images.githubusercontent.com/19146254/43503516-277aff9c-9579-11e8-9302-c281b0f05827.png)
13) in all email templates "From Email" will be  **Fixed**
info@yooslay.co.uk NOT user email
![image](https://user-images.githubusercontent.com/19146254/43503563-5bc9c116-9579-11e8-9c73-ff3392e85ccb.png)

**Comment by serviceproviderpk** [comment]
14) @adilshehbaz  on product detail if user click on small photo show block UI until photo not changed.
![image](https://user-images.githubusercontent.com/19146254/43503694-c25e9aa0-9579-11e8-950b-39a2e9b3ea65.png)

**Comment by serviceproviderpk** [comment]
15) if user add any coupon  show him any message **Fixed**

Please enter valid coupon code or Coupon discount is applied.
![image](https://user-images.githubusercontent.com/19146254/43503785-2ec27540-957a-11e8-8927-1caff23322cb.png)

**Comment by zaifullah786** [comment]
8)from admin menu remove menu "Menu category" Fixed
9)rename promotion tool to "Communcation" Fixed
10)in slide show / banner table add option
Enabled,Disable
11)Please make sure searching is working fine on all types of the users,admin,editor Fixed
12)on forget password Please use bootstrap alertbox FIxed
13)in all email templates "From Email" will be Fixed

**Comment by zaifullah786** [comment]
15) if user add any coupon  show him any message **Fixed**

**Comment by serviceproviderpk** [comment]
thanks
