### ISSUE TITLE
KFS UI

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#72]
1) 
![image](https://user-images.githubusercontent.com/19146254/43474971-caf35f82-950d-11e8-9d4c-b8f906498943.png)

**Comment by serviceproviderpk** [comment]
2) 
![image](https://user-images.githubusercontent.com/19146254/43475165-4ff18c86-950e-11e8-9d58-568e69d4dca8.png)
remove related product section from mobile UI and web ui
3) Login buttons are mixed up 
![image](https://user-images.githubusercontent.com/19146254/43475246-961f2d80-950e-11e8-8d1b-5a7adfde2a38.png)
4) on shopping cart button and text box are touched
![image](https://user-images.githubusercontent.com/19146254/43475299-c4fbd8ec-950e-11e8-92c1-bc20f0ce36c3.png)
5) on check out page  checkbox and text sh'd be in one line

![image](https://user-images.githubusercontent.com/19146254/43475384-fc965f0c-950e-11e8-8a79-2677e4edf7ce.png)

**Comment by serviceproviderpk** [comment]
4) if close contine (for asif)

**Comment by adilshehbaz** [comment]
1- **Fixed**
2- **Fixed**
3- **Fixed**
4- **Fixed**
5- **Fixed**

**Comment by serviceproviderpk** [comment]
Thanks
