### ISSUE TITLE
YS

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#73]
1) button touching each other
![image](https://user-images.githubusercontent.com/19146254/44893804-295a6880-ad06-11e8-8654-273c252615e2.png)
2) when user add a product by default set "Default Color" and size Stock as "0"
3) While user upload image for category or product use validation of image size
image of more than 2 MB sh'd not be uploaded.
if user upload 10MB image,  website will give error memory out of exception.
4) color ,Size and Size Guide sh'd be in one line
below this line show brief description of the product, right now page is looking empty
as have increased the height of the image.
if there is no field in db for "Breif Description"  we can add it.
5) If user is not logged and view "Reviewes" on detail page.
then hide submit review section (as below)
![image](https://user-images.githubusercontent.com/19146254/44894039-52c7c400-ad07-11e8-968e-ca5bdbb41435.png)

show only text "Please login/register" to submit your reviews

if user is logged in the nick name will be pre fill.

**Comment by serviceproviderpk** [comment]
6) email those will be send via newsletter add link of "Unsubsribe" this link was already in email template.

**Comment by adilshehbaz** [comment]
@serviceproviderpk 
1- Fixed
2- Need to discuss
3- Fixed
4- Not Yet as Discussed
5- Fixed
6- Already Fixed
