### ISSUE TITLE
new era mag

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#76]
we have reference website as   https://mybeammag.com/  and  http://sohnidigest.com/

1) User will be able to upload data as images or PDF (we will allow  X MB size of pdf)
so admin can split one book with different pdf files.
2) ON home page will display banner from  admag theme ans others list page and detail page will remain same

**Comment by serviceproviderpk** [comment]
3) we will have following menu
Home | Books  | Novels | Essays & Articles | Poetry | About Us

**Comment by serviceproviderpk** [comment]
we will use existing tables, you can modify if any field is required to add/edit.

we will remove register button, there will be only two type user
admin and Authors

**Comment by serviceproviderpk** [comment]
download inncerexepton code+db make it new copy with name
NewEraMag and work daily 2 hours on it.

**Comment by serviceproviderpk** [comment]
replace innerexception with NewEraMag in views+routes

**Comment by serviceproviderpk** [comment]
Articles=Novels
Post=Books
news=Poerty
Questions=Essays & Articles

**Comment by adilshehbaz** [comment]
Articles = Articles & Essays

News = News

Posts = Poetry

Project = Books

Template = Novels
