### ISSUE TITLE
Suppport System

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#77]
1) Login
2) Register
3) Change Passowrd
4) Edit Profile
5) Task list (add/edit/delete/search)

6) if user is logged in show him his created user id and assigned to user id.

int userid=sesssion

storedb.Taskmanagmen.where(w=>w.assginedto==userid)

my tasks

storedb.Taskmanagmen.where(w=>w.assginedto==userid)

my reqquest

storedb.Taskmanagmen.where(w=>w.assginedbyuserid==userid)

7) EmployeeLeave:

any employe can login and apply for leave, and senior employe will reviview the  leave application
and will approve and reject the leave,

**Table**

EmployeeLeaves:Id,EmployeeID,LeaveType,AssignTo,LeaveStatus,Apporvedby, ApprovedDate

**Comment by Abuzarmehdi954** [comment]
1)  done
2)  done
3)  done
4)  done
5)  done

**Comment by Abuzarmehdi954** [comment]
6. done
