### ISSUE TITLE
Yooslay urgent

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#78]
1) Check feedback of email
2) in products and Category show "Parent Category" name also
3) Add Created by and Last Updated by column in category and products grids
4) change loading icon to "Yooslay" move left and right
5)  in admins section (append main category name) in add/edit product
![image](https://user-images.githubusercontent.com/19146254/48244820-5ebbba80-e409-11e8-963e-f49b5e80b977.png)

new arrival is in both category Asia and English so we need to append main category in it.
6) when user register and place (before going to payment page) send email to service@service...pk

**Comment by serviceproviderpk** [comment]
7) Main Category color "Dark Gray"
8) if user is logged in  and user type is admin
then show edit button on product detail page, so that admin can edit any product with searching from dashboard.

**Comment by adilshehbaz** [comment]
All issues fixed
