### ISSUE TITLE
Aiphs.pk

### ISSUE THREAD

**Issue by adilshehbaz** [serviceproviderpk/sp.pk#80]
1- Student Admission Report Formating
2- Fee Collection Report Formating

**Comment by adilshehbaz** [comment]
**RFR**

**Comment by serviceproviderpk** [comment]
have updated dawood it isfixed?

**Comment by serviceproviderpk** [comment]
1) When User login to the software/portal please save login details

**Comment by serviceproviderpk** [comment]
2) Change Page title,keywords, description of its Home page only right now it is showing for school managment software

**Comment by serviceproviderpk** [comment]
3) if i click on Send button it is giving error.
it must save in table. if not table in db you can create, make sure copy script of the table
in admin section show list of subscribers

**Comment by serviceproviderpk** [comment]
4) set social icons
![image](https://user-images.githubusercontent.com/19146254/55844084-10941a00-5b55-11e9-9820-b077618a8c2c.png)
in foooter and top
![image](https://user-images.githubusercontent.com/19146254/55844097-24d81700-5b55-11e9-8f15-3fc292bba235.png)

in top in social icons use some space  links are looking conjusted.

**Comment by serviceproviderpk** [comment]
5) 
![image](https://user-images.githubusercontent.com/19146254/55844118-45a06c80-5b55-11e9-8f7a-123e67c648f1.png)
add website link , if is changed from Database table then change it in database
adil will guide you.

**Comment by serviceproviderpk** [comment]
6) 
![image](https://user-images.githubusercontent.com/19146254/55844162-6d8fd000-5b55-11e9-9b82-e8fef631a361.png)
use compnay name "Asian Institute of Pharmacy & Health Sciences (AIPHS)"

**Comment by serviceproviderpk** [comment]
7) increase logo size 
![image](https://user-images.githubusercontent.com/19146254/55844233-bd6e9700-5b55-11e9-984d-480d33baf56f.png)
atleast it is readable and give some good look.as much as its look good.

**Comment by serviceproviderpk** [comment]
8) use same green as green color is used in logo
![image](https://user-images.githubusercontent.com/19146254/55844344-4980be80-5b56-11e9-8400-68d0bd4bff38.png)

**Comment by serviceproviderpk** [comment]
9) if user click on logo (top logo and footer logo) redirect to  Home page "/"

**Comment by serviceproviderpk** [comment]
10) on login page show logo of aipsh http://aiphs.pk/Account/Login
you can change color sceme of login page if required.

**Comment by serviceproviderpk** [comment]
11) Explore database of  whole project and test system after login
so that i can assign some task related to admin.

**Comment by adilshehbaz** [comment]
Search on Attendance

**Comment by adilshehbaz** [comment]
Staff Sallery

**Comment by adilshehbaz** [comment]
On Fee Receipt Total Annual Amount, Paid, Balance hide in print

**Comment by adilshehbaz** [comment]
Fee Record Amount Issue

**Comment by adilshehbaz** [comment]
Fee Collect Report

**Comment by adilshehbaz** [comment]
Stock Management

**Comment by adilshehbaz** [comment]
Books Registration Separate

**Comment by Abuzarmehdi954** [comment]
> 1. When User login to the software/portal please save login details

**Comment by Abuzarmehdi954** [comment]
RFR
