### ISSUE TITLE
Feedback SP.PK

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#90]
1) 
 a) in customer support edit add check box list
that will show list of users which are admin and developers

![image](https://user-images.githubusercontent.com/19146254/54081414-77d86780-4326-11e9-8ef3-a7730abb69b4.png)

if we will  tick any user, we will send email to that user

that please work on this issue.

b) /ManageCustomerSupport/Index
if task prority is high set row color to red
if mid yellow

c) in left menu add new page
"SystemLookup"
show Add/edit of each table that is used in this website. use some other resource on it.

2)  in Timesheet  http://www.serviceprovider.pk/TimeSheets/Index

if user click on "Project Name" create  new page show list of task of this project only
in table form just like  ID,TaskDate,Description,

3) Payments add/edit/delete
4)  link spacing
![image](https://user-images.githubusercontent.com/19146254/54015558-df18df00-41a1-11e9-864b-958951f5baa0.png)
5) error on followup http://www.serviceprovider.pk/Enquiry/FollowUpList

**Comment by serviceproviderpk** [comment]
5)

![image](https://user-images.githubusercontent.com/19146254/52929451-4cd1a800-3366-11e9-9caa-2336ffc0b3bb.png)
 on home page we are showing Data from testimonial or customer review
in admin section do it add/edit/delete list page.
![image](https://user-images.githubusercontent.com/19146254/52929428-3297ca00-3366-11e9-8ad0-3936ad0f3351.png)

**Comment by serviceproviderpk** [comment]
5) in customer list, above the Genrate invoice, add new button
"Services"
if user will click on this, we will show services of this customer.
in service list page we will send customer Id to show data of this customer.

**Comment by serviceproviderpk** [comment]
6) in edit invoice add "Delete"
as user click on it 
we will send a link to admin to delete this invoice
http://www.serviceprovider.pk/InvoiceManager/InvoiceCrud?id=2

7) on make payment page show invoice description instead of id of invoice

**Comment by serviceproviderpk** [comment]
after this task please work on neweramage

**Comment by danishaali9** [comment]
Tasks which are done
1.
b),c)
2,3,4,5,7

**Comment by danishaali9** [comment]
Pending Issues
1 a)
5 b), 5 c), 6

**Comment by danishaali9** [comment]
8. customer services ->  a button showing customer list

9. in invocie manager -> text box description
