### ISSUE TITLE
Saudi Phone

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#93]
1) Please check news detail page
it is showing zig at bottom
http://saudi-phone.com/news/salvaged-samsung-galaxy-note-7-parts-may-be-about-to-go-on-sale-in-new-phones-597134

**Comment by serviceproviderpk** [comment]
2) Check news list page it is not showing latest news on top.

**Comment by serviceproviderpk** [comment]
3) if news title is big use Truncate function from BusinessManager.
abuzr can guide you.
![image](https://user-images.githubusercontent.com/19146254/55844850-ce6cd780-5b58-11e9-893d-6e38525065a3.png)

**Comment by serviceproviderpk** [comment]
4) website not showing favicon
![image](https://user-images.githubusercontent.com/19146254/55844891-f0fef080-5b58-11e9-9468-fff056a8bc8a.png)

**Comment by serviceproviderpk** [comment]
5) for product details, we need a logic
we will split product title in two arrays of character

on this list of those character we will get news details
and will display those news below the product price list.

we will create a partial to that partial view will send a  "Product Name" as string that will return list of news title,description, created date and news category.

i will explain it to you and abuzr.

list of characters
List<news> newslist=new List<news>();
foreach(item in list)
{
 // get news list by string 
// addnes in list.

}
return news list.

**Comment by serviceproviderpk** [comment]
as above task done.

please use admin section list down if you face any issue. while using this website.

**Comment by serviceproviderpk** [comment]
- admin section add new link "Manage News"
show list of news and also add new button "Add news"
check if this working is already in the dashobard.

**Comment by danishaali9** [comment]
- product and feature
