### ISSUE TITLE
ips

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#98]
1- affiliation=> new page edit able from admin
2- option to add/edite/delete in static page
we will add new menu pages

3- use header logo in all places

4- change certifications to "Distance learning
![image](https://user-images.githubusercontent.com/19146254/57753309-4359a100-7705-11e9-8365-ec2847250055.png)

5- from homepage remove
![image](https://user-images.githubusercontent.com/19146254/57752228-d7296e00-7701-11e9-90b4-a7c10207435a.png)

show news scrolling

**Comment by serviceproviderpk** [comment]
6- remove this section
![image](https://user-images.githubusercontent.com/19146254/57752253-f0321f00-7701-11e9-8ea6-c31af17adeaf.png)

**Comment by serviceproviderpk** [comment]
7- move able news
![image](https://user-images.githubusercontent.com/19146254/57752286-0d66ed80-7702-11e9-9b30-1f2ebebbc5b8.png)

**Comment by serviceproviderpk** [comment]
8- increase size
![image](https://user-images.githubusercontent.com/19146254/57752337-42734000-7702-11e9-8955-fbd377e33b04.png)

**Comment by serviceproviderpk** [comment]
9-
![image](https://user-images.githubusercontent.com/19146254/57752382-6fbfee00-7702-11e9-94c0-61cd1891ab11.png)
decrease hight in all pages
and remove apply now button

**Comment by serviceproviderpk** [comment]
10- 
![image](https://user-images.githubusercontent.com/19146254/57752427-92520700-7702-11e9-9986-ab36b372a9f4.png)
11- move it up
![image](https://user-images.githubusercontent.com/19146254/57752453-b01f6c00-7702-11e9-92b6-6f32e13330d4.png)

remove enquiry section from here

**Comment by serviceproviderpk** [comment]
12- logout button must working and clear session

**Comment by serviceproviderpk** [comment]
13-
![image](https://user-images.githubusercontent.com/19146254/57752549-055b7d80-7703-11e9-93a3-5d82b9218994.png)
must have only following inforamtion in admin section

Ttitle,
duration
Eligibilty
required documents
photo
Coursefee
Other

**Comment by serviceproviderpk** [comment]
14- add/edit/delete option in all sections of admin
15- getting erorr when click on "FAQ " page

**Comment by serviceproviderpk** [comment]
15-reduce text boxex size
show contact detail on top
![image](https://user-images.githubusercontent.com/19146254/57752744-916da500-7703-11e9-8ca7-db9da530e745.png)

**Comment by serviceproviderpk** [comment]
16- increase font size
![image](https://user-images.githubusercontent.com/19146254/57752823-cf6ac900-7703-11e9-9ee6-6b835bd0e9d4.png)

change to  20 px

**Comment by serviceproviderpk** [comment]
17- 
![image](https://user-images.githubusercontent.com/19146254/57752878-fde8a400-7703-11e9-8a71-9007fc27e18b.png)
show news marquee between slider and this section

**Comment by serviceproviderpk** [comment]
18- change color to red of logo color
![image](https://user-images.githubusercontent.com/19146254/57752944-28d2f800-7704-11e9-9132-14560aaf7932.png)

**Comment by serviceproviderpk** [comment]
19- change logo 
![image](https://user-images.githubusercontent.com/19146254/57752973-41dba900-7704-11e9-82fa-192e5b3e2f98.png)

remove register button

**Comment by serviceproviderpk** [comment]
20- http://ipslahore.pk/ManageEnquiry
delete option

**Comment by serviceproviderpk** [comment]
21-faqs

**Comment by serviceproviderpk** [comment]
22-Daily Task
Timesheet

**Comment by serviceproviderpk** [comment]
23- system user

**Comment by serviceproviderpk** [comment]
24-other pages

**Comment by SajjadAhmad111** [comment]
feedback by sir asif

inquiry - no edit button

courses - - add delete button - 

upper than distance learning 
new scrolling

news image

feedback by sir asif

user - add edit delete

users are of two types	normal	admin
normal user will ony have access to timesheet(staff report)
table-admin
timesheet - new crud to be made
admin will have overall all screens of admin access

add applynow in green box - courses by category
