### ISSUE TITLE
Quick feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sp.pk#99]
1- In emplyee grid show email

**Comment by serviceproviderpk** [comment]
2- You are logged in  Branch|Staff|whatevertype
![image](https://user-images.githubusercontent.com/19146254/57830872-e45f5f00-77cc-11e9-8e37-ecb82ca54c44.png)
rename to Account Details
when user click on it. show new in new tab

**Comment by serviceproviderpk** [comment]
3- Branch Name:

**Comment by TahirHussai** [comment]
1.fixed
2.fixed
